### ISSUE TITLE
Fragment and options menu

### ISSUE THREAD

**Issue by pietrocaselani** [Prototik/HoloEverywhere#102]
I made an app that uses ViewPager with fragments.
Each fragment has a options menu, but the menu only show when you press the menu button.
When the fragment will inflate the menu, the app crash.

On logcat appears this message:

java.lang.NoSuchMethodError: android.view.MenuItem.setShowAsAction at com.actionbarsherlock.internal.view.menu.MenuItemWrapper.setShowAsAction(MenuItemWrapper.java:207)

I made the same app only using ABS, and works fine.
My activity extends from SActivity, the fragments extends from SFragment and I use the theme Holo.Theme.Sherlock.
I test the app on devices with Android 2.2 and 2.3.

Sorry for the english.

**Comment by Prototik** [comment]
Full stacktrace, please.

**Comment by pietrocaselani** [comment]
ERROR/AndroidRuntime(19806): FATAL EXCEPTION: main
        java.lang.NoSuchMethodError: android.view.MenuItem.setShowAsAction
        at com.actionbarsherlock.internal.view.menu.MenuItemWrapper.setShowAsAction(MenuItemWrapper.java:207)
        at com.actionbarsherlock.view.MenuInflater$MenuState.setItem(MenuInflater.java:401)
        at com.actionbarsherlock.view.MenuInflater$MenuState.addItem(MenuInflater.java:445)
        at com.actionbarsherlock.view.MenuInflater.parseMenu(MenuInflater.java:175)
        at com.actionbarsherlock.view.MenuInflater.inflate(MenuInflater.java:97)
        at com.pc.tests.DemoHolo.Fragment1.onCreateOptionsMenu(Fragment1.java:32)
        at com.WazaBe.HoloEverywhere.sherlock.SFragment.onCreateOptionsMenu(SFragment.java:45)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:1877)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:210)
        at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:305)
        at com.android.internal.policy.impl.PhoneWindow.onKeyDownPanel(PhoneWindow.java:550)
        at com.android.internal.policy.impl.PhoneWindow.onKeyDown(PhoneWindow.java:1197)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1653)
        at android.view.ViewRoot.deliverKeyEventToViewHierarchy(ViewRoot.java:2471)
        at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2441)
        at android.view.ViewRoot.handleMessage(ViewRoot.java:1735)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:4627)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:521)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by Prototik** [comment]
Then I want to congratulate you - you are the master. To date, the library has a bug that makes it impossible to create a menu in fragments.
Bug confirmed.
