### ISSUE TITLE
HoloDemo not work on emulator 2.3.3

### ISSUE THREAD

**Issue by ru-nekit-android** [Prototik/HoloEverywhere#115]
``` java
10-03 14:38:14.868: E/AndroidRuntime(920): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.WazaBe.HoloDemo/com.WazaBe.HoloDemo.DemoActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class com.actionbarsherlock.internal.widget.ActionBarContextView
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.app.ActivityThread.access$1500(ActivityThread.java:117)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.os.Handler.dispatchMessage(Handler.java:99)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.os.Looper.loop(Looper.java:123)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.app.ActivityThread.main(ActivityThread.java:3683)
10-03 14:38:14.868: E/AndroidRuntime(920):  at java.lang.reflect.Method.invokeNative(Native Method)
10-03 14:38:14.868: E/AndroidRuntime(920):  at java.lang.reflect.Method.invoke(Method.java:507)
10-03 14:38:14.868: E/AndroidRuntime(920):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
10-03 14:38:14.868: E/AndroidRuntime(920):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
10-03 14:38:14.868: E/AndroidRuntime(920):  at dalvik.system.NativeStart.main(Native Method)
10-03 14:38:14.868: E/AndroidRuntime(920): Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class com.actionbarsherlock.internal.widget.ActionBarContextView
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.view.LayoutInflater.createView(LayoutInflater.java:518)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:626)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
10-03 14:38:14.868: E/AndroidRuntime(920):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.generateLayout(ActionBarSherlockCompat.java:1049)
10-03 14:38:14.868: E/AndroidRuntime(920):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.installDecor(ActionBarSherlockCompat.java:919)
10-03 14:38:14.868: E/AndroidRuntime(920):  at com.actionbarsherlock.internal.ActionBarSherlockCompat.setContentView(ActionBarSherlockCompat.java:853)
10-03 14:38:14.868: E/AndroidRuntime(920):  at com.WazaBe.HoloEverywhere.sherlock.SActivity.setContentView(SActivity.java:247)
10-03 14:38:14.868: E/AndroidRuntime(920):  at com.WazaBe.HoloDemo.DemoActivity.onCreate(DemoActivity.java:84)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
10-03 14:38:14.868: E/AndroidRuntime(920):  ... 11 more
10-03 14:38:14.868: E/AndroidRuntime(920): Caused by: java.lang.reflect.InvocationTargetException
10-03 14:38:14.868: E/AndroidRuntime(920):  at java.lang.reflect.Constructor.constructNative(Native Method)
10-03 14:38:14.868: E/AndroidRuntime(920):  at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.view.LayoutInflater.createView(LayoutInflater.java:505)
10-03 14:38:14.868: E/AndroidRuntime(920):  ... 24 more
10-03 14:38:14.868: E/AndroidRuntime(920): Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x2
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.view.View.<init>(View.java:2108)
10-03 14:38:14.868: E/AndroidRuntime(920):  at android.view.ViewGroup.<init>(ViewGroup.java:292)
10-03 14:38:14.868: E/AndroidRuntime(920):  at com.actionbarsherlock.internal.nineoldandroids.view.NineViewGroup.<init>(NineViewGroup.java:21)
10-03 14:38:14.868: E/AndroidRuntime(920):  at com.actionbarsherlock.internal.widget.AbsActionBarView.<init>(AbsActionBarView.java:65)
10-03 14:38:14.868: E/AndroidRuntime(920):  at com.actionbarsherlock.internal.widget.ActionBarContextView.<init>(ActionBarContextView.java:78)
10-03 14:38:14.868: E/AndroidRuntime(920):  at com.actionbarsherlock.internal.widget.ActionBarContextView.<init>(ActionBarContextView.java:74)
10-03 14:38:14.868: E/AndroidRuntime(920):  ... 27 more
```

**Comment by Prototik** [comment]
It's ABS bug and it was fixed in dev branch.

**Comment by ru-nekit-android** [comment]
With dev branch of ABS Holo not work at all) epic fail

**Comment by Prototik** [comment]
Короче, давай на русском :D
Це значит не работает все?
Да и потом, никто не говорил всю ветку брать, взял бы нужный коммит, слил с тем форком, что у кристофа -  вуаля.

**Comment by ru-nekit-android** [comment]
Ура зработало!!!

**Comment by Prototik** [comment]
Ну я рад. :D
Хотя, я вообще не понимаю, почему оно не работало.
(да, я не колупал тот злосчастный коммит).
Ну да хер с ним, счастливого коддинга, так сказать :D
