### ISSUE TITLE
Footer view in ListView

### ISSUE THREAD

**Issue by pietrocaselani** [Prototik/HoloEverywhere#150]
I am getting this exception when I try to add a footer view on ListView.

```
10-18 11:52:54.503: ERROR/AndroidRuntime(13372): FATAL EXCEPTION: main
        java.lang.NullPointerException
        at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:778)
        at android.widget.ListView.addFooterView(ListView.java:346)
        at com.flipstudio.portal.recreiodajuventude.fragments.EventsFragment.updateHeaderView(EventsFragment.java:232)
        at com.flipstudio.portal.recreiodajuventude.fragments.EventsFragment.onEventRequestSuccess(EventsFragment.java:286)
        at com.flipstudio.portal.recreiodajuventude.requests.EventsRequest.onPostExecute(EventsRequest.java:79)
        at com.flipstudio.portal.recreiodajuventude.requests.EventsRequest.onPostExecute(EventsRequest.java:16)
        at android.os.AsyncTask.finish(AsyncTask.java:417)
        at android.os.AsyncTask.access$300(AsyncTask.java:127)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:429)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:4627)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:521)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
        at dalvik.system.NativeStart.main(Native Method)
```

I tested on Android 2.2, but in the Jelly Bean/ICS works greats.

**Comment by Prototik** [comment]
Show me here at least one class of HoloEverywhere.

**Comment by pietrocaselani** [comment]
```
at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:778)
```

Should not use the AdapterView of HE?

**Comment by Prototik** [comment]
No, ListView yet native.

**Comment by pietrocaselani** [comment]
OK, sorry for the inconvenience
