### ISSUE TITLE
Suggested Proguard configuration for HE

### ISSUE THREAD

**Issue by arcao** [Prototik/HoloEverywhere#154]
Hello Christophe and Sergey,

I am trying to integrate HE to my existing project but I found problem with Proguard configuration. Just now I am using default proguard-android.txt plus custom Proguard configuration because of easier reading crash logs sent via ACRA:

```
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*,!code/allocation/variable
-optimizationpasses 5
-verbose

#prevent severe obfuscation
-keep,allowshrinking,allowoptimization class * { <methods>; } 

#-keep public class * extends android.app.Application
#-keep public class * extends android.app.Service
#-keep public class * extends android.content.BroadcastReceiver
#-keep public class * extends android.content.ContentProvider
#-keep public class * extends android.app.backup.BackupAgentHelper
#-keep public class * extends android.preference.Preference
##-keep public class com.android.vending.licensing.ILicensingService


-keepclasseswithmembernames,allowshrinking class * {
    native <methods>;
}

-keepclasseswithmembers,allowshrinking class * {
    public <init>(android.content.Context,android.util.AttributeSet);
    public <init>(android.content.Context,android.util.AttributeSet,int);
}

-keepclassmembers class * {
    public <init>(android.content.Context,android.util.AttributeSet);
    public <init>(android.content.Context,android.util.AttributeSet,int);
}

# keep this class so that logging will show 'ACRA' and not a obfuscated name like 'a'.
# Note: if you are removing log messages elsewhere in this file then this isn't necessary
-keep class org.acra.ACRA {
        *;
}

# keep this around for some enums that ACRA needs
-keep class org.acra.ReportingInteractionMode {
   *;
}

# keep this otherwise it is removed by ProGuard
-keep public class org.acra.ErrorReporter
{
public void addCustomData(java.lang.String,java.lang.String);
}

# keep this otherwise it is removed by ProGuard
-keep public class org.acra.ErrorReporter
{
public org.acra.ErrorReporter$ReportsSenderWorker handleSilentException(java.lang.Throwable);
}

# keep bean getters for geocaching-api
-keep class com.arcao.geocaching.api.data.** {
    *** is*(); 
    *** get*();
}

# keep mExtraOnDisplay
-keep class menion.android.locus.addon.publiclib.geoData.Point {
    private java.lang.String mExtraOnDisplay; 
}

-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable #needed
-keepattributes Signature # Needed by google-api-client #to make XStream work with obfuscation?
-keepattributes EnclosingMethod #required?
-keepattributes InnerClasses #required?

-keepattributes Exceptions # can be removed?
-keepattributes Deprecated # can be removed?
-keepattributes Synthetic # can be removed?

-dontwarn org.apache.log4j.**
-dontwarn org.apache.commons.codec.binary.**
```

But this cause NPE when any SActivity is shown:

```
java.lang.ExceptionInInitializerError
      at com.WazaBe.HoloEverywhere.app.Activity.getSystemService(SourceFile:86)
      at android.view.LayoutInflater.from(LayoutInflater.java:210)
      at com.android.internal.policy.impl.PhoneWindow.<init>(PhoneWindow.java:199)
      at com.android.internal.policy.impl.Policy.makeNewWindow(Policy.java:63)
      at com.android.internal.policy.PolicyManager.makeNewWindow(PolicyManager.java:59)
      at android.app.Activity.attach(Activity.java:4427)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2018)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2104)
      at android.app.ActivityThread.access$600(ActivityThread.java:132)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1157)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loop(Looper.java:137)
      at android.app.ActivityThread.main(ActivityThread.java:4575)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:511)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
      at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
      at com.WazaBe.HoloEverywhere.app.Application$Config.getWidgetsPackage(SourceFile:86)
      at com.WazaBe.HoloEverywhere.LayoutInflater.<clinit>(SourceFile:46)
... 18 more
java.lang.NullPointerException
      at com.WazaBe.HoloEverywhere.app.Application$Config.getWidgetsPackage(SourceFile:86)
      at com.WazaBe.HoloEverywhere.LayoutInflater.<clinit>(SourceFile:46)
      at com.WazaBe.HoloEverywhere.app.Activity.getSystemService(SourceFile:86)
      at android.view.LayoutInflater.from(LayoutInflater.java:210)
      at com.android.internal.policy.impl.PhoneWindow.<init>(PhoneWindow.java:199)
      at com.android.internal.policy.impl.Policy.makeNewWindow(Policy.java:63)
      at com.android.internal.policy.PolicyManager.makeNewWindow(PolicyManager.java:59)
      at android.app.Activity.attach(Activity.java:4427)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2018)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2104)
      at android.app.ActivityThread.access$600(ActivityThread.java:132)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1157)
      at android.os.Handler.dispatchMessage(Handler.java:99)
      at android.os.Looper.loop(Looper.java:137)
      at android.app.ActivityThread.main(ActivityThread.java:4575)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:511)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
      at dalvik.system.NativeStart.main(Native Method)
```

When I try to disable Proguard it works ok. Is there any suggested Proguard configuration for HE?

**Comment by Prototik** [comment]
ProGuard remove annotation, try to add rule for save them.

**Comment by emileb** [comment]
Just updated HE and getting similar error when using Alert Dialog. Proguard already saves annotation. Any luck in a fix? Need one asap as delaying release of app! 

Thanks!
Emile.

**Comment by emileb** [comment]
Ok think it works with the following, not ideal but at least does not crash now:

-keep class  com.WazaBe.HoloEverywhere.*\* { *; }

-keepclassmembers public class  com.WazaBe.HoloEverywhere.*\* {
    *;
}

**Comment by arcao** [comment]
In my case it was caused by missing empty constructor for *Property classes.

After some tests I use bellow Proguard configuration but I think it's still not optimal.

```
# HoloEverywhere
-keep,allowoptimization class com.WazaBe.HoloEverywhere.** { 
    public *;
    protected *;
}
-keep,allowoptimization interface com.WazaBe.HoloEverywhere.** { *; }
```
