### ISSUE TITLE
SearchView widget

### ISSUE THREAD

**Issue by xavifc** [Prototik/HoloEverywhere#156]
Is there support for SearchView from ActionBar Sherlock? It's not working on a 4.0 device

``` java
10-22 10:26:20.256: E/AndroidRuntime(5808): android.view.InflateException: Binary XML file line #29: Error inflating class <unknown>
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.view.LayoutInflater.createView(LayoutInflater.java:606)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.actionbarsherlock.widget.SearchView.<init>(SearchView.java:266)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.actionbarsherlock.widget.SearchView.<init>(SearchView.java:253)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at MyActivity.onCreateOptionsMenu(MyActivity.java:72)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.support.v4.app.Watson.onCreatePanelMenu(Watson.java:45)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:559)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchCreateOptionsMenu(ActionBarSherlockNative.java:60)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.actionbarsherlock.app.SherlockFragmentActivity.onCreatePanelMenu(SherlockFragmentActivity.java:165)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:409)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:760)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:3003)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.os.Handler.handleCallback(Handler.java:605)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.os.Handler.dispatchMessage(Handler.java:92)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.os.Looper.loop(Looper.java:137)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.app.ActivityThread.main(ActivityThread.java:4512)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at java.lang.reflect.Method.invokeNative(Native Method)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at java.lang.reflect.Method.invoke(Method.java:511)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at dalvik.system.NativeStart.main(Native Method)
10-22 10:26:20.256: E/AndroidRuntime(5808): Caused by: java.lang.reflect.InvocationTargetException
10-22 10:26:20.256: E/AndroidRuntime(5808):     at java.lang.reflect.Constructor.constructNative(Native Method)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.view.LayoutInflater.createView(LayoutInflater.java:586)
10-22 10:26:20.256: E/AndroidRuntime(5808):     ... 25 more
10-22 10:26:20.256: E/AndroidRuntime(5808): Caused by: android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x7f01001f a=-1}
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.content.res.Resources.loadColorStateList(Resources.java:2073)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.content.res.TypedArray.getColorStateList(TypedArray.java:342)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.widget.TextView.<init>(TextView.java:913)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at android.widget.TextView.<init>(TextView.java:573)
10-22 10:26:20.256: E/AndroidRuntime(5808):     at com.WazaBe.HoloEverywhere.widget.TextView.<init>(TextView.java:24)
10-22 10:26:20.256: E/AndroidRuntime(5808):     ... 28 more
```

**Comment by Prototik** [comment]
Try with dev branch.

**Comment by xavifc** [comment]
It's working on dev version, thanks.

**Comment by donotwarry** [comment]
I also occur the promble in SearchView on 4.0 device, in 2.3 device it's ok. but in my other project, that's ok, I can't find out what's different with them.

**Comment by RobGThai** [comment]
@Prototik any chance you could outline what exactly is the issue here? I'm trying to get around this but I don't use HoloEverywhere in my project at all. I was hoping a few modification to ABS stable sources could do the trick.

**Comment by Prototik** [comment]
@RobGThai attr/textColorPrimary (without android: prefix) not defined for v14 themes.
