### ISSUE TITLE
NoSuchMethodError when calling Fragment#setHasOptionsMenu.

### ISSUE THREAD

**Issue by tmurakami** [Prototik/HoloEverywhere#170]
HE 1.3.3 on Android 2.2 (API 8) Emulator.

MyFragment:

``` java
@Override
public void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  setHasOptionsMenu(true);
```

StackTrace:

```
10-17 05:27:08.517: E/AndroidRuntime(1536): java.lang.NoSuchMethodError: android.support.v4.app._HoloActivity.invalidateOptionsMenu
10-17 05:27:08.517: E/AndroidRuntime(1536):     at android.support.v4.app._HoloActivity.supportInvalidateOptionsMenu(_HoloActivity.java:94)
10-17 05:27:08.517: E/AndroidRuntime(1536):     at android.support.v4.app.Fragment.setHasOptionsMenu(Fragment.java:712)
10-17 05:27:08.517: E/AndroidRuntime(1536):     at x.y.z.fragment.MyFragment.onCreate(MyFragment.java:153)
10-17 05:27:08.517: E/AndroidRuntime(1536):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:835)
```

Activity#invalidateOptionsMenu is not available prior to HoneyComb.

**Comment by Prototik** [comment]
This fix will be available only in 1.4 release, please wait, it soon.
