### ISSUE TITLE
DialogFragment.show() throws NullPointerException

### ISSUE THREAD

**Issue by Zeliret** [Prototik/HoloEverywhere#172]
Thats how i showing a dialog:

``` java
private void showProgressDialog(final int msgId) {
        if( null == progressDialog ){
            progressDialog = new ProgressDialog(msgId);
        }

        progressDialog.show();
    }
```

And here i get exception:

```
ERROR/AndroidRuntime(7682): FATAL EXCEPTION: main
        java.lang.NullPointerException
        at com.WazaBe.HoloEverywhere.app.DialogFragment.show(DialogFragment.java:303)
        at mega.app.activity.HomeActivity.showProgressDialog(HomeActivity.java:114)
        at mega.app.activity.HomeActivity.authenticateAccount(HomeActivity.java:122)
        at mega.app.activity.HomeActivity.access$300(HomeActivity.java:37)
        at mega.app.activity.HomeActivity$AccountDialog.onClick(HomeActivity.java:444)
        at com.WazaBe.HoloEverywhere.internal.AlertController$AlertParams$3.onItemClick(AlertController.java:216)
        at android.widget.AdapterView.performItemClick(AdapterView.java:284)
        at android.widget.ListView.performItemClick(ListView.java:3763)
        at com.WazaBe.HoloEverywhere.widget.ListView.performItemClick(ListView.java:168)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:1918)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:3687)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
        at dalvik.system.NativeStart.main(Native Method)
```

DialogFragment has 4 "show" methods, but 2 of them are depricated. One of the remain has no arguments and throws exception above, second "show" takes FragmentTransaction object. Only with that method i can evade this error... So what the "show()" method for? Should i use only show(FragmentTransaction ft)?

**Comment by Prototik** [comment]
Because DialogFragment does not have reference to any context. So it's crashs. And it's better to use replace (FragmentTransaction)

**Comment by Zeliret** [comment]
As i thought. Its just a bit wierd to mark this method as public ))

If u dont mind could u explain how to use show/replace in pair with hide? For example:

``` java
private void showProgressDialog(final int msgId) {
        if (null == progressDialog) {
            progressDialog = new ProgressDialog(msgId);
        }

        final FragmentManager fm = getSupportFragmentManager();
        progressDialog.replace(fm, fm.beginTransaction());
    }

    private void hideProgressDialog() {
        final FragmentManager fm = getSupportFragmentManager();
        progressDialog.hide(fm, fm.beginTransaction());
    }
```

I have such methods. First method works fine but second doesn't hide dialog... i dunno whats wrong here...

**Comment by Prototik** [comment]
For hide dialog invoke dismiss(), hide() is deprecated and already removed in dev version.
