### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by jouvigrouvi** [Prototik/HoloEverywhere#200]
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-mdpi/scrollbar_handle_holo_dark.9.png from drawable resource ID #0x0
 at android.content.res.Resources.loadDrawable(Resources.java:1714)
 at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
 at android.widget.AbsListView.<init>(AbsListView.java:630)
 at android.widget.ListView.<init>(ListView.java:230)
 at android.widget.ListView.<init>(ListView.java:226)
 ... 27 more
Caused by: java.io.FileNotFoundException: res/drawable-mdpi/scrollbar_handle_holo_dark.9.png
 at android.content.res.AssetManager.openNonAssetNative(Native Method)
 at android.content.res.AssetManager.openNonAsset(AssetManager.java:405)
 at android.content.res.Resources.loadDrawable(Resources.java:1706)

**Comment by Prototik** [comment]
Where? Which Android version? Phone model?

**Comment by jouvigrouvi** [comment]
I dont have data about phone model and android version only that its mdpi and what file is missing.

**Comment by Prototik** [comment]
```
[prok@prok-pc HE]$ ls -lh library/res/drawable-mdpi | grep scrollbar
-rw-rw-r-- 1 prok users  191 окт.  11 15:54 scrollbar_handle_holo_dark.9.png
-rw-rw-r-- 1 prok users  194 окт.  11 15:54 scrollbar_handle_holo_light.9.png
```

```
[prok@prok-pc HE]$ cd library/res/drawable-mdpi
[prok@prok-pc drawable-mdpi]$ md5sum `ls | grep scrollbar`
cf1c798e73a93c0176f96d9692980bee  scrollbar_handle_holo_dark.9.png
03054460b99a94ce93393b7a60d375c2  scrollbar_handle_holo_light.9.png
[prok@prok-pc drawable-mdpi]$ cd ~/android-sdk/platforms/android-16/data/res/drawable-mdpi
[prok@prok-pc drawable-mdpi]$ md5sum `ls | grep scrollbar`
...
cf1c798e73a93c0176f96d9692980bee  scrollbar_handle_holo_dark.9.png
03054460b99a94ce93393b7a60d375c2  scrollbar_handle_holo_light.9.png
...
```

**Comment by dougkeen** [comment]
Same stack trace is being reported by some of my users.  I know one of them is on a Samsung Galaxy S, which is likely on Android 2.2 or 2.3 (and uses the TouchWiz interface).

**Comment by dasony** [comment]
I get this report too.

Caused by: java.io.FileNotFoundException: res/drawable-hdpi/scrollbar_handle_holo_dark.9.png
        at android.content.res.AssetManager.openNonAssetNative(Native Method)
        at android.content.res.AssetManager.openNonAsset(AssetManager.java:405)
        at android.content.res.Resources.loadDrawable(Resources.java:1706)
        ... 37 more
android.content.res.Resources$NotFoundException: File res/drawable-hdpi/scrollbar_handle_holo_dark.9.png from drawable resource ID #0x0
        at android.content.res.Resources.loadDrawable(Resources.java:1714)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
        at android.widget.AbsListView.<init>(AbsListView.java:630)
        at android.widget.ListView.<init>(ListView.java:230)
        at android.widget.ListView.<init>(ListView.java:226)
        at com.WazaBe.HoloEverywhere.widget.ListView.<init>(SourceFile:120)

The device info is Samsung SGH-T959V / TMOUS / Android 2.2.1.

**Comment by dougkeen** [comment]
Turns out the error report I received is from the same device model:

Model number: sgh-t959v
Firmware version: 2.2.1
Kernel version: 2.6.32.9
Build: froyo-vuvkd1

**Comment by dougkeen** [comment]
I've also confirmed that the files being reported as missing are, in fact, inside the apk I released to the Play market (and in the correct directory).

**Comment by dougkeen** [comment]
Was this actually fixed or just closed?

**Comment by Prototik** [comment]
I don't have device for reproduce this bug. If you can fix it - send pull request.

**Comment by ChrisDavis8** [comment]
I have a very similar issue with a different resource file, did you find a workaround in the end?
