### ISSUE TITLE
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by Zeliret** [Prototik/HoloEverywhere#210]
``` java
ERROR/AndroidRuntime(5223): FATAL EXCEPTION: main
        java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1314)
        at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1325)
        at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:548)
        at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:532)
        at org.holoeverywhere.app.DialogFragment.show(DialogFragment.java:340)
        at org.holoeverywhere.app.DialogFragment.show(DialogFragment.java:317)
        at org.holoeverywhere.app.DialogFragment.show(DialogFragment.java:296)
        at org.holoeverywhere.app.DialogFragment.show(DialogFragment.java:291)
        at mega.onicon.activity.MainActivity.showChooseAccountDialog(MainActivity.java:208)
        at mega.onicon.activity.MainActivity.initSession(MainActivity.java:154)
        at mega.onicon.activity.MainActivity.access$700(MainActivity.java:40)
        at mega.onicon.activity.MainActivity$4.run(MainActivity.java:358)
        at android.accounts.AccountManager$10.run(AccountManager.java:1138)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:3687)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
        at dalvik.system.NativeStart.main(Native Method)
```

I show dialog, then in onClick handler I dismiss dialog and open a new activity. When I close that activity, I show dialog again (new instance and show() method). After that I have IllegalStateException exception.

Can u help me?

**Comment by 4nd3250n** [comment]
Could you provide a snippet of your code. Or even better a minimum working code that exhibits this behavior?

**Comment by Zeliret** [comment]
Dialog:

``` java
public static class AccountDialog extends DialogFragment
            implements DialogInterface.OnClickListener, DialogInterface.OnKeyListener {
        private Account[] accounts;

        static AccountDialog newInstance(final Account[] accounts) {
            final AccountDialog dialog = new AccountDialog();

            Bundle args = new Bundle();
            args.putParcelableArray("accounts", accounts);
            dialog.setArguments(args);

            return dialog;
        }

        public AccountDialog() {}

        @Override
        public Dialog onCreateDialog(Bundle savedInstanceState) {
            super.onCreateDialog(savedInstanceState);

            accounts = (Account[]) getArguments().getParcelableArray("accounts");
            if (null == accounts && null != savedInstanceState) {
                accounts = (Account[]) savedInstanceState.getParcelableArray("accounts");
            }

            final Activity activity = getSupportActivity();
            final AccountAdapter adapter = new AccountAdapter(activity, accounts);

            return new AlertDialog.Builder(activity)
                    .setTitle(R.string.titleChooseAccountToLogin)
                    .setSingleChoiceItems(adapter, -1, AccountDialog.this)
                    .setCancelable(false)
                    .setOnKeyListener(AccountDialog.this)
                    .setNeutralButton(R.string.addAccount, AccountDialog.this)
                    .create();
        }

        @Override
        public void onSaveInstanceState(Bundle outState) {
            super.onSaveInstanceState(outState);

            outState.putParcelableArray("accounts", accounts);
        }

        @Override
        public void onClick(DialogInterface dialogInterface, int i) {
            final MainActivity activity = ((MainActivity) getSupportActivity());
            if (i == DialogInterface.BUTTON_NEUTRAL) {
                activity.addAccount();
            } else {
                activity.beginAuthentication(accounts[i]);
            }

            this.dismiss();
        }

        @Override
        public boolean onKey(DialogInterface dialogInterface, int i, KeyEvent keyEvent) {
            getSupportActivity().finish();

            return false;
        }
    }
```

Using: 

``` java
private void showChooseAccountDialog() {
        final AccountDialog dialog = AccountDialog.newInstance(accountManager.getAccountsByType(accountType));
        dialog.show(this);
    }
```

addAccount opens AuthenticatorActivity. After then I press "back":

``` java
private void addAccount() {
        accountManager.addAccount(accountType, null, null, null, this,
                new AccountManagerCallback<Bundle>() {
                    @Override
                    public void run(AccountManagerFuture<Bundle> bundleAccountManagerFuture) {
                        try {
                            final Bundle result = bundleAccountManagerFuture.getResult();
                            final Account account = new Account(
                                    result.getString(AccountManager.KEY_ACCOUNT_NAME),
                                    result.getString(AccountManager.KEY_ACCOUNT_TYPE));
                            beginAuthentication(account);
                        } catch (OperationCanceledException e) {
                            initSession();
                        } catch (IOException e) {
                            e.printStackTrace();
                        } catch (AuthenticatorException e) {
                            e.printStackTrace();
                        }
                    }
                }, null);
    }
```

InitSession opens AccountDialog again via showChooseAccountDialog().

Exception throws instead of opening dialog.

**Comment by Zeliret** [comment]
http://code.google.com/p/android/issues/detail?id=17787
http://stackoverflow.com/questions/10114324/show-dialogfragment-from-onactivityresult

Its a known bug. In my project I will be using workaround solution until bug is fixed.

**Comment by AndroidDeveloperLB** [comment]
@Zeliret How did you solve (or found a workaround) for this? I don't even use the support library's fragment for this, yet I get an exception when trying to show a DialogFragment on "onStart" .
