### ISSUE TITLE
DetailActivity with fragments crashing with NullPointerException

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#228]
Hello! My detailactivity inflates inflates three fragments which are shown within tabs. However, as soon as I enter the detail activity, the app crashes due to a nullpointerexception without any reference to where in my code it is happening.

Here is my ItemDetailActivity

```
package com.example.sampleapp;

import org.holoeverywhere.app.Activity;
import org.holoeverywhere.app.Fragment;

import com.actionbarsherlock.app.ActionBar;
import com.actionbarsherlock.app.ActionBar.Tab;
import com.actionbarsherlock.view.MenuItem;

import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.FragmentTransaction;
import android.support.v4.app.NavUtils;

/**
 * An activity representing a single Item detail screen. This activity is only
 * used on handset devices. On tablet-size devices, item details are presented
 * side-by-side with a list of items in a {@link ItemListActivity}.
 * <p>
 * This activity is mostly just a 'shell' activity containing nothing more than
 * a {@link ItemDetailFragment}.
 */
public class ItemDetailActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_item_detail);
        // Show the Up button in the action bar.
        ActionBar actionBar = getSupportActionBar();
        actionBar.setDisplayHomeAsUpEnabled(true);
        actionBar.setNavigationMode(ActionBar.NAVIGATION_MODE_TABS);

        ActionBar.Tab assignTab = actionBar.newTab().setText(
            "Assignments");
        ActionBar.Tab schedTab = actionBar.newTab().setText("Schedule");
        ActionBar.Tab contactTab = actionBar.newTab()
            .setText("Contact");

        Fragment assignFragment = new Assignments();
        Fragment schedFragment = new Schedule();
        Fragment contactFragment = new Contact();

        assignTab.setTabListener(new MyTabsListener(assignFragment));
        schedTab.setTabListener(new MyTabsListener(schedFragment));
        contactTab.setTabListener(new MyTabsListener(contactFragment));

        actionBar.addTab(assignTab);
        actionBar.addTab(schedTab);
        actionBar.addTab(contactTab);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
        case android.R.id.home:
            // This ID represents the Home or Up button. In the case of this
            // activity, the Up button is shown. Use NavUtils to allow users
            // to navigate up one level in the application structure. For
            // more details, see the Navigation pattern on Android Design:
            //
            // http://developer.android.com/design/patterns/navigation.html#up-vs-back
            //
            NavUtils.navigateUpTo(this,
                new Intent(this, ItemListActivity.class));
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

    class MyTabsListener implements ActionBar.TabListener {
        public Fragment fragment;

        public MyTabsListener(Fragment fragment) {
            this.fragment = fragment;
        }

        @Override
        public void onTabSelected(Tab tab, FragmentTransaction ft) {
            // TODO Auto-generated method stub
            ft.replace(R.id.item_detail_container, fragment);
        }

        @Override
        public void onTabUnselected(Tab tab, FragmentTransaction ft) {
            // TODO Auto-generated method stub
            ft.remove(fragment);
        }

        @Override
        public void onTabReselected(Tab tab, FragmentTransaction ft) {
            // TODO Auto-generated method stub

        }
    }
}
```

And here is my logcat

```
12-15 10:34:31.433: E/AndroidRuntime(385): FATAL EXCEPTION: main
12-15 10:34:31.433: E/AndroidRuntime(385): java.lang.NullPointerException
12-15 10:34:31.433: E/AndroidRuntime(385):  at org.holoeverywhere.ArrayAdapter.createViewFromResource(ArrayAdapter.java:204)
12-15 10:34:31.433: E/AndroidRuntime(385):  at org.holoeverywhere.ArrayAdapter.getView(ArrayAdapter.java:250)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.AbsListView.obtainView(AbsListView.java:1315)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.ListView.measureHeightOfChildren(ListView.java:1198)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.ListView.onMeasure(ListView.java:1109)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.View.measure(View.java:8171)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
12-15 10:34:31.433: E/AndroidRuntime(385):  at org.holoeverywhere.widget.LinearLayout.measureChildWithMargins(LinearLayout.java:233)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1012)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.LinearLayout.measureVertical(LinearLayout.java:381)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.LinearLayout.onMeasure(LinearLayout.java:304)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.View.measure(View.java:8171)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.View.measure(View.java:8171)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.View.measure(View.java:8171)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.View.measure(View.java:8171)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.View.measure(View.java:8171)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.View.measure(View.java:8171)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.LinearLayout.measureVertical(LinearLayout.java:526)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.LinearLayout.onMeasure(LinearLayout.java:304)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.View.measure(View.java:8171)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.View.measure(View.java:8171)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.View.measure(View.java:8171)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.ViewRoot.performTraversals(ViewRoot.java:801)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.view.ViewRoot.handleMessage(ViewRoot.java:1727)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.os.Handler.dispatchMessage(Handler.java:99)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.os.Looper.loop(Looper.java:123)
12-15 10:34:31.433: E/AndroidRuntime(385):  at android.app.ActivityThread.main(ActivityThread.java:4627)
12-15 10:34:31.433: E/AndroidRuntime(385):  at java.lang.reflect.Method.invokeNative(Native Method)
12-15 10:34:31.433: E/AndroidRuntime(385):  at java.lang.reflect.Method.invoke(Method.java:521)
12-15 10:34:31.433: E/AndroidRuntime(385):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
12-15 10:34:31.433: E/AndroidRuntime(385):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
12-15 10:34:31.433: E/AndroidRuntime(385):  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Prototik** [comment]
In Assignments Fragment you use ListView with adapter which created with null context reference or incorrect id. Show fragment code.

**Comment by ghost** [comment]
Here's one of my fragment's code.

```
package com.example.sampleapp;

import org.holoeverywhere.ArrayAdapter;
import org.holoeverywhere.LayoutInflater;
import org.holoeverywhere.app.Fragment;
import org.holoeverywhere.widget.ListView;

import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;

public class Assignments extends Fragment {
    View view;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
        Bundle savedInstanceState) {
        // TODO Auto-generated method stub
        view = inflater.inflate(R.layout.assignfrag, container, false);
        return view;
    }

    @Override
    public void onViewCreated(View view) {
        // TODO Auto-generated method stub
        super.onViewCreated(view);
        ListView listView = (ListView)  getView().findViewById(R.id.assignlist);
        String[] values = new String[] { "Android", "iPhone", "WindowsMobile",
      "Blackberry", "WebOS", "Ubuntu", "Windows7", "Max OS X",
      "Linux", "OS/2" };

        // First parameter - Context
        // Second parameter - Layout for the row
        // Third parameter - ID of the TextView to which the data is written
        // Forth - the Array of data
        ArrayAdapter<String> adapter = new ArrayAdapter<String>(getActivity(),
      org.holoeverywhere.R.layout.simple_list_item_multiple_choice, org.holoeverywhere.R.id.text1, values);

        // Assign adapter to ListView
        listView.setAdapter(adapter);

    }

}
```

**Comment by ghost** [comment]
nvm fixed it. they shouldn't be org.holoeverywhere.R. they should be android.R.

**Comment by Prototik** [comment]
android.R.id.text1
