### ISSUE TITLE
Proguard obsfucation missing classes

### ISSUE THREAD

**Issue by duanemalcolm** [Prototik/HoloEverywhere#231]
I have an app that uses both HoloEverywhere and ActionBarSherlock. I create a release of the app using Proguard obsfucation which causes the app to fail due to missing classes when AlertDialogs appear. If I build a release with obsfucation turned off using the "-dontobsfucate" tag, the app works fine. I've worked on this issue for a day or so and cannot find a solution.

I'm hoping to launch in a couple of days and this is one issue holding me up. I would really appreciate some help. My alternative is to release without obsfucation :-(

Thanks for your help.

project.properties

```
target=android-17
proguard.config=proguard.cfg
android.library=false
android.library.reference.1=../ActionBarSherlock
android.library.reference.2=../HoloEveryWhere
```

proguard.cfg:

```
-optimizationpasses 1
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontpreverify
-verbose
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*

-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class com.android.vending.licensing.ILicensingService

-keep class com.google.ads.**  { *; }
-dontwarn com.google.ads.**

# ActionBarSherlock
-keep class android.support.v4.app.** { *; }
-keep interface android.support.v4.app.** { *; }
-keep class com.actionbarsherlock.** { *; }
-keep interface com.actionbarsherlock.** { *; }
-keepattributes *Annotation*

# HoloEverywhere
-keep,allowoptimization class org.holoeverywhere.** { 
    public *;
    protected *;
}
-keep,allowoptimization interface org.holoeverywhere.** { *; }

# Original
-keepclasseswithmembernames class * {
    native <methods>;
}

-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet);
}

-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet, int);
}

-keepclassmembers class * extends android.app.Activity {
   public void *(android.view.View);
}

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
```

Output from proguard:

```
-obfuscate:
   [delete] Deleting: /home/malcolm/enzure/android/weatherbomb/bin/proguard/original.jar
   [delete] Deleting: /home/malcolm/enzure/android/weatherbomb/bin/proguard/obfuscated.jar
      [jar] Building jar: /home/malcolm/enzure/android/weatherbomb/bin/proguard/original.jar
 [proguard] ProGuard, version 4.7
 [proguard] Reading input...
 [proguard] Reading program jar [/home/malcolm/enzure/android/weatherbomb/bin/proguard/original.jar]
 [proguard] Reading program jar [/home/malcolm/enzure/android/HoloEveryWhere/bin/classes.jar]
 [proguard] Reading program jar [/home/malcolm/enzure/android/ActionBarSherlock/bin/classes.jar]
 [proguard] Reading program jar [/home/malcolm/enzure/android/weatherbomb/libs/GoogleAdMobAdsSdk-6.2.1.jar]
 [proguard] Reading program jar [/home/malcolm/enzure/android/weatherbomb/libs/GeocoderPlus.jar]
 [proguard] Reading program jar [/home/malcolm/enzure/android/ActionBarSherlock/libs/android-support-v4.jar]
 [proguard] Reading library jar [/opt/android-sdks/platforms/android-17/android.jar]
 [proguard] Initializing...
 [proguard] Note: com.google.ads.AdRequest: can't find dynamically referenced class com.google.analytics.tracking.android.AdMobInfo
 [proguard] Note: the configuration refers to the unknown class 'com.android.vending.licensing.ILicensingService'
 [proguard] Note: the configuration refers to the unknown class 'Internal.DialogTitle'
 [proguard]       Maybe you meant the fully qualified name 'org.holoeverywhere.internal.DialogTitle'?
 [proguard] Note: the configuration refers to the unknown class 'Internal.ExpandedMenuView'
 [proguard]       Maybe you meant the fully qualified name 'com.actionbarsherlock.internal.view.menu.ExpandedMenuView'?
 [proguard] Note: the configuration refers to the unknown class 'Internal.NumberPickerEditText'
 [proguard]       Maybe you meant the fully qualified name 'org.holoeverywhere.internal.NumberPickerEditText'?
 [proguard] Note: the configuration refers to the unknown class 'Internal.RecycleListView'
 [proguard] Note: the configuration keeps the entry point 'android.support.v4.app.LoaderManager$LoaderCallbacks { void onLoadFinished(android.support.v4.content.Loader,java.lang.Object); }', but not the descriptor class 'android.support.v4.content.Loader'
 [proguard] Note: the configuration keeps the entry point 'android.support.v4.app.LoaderManager$LoaderCallbacks { void onLoaderReset(android.support.v4.content.Loader); }', but not the descriptor class 'android.support.v4.content.Loader'
 [proguard] Note: the configuration keeps the entry point 'android.support.v4.app.LoaderManagerImpl$LoaderInfo { void onLoadComplete(android.support.v4.content.Loader,java.lang.Object); }', but not the descriptor class 'android.support.v4.content.Loader'
 [proguard] Note: the configuration keeps the entry point 'android.support.v4.app.LoaderManagerImpl$LoaderInfo { void callOnLoadFinished(android.support.v4.content.Loader,java.lang.Object); }', but not the descriptor class 'android.support.v4.content.Loader'
 [proguard] Note: the configuration keeps the entry point 'android.support.v4.view.ViewCompat { void onInitializeAccessibilityNodeInfo(android.view.View,android.support.v4.view.accessibility.AccessibilityNodeInfoCompat); }', but not the descriptor class 'android.support.v4.view.accessibility.AccessibilityNodeInfoCompat'
 [proguard] Note: the configuration keeps the entry point 'android.support.v4.view.ViewCompat { void setAccessibilityDelegate(android.view.View,android.support.v4.view.AccessibilityDelegateCompat); }', but not the descriptor class 'android.support.v4.view.AccessibilityDelegateCompat'
 [proguard] Note: the configuration keeps the entry point 'com.actionbarsherlock.widget.SearchView { void setSuggestionsAdapter(android.support.v4.widget.CursorAdapter); }', but not the descriptor class 'android.support.v4.widget.CursorAdapter'
 [proguard] Note: there were 5 references to unknown classes.
 [proguard]       You should check your configuration for typos.
 [proguard] Note: there were 7 unkept descriptor classes in kept class members.
 [proguard]       You should consider explicitly keeping the mentioned classes
 [proguard]       (using '-keep').
 [proguard] Note: there were 1 unresolved dynamic references to classes or interfaces.
 [proguard]       You should check if you need to specify additional program jars.
 [proguard] Ignoring unused library classes...
 [proguard]   Original number of library classes: 3259
 [proguard]   Final number of library classes:    874
 [proguard] Printing kept classes, fields, and methods...
 [proguard] Shrinking...
 [proguard] Printing usage to [/home/malcolm/enzure/android/weatherbomb/bin/proguard/usage.txt]...
 [proguard] Removing unused program classes and class elements...
 [proguard]   Original number of program classes: 1127
 [proguard]   Final number of program classes:    1000
 [proguard] Optimizing...
 [proguard]   Number of finalized classes:                 263
 [proguard]   Number of vertically merged classes:         0   (disabled)
 [proguard]   Number of horizontally merged classes:       0   (disabled)
 [proguard]   Number of removed write-only fields:         0   (disabled)
 [proguard]   Number of privatized fields:                 0   (disabled)
 [proguard]   Number of inlined constant fields:           0   (disabled)
 [proguard]   Number of privatized methods:                858
 [proguard]   Number of staticized methods:                95
 [proguard]   Number of finalized methods:                 2125
 [proguard]   Number of removed method parameters:         67
 [proguard]   Number of inlined constant parameters:       43
 [proguard]   Number of inlined constant return values:    14
 [proguard]   Number of inlined short method calls:        167
 [proguard]   Number of inlined unique method calls:       439
 [proguard]   Number of inlined tail recursion calls:      2
 [proguard]   Number of merged code blocks:                22
 [proguard]   Number of variable peephole optimizations:   2728
 [proguard]   Number of arithmetic peephole optimizations: 0   (disabled)
 [proguard]   Number of cast peephole optimizations:       0
 [proguard]   Number of field peephole optimizations:      6
 [proguard]   Number of branch peephole optimizations:     785
 [proguard]   Number of string peephole optimizations:     273
 [proguard]   Number of simplified instructions:           330
 [proguard]   Number of removed instructions:              1009
 [proguard]   Number of removed local variables:           103
 [proguard]   Number of removed exception blocks:          111
 [proguard]   Number of optimized local variable frames:   1336
 [proguard] Shrinking...
 [proguard] Removing unused program classes and class elements...
 [proguard]   Original number of program classes: 1000
 [proguard]   Final number of program classes:    982
 [proguard] Obfuscating...
 [proguard] Printing mapping to [/home/malcolm/enzure/android/weatherbomb/bin/proguard/mapping.txt]...
 [proguard] Writing output...
 [proguard] Preparing output jar [/home/malcolm/enzure/android/weatherbomb/bin/proguard/obfuscated.jar]
 [proguard]   Copying resources from program jar [/home/malcolm/enzure/android/weatherbomb/bin/proguard/original.jar]
 [proguard]   Copying resources from program jar [/home/malcolm/enzure/android/HoloEveryWhere/bin/classes.jar]
 [proguard] Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF])
 [proguard]   Copying resources from program jar [/home/malcolm/enzure/android/ActionBarSherlock/bin/classes.jar]
 [proguard] Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [classes.jar:META-INF/MANIFEST.MF])
 [proguard]   Copying resources from program jar [/home/malcolm/enzure/android/weatherbomb/libs/GoogleAdMobAdsSdk-6.2.1.jar]
 [proguard] Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [GoogleAdMobAdsSdk-6.2.1.jar:META-INF/MANIFEST.MF])
 [proguard]   Copying resources from program jar [/home/malcolm/enzure/android/weatherbomb/libs/GeocoderPlus.jar]
 [proguard] Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [GeocoderPlus.jar:META-INF/MANIFEST.MF])
 [proguard]   Copying resources from program jar [/home/malcolm/enzure/android/ActionBarSherlock/libs/android-support-v4.jar]
 [proguard] Warning: can't write resource [META-INF/MANIFEST.MF] (Duplicate zip entry [android-support-v4.jar:META-INF/MANIFEST.MF])
 [proguard] Printing classes to [/home/malcolm/enzure/android/weatherbomb/bin/proguard/dump.txt]...

-dex:
      [dex] input: /home/malcolm/enzure/android/weatherbomb/bin/proguard/obfuscated.jar
      [dex] Found modified input file
      [dex] Converting compiled files and external libraries into /home/malcolm/enzure/android/weatherbomb/bin/classes.dex...

-crunch:
   [crunch] Crunching PNG Files in source dir: /home/malcolm/enzure/android/weatherbomb/res
   [crunch] To destination dir: /home/malcolm/enzure/android/weatherbomb/bin/res
   [crunch] Crunched 0 PNG files to update cache

-package-resources:
     [aapt] No changed resources or assets. WeatherBomb.ap_ remains untouched

-package:
[apkbuilder] Found modified input file
[apkbuilder] Creating WeatherBomb-release-unsigned.apk for release...

-post-package:

-release-prompt-for-password:

-release-nosign:

-release-sign:
     [echo] Signing final apk...
 [zipalign] Running zip align on final apk...
     [echo] Release Package: /home/malcolm/enzure/android/weatherbomb/bin/WeatherBomb-release.apk
[propertyfile] Updating property file: /home/malcolm/enzure/android/weatherbomb/bin/build.prop
[propertyfile] Updating property file: /home/malcolm/enzure/android/weatherbomb/bin/build.prop
[propertyfile] Updating property file: /home/malcolm/enzure/android/weatherbomb/bin/build.prop
[propertyfile] Updating property file: /home/malcolm/enzure/android/weatherbomb/bin/build.prop
...
```

Crash report:

```
12-19 16:19:07.047: W/System.err(19729): java.lang.ClassNotFoundException: Could not find class: Internal.RecycleListView
12-19 16:19:07.047: W/System.err(19729):    at org.holoeverywhere.LayoutInflater.onCreateView(Unknown Source)
12-19 16:19:07.047: W/System.err(19729):    at org.holoeverywhere.LayoutInflater.onCreateView(Unknown Source)
12-19 16:19:07.047: W/System.err(19729):    at org.holoeverywhere.LayoutInflater$HoloFactoryMerger.onCreateView(Unknown Source)
12-19 16:19:07.047: W/System.err(19729):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:676)
12-19 16:19:07.047: W/System.err(19729):    at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
12-19 16:19:07.047: W/System.err(19729):    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
12-19 16:19:07.047: W/System.err(19729):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
12-19 16:19:07.047: W/System.err(19729):    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
12-19 16:19:07.047: W/System.err(19729):    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
12-19 16:19:07.047: W/System.err(19729):    at org.holoeverywhere.internal.AlertController$AlertParams.apply(Unknown Source)
12-19 16:19:07.047: W/System.err(19729):    at org.holoeverywhere.app.AlertDialog$Builder.create(Unknown Source)
12-19 16:19:07.047: W/System.err(19729):    at org.holoeverywhere.preference.DialogPreference.a(Unknown Source)
12-19 16:19:07.047: W/System.err(19729):    at org.holoeverywhere.preference.DialogPreference.onClick(Unknown Source)
12-19 16:19:07.055: W/System.err(19729):    at org.holoeverywhere.preference.Preference.a(Unknown Source)
12-19 16:19:07.055: W/System.err(19729):    at org.holoeverywhere.preference.PreferenceScreen.onItemClick(Unknown Source)
12-19 16:19:07.055: W/System.err(19729):    at android.widget.AdapterView.performItemClick(AdapterView.java:298)
12-19 16:19:07.055: W/System.err(19729):    at android.widget.AbsListView.performItemClick(AbsListView.java:1086)
12-19 16:19:07.055: W/System.err(19729):    at org.holoeverywhere.widget.ListView.performItemClick(Unknown Source)
12-19 16:19:07.055: W/System.err(19729):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:2855)
12-19 16:19:07.055: W/System.err(19729):    at android.widget.AbsListView$1.run(AbsListView.java:3529)
12-19 16:19:07.055: W/System.err(19729):    at android.os.Handler.handleCallback(Handler.java:615)
12-19 16:19:07.055: W/System.err(19729):    at android.os.Handler.dispatchMessage(Handler.java:92)
12-19 16:19:07.062: W/System.err(19729):    at android.os.Looper.loop(Looper.java:137)
12-19 16:19:07.062: W/System.err(19729):    at android.app.ActivityThread.main(ActivityThread.java:4745)
12-19 16:19:07.062: W/System.err(19729):    at java.lang.reflect.Method.invokeNative(Native Method)
12-19 16:19:07.062: W/System.err(19729):    at java.lang.reflect.Method.invoke(Method.java:511)
12-19 16:19:07.062: W/System.err(19729):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
12-19 16:19:07.062: W/System.err(19729):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
12-19 16:19:07.062: W/System.err(19729):    at dalvik.system.NativeStart.main(Native Method)
12-19 16:19:07.070: D/AndroidRuntime(19729): Shutting down VM
12-19 16:19:07.070: W/dalvikvm(19729): threadid=1: thread exiting with uncaught exception (group=0x4196d300)
12-19 16:19:07.078: E/AndroidRuntime(19729): FATAL EXCEPTION: main
12-19 16:19:07.078: E/AndroidRuntime(19729): android.view.InflateException: Binary XML file line #2: Error inflating class Internal.RecycleListView
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:698)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at org.holoeverywhere.LayoutInflater.inflate(Unknown Source)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at org.holoeverywhere.internal.AlertController$AlertParams.apply(Unknown Source)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at org.holoeverywhere.app.AlertDialog$Builder.create(Unknown Source)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at org.holoeverywhere.preference.DialogPreference.a(Unknown Source)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at org.holoeverywhere.preference.DialogPreference.onClick(Unknown Source)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at org.holoeverywhere.preference.Preference.a(Unknown Source)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at org.holoeverywhere.preference.PreferenceScreen.onItemClick(Unknown Source)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.widget.AdapterView.performItemClick(AdapterView.java:298)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.widget.AbsListView.performItemClick(AbsListView.java:1086)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at org.holoeverywhere.widget.ListView.performItemClick(Unknown Source)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:2855)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.widget.AbsListView$1.run(AbsListView.java:3529)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.os.Handler.handleCallback(Handler.java:615)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.os.Handler.dispatchMessage(Handler.java:92)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.os.Looper.loop(Looper.java:137)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.app.ActivityThread.main(ActivityThread.java:4745)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at java.lang.reflect.Method.invokeNative(Native Method)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at java.lang.reflect.Method.invoke(Method.java:511)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at dalvik.system.NativeStart.main(Native Method)
12-19 16:19:07.078: E/AndroidRuntime(19729): Caused by: java.lang.ClassNotFoundException: Internal.RecycleListView
12-19 16:19:07.078: E/AndroidRuntime(19729):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.view.LayoutInflater.createView(LayoutInflater.java:552)
12-19 16:19:07.078: E/AndroidRuntime(19729):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
12-19 16:19:07.078: E/AndroidRuntime(19729):    ... 25 more
12-19 16:19:07.086: W/ActivityManager(306):   Force finishing activity com.enzuredigital.weatherbomb/.SettingsActivity
```

**Comment by Prototik** [comment]
Put into static code block of your Application object next code:

``` java
LayoutInflater.remapHard("Internal.RecycleListView", org.holoeverywhere.internal.AlertController.RecycleListView.class);
```

Or just add rules to disable renaming of classes that extend a View.

**Comment by duanemalcolm** [comment]
Thanks for that.

**Comment by alexfu** [comment]
I'm currently getting this problem. I added the following to my proguard.cfg...

```
-keep public class * extends android.view.View
```

but I'm still getting this error.

**Comment by agarwlGaurav** [comment]
@alexfu What error you are getting?

**Comment by alexfu** [comment]
@CodingCrow the same exact error as the original poster.

**Comment by ghost** [comment]
I have tried:
-keep public class \* extends android.view.View

I have tried putting the following code in my Application class:
    protected static void keep() {
        LayoutInflater.remapHard("Internal.RecycleListView", org.holoeverywhere.internal.AlertController.RecycleListView.class.toString());
    }

Tried them both.

Tried  
-keep public class \* extends com.android.internal.app.

None worked.  Keep getting the same error as the poster.

I have also tried the latest proguard statements found in the demo project, including:
-keep public class \* extends android.view.View {
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
    public void set_(...);
    public void get_(...);
}

Any one get this to work?

**Comment by Prototik** [comment]
@Appstervan 
`LayoutInflater.remapHard("Internal.RecycleListView", org.holoeverywhere.internal.AlertController.RecycleListView.class.getName());` maybe?

And 1.4.1 don't have this issue, you sure?

**Comment by ghost** [comment]
I tried with class.GetName() earlier without success.

I hadn't tried upgrading.  I was trying to avoid that as we are in final stages of testing.  However, when I tried, I received build errors and was unable to build the HoloEverwhere library with the following errors: 

Plugin execution not covered by lifecycle configuration: com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.4.1:generate-sources (execution: default-generate-sources, phase: generate-sources)    pom.xml /HoloEverywhere line 58 Maven Project Build Lifecycle Mapping Problem

Project 'HoloEverywhere' is missing required source folder: 'test'  HoloEverywhere      Build path  Build Path Problem

So instead of checking out 1.4.1, I left it on the Master and receive this error:
Project build error: Non-resolvable parent POM: Failure to find org.holoeverywhere:parent:pom:1.4.2 in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM  pom.xml /HoloEverywhere line 9  Maven pom Loading Problem

**Comment by ghost** [comment]
I got this to work with 1.4.1.  I had to delete HoloEverywhere/test from the project.  However, I still have a "red" x on the HoloEverywhere project as it is still has the following problem:
Plugin execution not covered by lifecycle configuration: com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.4.1:generate-sources (execution: default-generate-sources, phase: generate-sources) pom.xml /HoloEverywhere line 58 Maven Project Build Lifecycle Mapping Problem

However, the code generates even though it looks like there is a severe error.

**Comment by ghost** [comment]
I had to use the latest master rather then the 1.4.1 branch.  As the 1.4.1 branch does not have the fix for RingTone in it.  While the master does.  As well the master project has an error:
Project build error: Non-resolvable parent POM: Failure to find org.holoeverywhere:parent:pom:1.4.2 in http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM pom.xml /HoloEverywhere line 9 Maven pom Loading Problem

Which doesn't prevent a build.  So, everything works now...except for a strange X.  And hopefully the master is a stable version.
