### ISSUE TITLE
java.lang.NullPointerException org.holoeverywhere.a.e.e(Unknown Source)

### ISSUE THREAD

**Issue by bondjpf** [Prototik/HoloEverywhere#239]
I'm getting this error from users and I don't know where to look

Stack trace:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.monzonito.xxxx/com.monzonito.xxxx.Home}:
java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1970)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1995)
at android.app.ActivityThread.access$600(ActivityThread.java:128)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1161)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4514)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:980)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.holoeverywhere.a.e.e(Unknown Source)
at org.holoeverywhere.preference.v.a(Unknown Source)
at android.support.v4.app.ai.a(Unknown Source)
at com.monzonito.xxxx.Home.onCreate(Unknown Source)
at android.app.Activity.performCreate(Activity.java:4470)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1053)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1934)
... 11 more

What can be worng?

**Comment by 4nd3250n** [comment]
Well... I guess there is a null pointer where it shouldn't be.
What is yourcom.monzonito.xxxx.Home.onCreate() method? Go through it with a debugger.

**Comment by Prototik** [comment]
Yea, and make detrace of logcat.

**Comment by bondjpf** [comment]
It runs fine on my device and emulator.

The only code I've changed was the themes section because I've upgraded from 1.3 to 1.4. Here's how I have that section of code:

setForceThemeApply(true);

SP = Home.this.getSharedPreferences(SHARED_PREFS_NAME, 0);
this.SP.registerOnSharedPreferenceChangeListener(this);
if (SP.getString("theme_list_preference", "AppThemeLight").equals(
                "AppThemeLight")) {
    ThemeManager.restartWithTheme(this, ThemeManager.LIGHT);

```
} else if (SP.getString("theme_list_preference",
            "AppThemeLightDarkActionBar").equals(
            "AppThemeLightDarkActionBar")) {

    ThemeManager.restartWithTheme(this, ThemeManager.MIXED);

} else if (SP.getString("theme_list_preference", "AppThemeDark")
            .equals("AppThemeDark")) {

    ThemeManager.restartWithTheme(this, ThemeManager.DARK);
```

}

**Comment by 4nd3250n** [comment]
Which line causes the exception?

**Comment by Prototik** [comment]
Make detrace, please. Just so guess where the error in your proguard configuration I do not.

**Comment by bondjpf** [comment]
Will try to do it. Now that you mention proguard I did implement it prior to upgrading from v.1.3 to 1.4

**Comment by Prototik** [comment]
I close this issue?
