### ISSUE TITLE
PreferenceActivity headers crash using Holo.Theme.Light.DarkActionBar

### ISSUE THREAD

**Issue by mattprecious** [Prototik/HoloEverywhere#242]
I have no idea why this happens... it's really weird. I've taken a look through the HE code and I can't figure it out.

My app uses `preference-headers` and it crashes when I use the `Holo.Theme.Light.DarkActionBar` theme and works perfectly fine on the other themes.

```
12-24 21:18:16.451: E/AndroidRuntime(23533): FATAL EXCEPTION: main
12-24 21:18:16.451: E/AndroidRuntime(23533): android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.LayoutInflater.createView(LayoutInflater.java:613)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at org.holoeverywhere.LayoutInflater.tryCreateView(LayoutInflater.java:347)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:299)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:278)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:263)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at org.holoeverywhere.preference.PreferenceActivity$HeaderAdapter.getView(PreferenceActivity.java:182)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.AbsListView.obtainView(AbsListView.java:2159)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.ListView.onMeasure(ListView.java:1130)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.View.measure(View.java:15513)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4827)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at org.holoeverywhere.widget.LinearLayout.measureChildWithMargins(LinearLayout.java:233)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.View.measure(View.java:15513)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1034)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:590)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.View.measure(View.java:15513)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.View.measure(View.java:15513)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4827)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.View.measure(View.java:15513)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4827)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.View.measure(View.java:15513)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.View.measure(View.java:15513)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4827)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2176)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.View.measure(View.java:15513)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1874)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1089)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1265)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.Choreographer.doFrame(Choreographer.java:532)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.os.Handler.handleCallback(Handler.java:725)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.os.Handler.dispatchMessage(Handler.java:92)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.os.Looper.loop(Looper.java:137)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.app.ActivityThread.main(ActivityThread.java:5039)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at java.lang.reflect.Method.invokeNative(Native Method)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at java.lang.reflect.Method.invoke(Method.java:511)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at dalvik.system.NativeStart.main(Native Method)
12-24 21:18:16.451: E/AndroidRuntime(23533): Caused by: java.lang.reflect.InvocationTargetException
12-24 21:18:16.451: E/AndroidRuntime(23533):    at java.lang.reflect.Constructor.constructNative(Native Method)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
12-24 21:18:16.451: E/AndroidRuntime(23533):    at android.view.LayoutInflater.createView(LayoutInflater.java:5
```

The issue is on L5 of `layout/preference_header_item.xml`:

``` xml
android:background="?activatedBackgroundIndicator"
```

Removing that line causes the app to run properly. To get around this issue, I've copied this from your `styles.xml` file into my own theme and it works just fine:

``` xml
<item name="activatedBackgroundIndicator">@drawable/activated_background_holo</item>
```

**Comment by Prototik** [comment]
Fixed in 1.4.1
