### ISSUE TITLE
java.lang.ClassCastException: org.holoeverywhere.widget.LinearLayout

### ISSUE THREAD

**Issue by minioreo** [Prototik/HoloEverywhere#251]
java.lang.ClassCastException happend in demo

```
java.lang.ClassCastException: org.holoeverywhere.widget.LinearLayout                     
    at org.holoeverywhere.demo.DemoActivity$NavigationItem.getView(DemoActivity.java:114)  
    at org.holoeverywhere.demo.DemoActivity$NavigationAdapter.getView(DemoActivity.java:68)
    at org.holoeverywhere.widget.ListView$ListAdapterWrapper.getView(ListView.java:341)    
    at android.widget.AbsListView.obtainView(AbsListView.java:1409)                        
    at android.widget.ListView.makeAndAddView(ListView.java:1745)                          
    at android.widget.ListView.fillSpecific(ListView.java:1290)                            
    at android.widget.ListView.layoutChildren(ListView.java:1576)                          
    at android.widget.AbsListView.onLayout(AbsListView.java:1260)                          
    at android.view.View.layout(View.java:7175)                                            
    at android.widget.FrameLayout.onLayout(FrameLayout.java:338)                           
    at android.view.View.layout(View.java:7175)                                            
    at android.view.ViewRoot.performTraversals(ViewRoot.java:1140)                         
    at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)                             
    at android.os.Handler.dispatchMessage(Handler.java:99)                                 
    at android.os.Looper.loop(Looper.java:123)                                             
    at android.app.ActivityThread.main(ActivityThread.java:3683)                           
    at java.lang.reflect.Method.invokeNative(Native Method)                                
    at java.lang.reflect.Method.invoke(Method.java:507)                                    
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)     
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)                        
    at dalvik.system.NativeStart.main(Native Method)                                       
```

**Comment by 4nd3250n** [comment]
Source of ListView adapter?

**Comment by minioreo** [comment]
it happened in the holoeverywhere demo application
https://github.com/ChristopheVersieux/HoloEverywhere/blob/master/demo/src/org/holoeverywhere/demo/DemoActivity.java

**Comment by Prototik** [comment]
You have a compile mistakes. Master branch and my local version successful compiles and running. Into maven central you may download demo-1.4.1.apk.
