### ISSUE TITLE
setSlidingActionBarEnabled

### ISSUE THREAD

**Issue by CiTuX** [Prototik/HoloEverywhere#273]
No Issue, but a question:

In the SlidingMenu addon at [setSlidingActionBarEnabled(boolean b)](https://github.com/ChristopheVersieux/HoloEverywhere/blob/13b0d5eddd3ed54647ffef4b4d4cf74e2d0b6c43/slidingmenu/src/org/holoeverywhere/addon/SlidingMenu.java#L103) the helper call is commented out with a note  _Sliding with ActionBar temporary not working_.

When I enable the helper call, it seems to work (ActionBar is sliding).
What was the reason for disabling the function?

Thanks for your great work!

**Comment by Prototik** [comment]
Mmm...
I test it on 2.1, 2.3.7 and 4.1 - not working.

Or am I an idiot, or ... I don't know.

**Comment by CiTuX** [comment]
It's working on my Galaxy Nexus 4.2.1 and Nexus S 4.1.2
On my Nexus One 2.3.7, the SlidingMenu works with errors, the content views are not updating until you open the navigation and I get some StackOverflowError exceptions:

``` java
01-14 13:18:44.702: ERROR/AndroidRuntime(1140): FATAL EXCEPTION: main
        java.lang.StackOverflowError
        at android.text.SpannedString.getSpans(SpannedString.java:25)
        at android.text.Layout$SpannedEllipsizer.getSpans(Layout.java:1904)
        at android.text.Styled.drawUniformRun(Styled.java:61)
        at android.text.Styled.drawDirectionalRun(Styled.java:300)
        at android.text.Styled.drawText(Styled.java:359)
        at android.text.Layout.drawText(Layout.java:1392)
        at android.text.Layout.draw(Layout.java:372)
        at android.widget.TextView.onDraw(TextView.java:4170)
        at android.view.View.draw(View.java:6880)
        at android.view.View.buildDrawingCache(View.java:6642)
        at android.view.ViewGroup.onAnimationStart(ViewGroup.java:1259)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1505)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.widget.AbsListView.dispatchDraw(AbsListView.java:1480)
        at android.widget.ListView.dispatchDraw(ListView.java:3138)
        at android.view.View.draw(View.java:6883)
        at android.widget.AbsListView.draw(AbsListView.java:2584)
        at com.handmark.pulltorefresh.library.PullToRefreshListView$InternalListView.draw(PullToRefreshListView.java:280)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.View.draw(View.java:6883)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.View.draw(View.java:6883)
        at android.widget.FrameLayout.draw(FrameLayout.java:357)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.View.draw(View.java:6883)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.View.draw(View.java:6883)
        at android.widget.FrameLayout.draw(FrameLayout.java:357)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.View.draw(View.java:6883)
        at android.widget.FrameLayout.draw(FrameLayout.java:357)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.View.draw(View.java:6883)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.View.draw(View.java:6883)
        at android.widget.FrameLayout.draw(FrameLayout.java:357)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.View.draw(View.java:6883)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.View.draw(View.java:6883)
        at android.widget.FrameLayout.draw(FrameLayout.java:357)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at com.slidingmenu.lib.CustomViewAbove.dispatchDraw(CustomViewAbove.java:841)
        at android.view.View.draw(View.java:6883)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
        at android.view.View.draw(View.java:6883)
        at android.widget.FrameLayout.draw(FrameLayout.java:357)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1862)
        at android.view.ViewRoot.draw(ViewRoot.
```

I will investigate the errors on the Nexus One.

**Comment by CiTuX** [comment]
I have the same problems on the HTC Wildfire 2.2

**Comment by Prototik** [comment]
Now you see why not working?
