### ISSUE TITLE
ExpandableListView fails to load its SavedState

### ISSUE THREAD

**Issue by r-gurzkowski** [Prototik/HoloEverywhere#288]
Version TAG: 1.4.2

Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.holoeverywhere.widget.ListView$SavedState
at android.os.Parcel.readParcelable(Parcel.java:2077)
at android.view.AbsSavedState.(AbsSavedState.java:57)
at android.view.View$BaseSavedState.(View.java:17506)
at org.holoeverywhere.widget.ExpandableListView$SavedState.(ExpandableListView.java:72)
at org.holoeverywhere.widget.ExpandableListView$SavedState.(ExpandableListView.java:71)
at org.holoeverywhere.widget.ExpandableListView$SavedState$1.createFromParcel(ExpandableListView.java:61)
at org.holoeverywhere.widget.ExpandableListView$SavedState$1.createFromParcel(ExpandableListView.java:1)
at android.os.Parcel.readParcelable(Parcel.java:2103)
at android.os.Parcel.readValue(Parcel.java:1965)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2255)
at android.os.Parcel.readSparseArray(Parcel.java:1687)
at android.os.Parcel.readValue(Parcel.java:2022)
at android.os.Parcel.readMapInternal(Parcel.java:2226)
at android.os.Bundle.unparcel(Bundle.java:223)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1232)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:845)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1070)
at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1856)
at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:210)
at android.support.v4.app._HoloActivity.onCreate(_HoloActivity.java:294)

**Comment by Prototik** [comment]
I don't can reproduce this bug. Modify project in `bugs` branch (above) for crash application after onRestoreInstanceState.

**Comment by r-gurzkowski** [comment]
I have managed to reproduce the bug using your project. It does not happen when screen is rotating, but when system is stopping application. Probably it would be easier to reproduce it by using instrumentation test.

Here are the logs:

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.holoeverywhere.bug.i288/org.holoeverywhere.bug.i288.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.holoeverywhere.widget.ListView$SavedState
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
    at android.app.ActivityThread.access$600(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4898)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.holoeverywhere.widget.ListView$SavedState
    at android.os.Parcel.readParcelable(Parcel.java:2077)
    at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
    at android.view.View$BaseSavedState.<init>(View.java:17506)
    at org.holoeverywhere.widget.ExpandableListView$SavedState.<init>(ExpandableListView.java:72)
    at org.holoeverywhere.widget.ExpandableListView$SavedState.<init>(ExpandableListView.java:71)
    at org.holoeverywhere.widget.ExpandableListView$SavedState$1.createFromParcel(ExpandableListView.java:61)
    at org.holoeverywhere.widget.ExpandableListView$SavedState$1.createFromParcel(ExpandableListView.java:1)
    at android.os.Parcel.readParcelable(Parcel.java:2103)
    at android.os.Parcel.readValue(Parcel.java:1965)
    at android.os.Parcel.readSparseArrayInternal(Parcel.java:2255)
    at android.os.Parcel.readSparseArray(Parcel.java:1687)
    at android.os.Parcel.readValue(Parcel.java:2022)
    at android.os.Parcel.readMapInternal(Parcel.java:2226)
    at android.os.Bundle.unparcel(Bundle.java:223)
    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1232)
    at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1795)
    at android.app.Activity.onRestoreInstanceState(Activity.java:972)
    at android.app.Activity.performRestoreInstanceState(Activity.java:944)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1134)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2078)
... 11 more

**Comment by Prototik** [comment]
It's android bug, but this issue should be fixed in latest master branch, try it.

**Comment by siyamed** [comment]
Hi Protonik, I couldnt find the related commit, can you please describe how you fixed this problem?
