### ISSUE TITLE
PreferenceFramework not found

### ISSUE THREAD

**Issue by dodyg** [Prototik/HoloEverywhere#297]
I receive this error when trying to receive value from Preference

  java.lang.UnsatisfiedLinkError: HoloEverywhere: PreferenceFramework not found
        at org.holoeverywhere.preference.PreferenceManagerHelper.checkImpl(PreferenceManagerHelper.java:35)
        at org.holoeverywhere.preference.PreferenceManagerHelper.wrap(PreferenceManagerHelper.java:51)
        at org.holoeverywhere.preference.PreferenceManagerHelper.wrap(PreferenceManagerHelper.java:57)

**Comment by Prototik** [comment]
Duplicate #296
