### ISSUE TITLE
Class cast exception error when setting tile for a dialog fragment

### ISSUE THREAD

**Issue by MartinRajniak** [Prototik/HoloEverywhere#310]
02-19 11:17:46.075: E/AndroidRuntime(12361): FATAL EXCEPTION: main
02-19 11:17:46.075: E/AndroidRuntime(12361): java.lang.ClassCastException: org.holoeverywhere.internal.DialogTitle
02-19 11:17:46.075: E/AndroidRuntime(12361):    at org.holoeverywhere.internal.AlertController.setupTitle(AlertController.java:688)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at org.holoeverywhere.internal.AlertController.setupView(AlertController.java:722)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at org.holoeverywhere.internal.AlertController.installContent(AlertController.java:442)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at org.holoeverywhere.app.AlertDialog.onCreate(AlertDialog.java:389)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.app.Dialog.dispatchOnCreate(Dialog.java:307)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.app.Dialog.show(Dialog.java:225)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at org.holoeverywhere.app.DialogFragment.onStart(DialogFragment.java:272)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.support.v4.app.Fragment.performStart(Fragment.java:1484)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:941)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:429)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.os.Handler.handleCallback(Handler.java:587)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.os.Handler.dispatchMessage(Handler.java:92)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.os.Looper.loop(Looper.java:130)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at android.app.ActivityThread.main(ActivityThread.java:3691)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at java.lang.reflect.Method.invokeNative(Native Method)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at java.lang.reflect.Method.invoke(Method.java:507)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
02-19 11:17:46.075: E/AndroidRuntime(12361):    at dalvik.system.NativeStart.main(Native Method)

**Comment by MartinRajniak** [comment]
The problem is I think that in

org.holoeverywhere.internal.DialogTitle you extend android.widget.TextView (classical)

but when you are doing casting in Dialog AllertController you are using org.holoeverywhere.widget.TextView (holo)
