### ISSUE TITLE
ClastCastException on DatePickerDialog

### ISSUE THREAD

**Issue by silversmurf** [Prototik/HoloEverywhere#318]
on using DatePicker i get this error:
**java.lang.ClassCastException: org.holoeverywhere.internal.DialogTitle cannot be cast to org.holoeverywhere.widget.TextView**

I'm using SherlockFragment and calling my DialogPickerFragment that extends SherlockDialogFragment.

Here is the LogCat:

```
02-22 13:17:15.007: E/AndroidRuntime(2520): FATAL EXCEPTION: main
02-22 13:17:15.007: E/AndroidRuntime(2520): java.lang.ClassCastException: org.holoeverywhere.internal.DialogTitle cannot be cast to org.holoeverywhere.widget.TextView
02-22 13:17:15.007: E/AndroidRuntime(2520):     at org.holoeverywhere.internal.AlertController.setupTitle(AlertController.java:688)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at org.holoeverywhere.internal.AlertController.setupView(AlertController.java:722)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at org.holoeverywhere.internal.AlertController.installContent(AlertController.java:442)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at org.holoeverywhere.app.AlertDialog.onCreate(AlertDialog.java:389)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.app.Dialog.dispatchOnCreate(Dialog.java:351)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.app.Dialog.show(Dialog.java:256)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.support.v4.app.DialogFragment.onStart(DialogFragment.java:385)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.support.v4.app.Fragment.performStart(Fragment.java:1484)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:941)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:429)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.os.Handler.handleCallback(Handler.java:615)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.os.Handler.dispatchMessage(Handler.java:92)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.os.Looper.loop(Looper.java:137)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at android.app.ActivityThread.main(ActivityThread.java:4745)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at java.lang.reflect.Method.invokeNative(Native Method)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at java.lang.reflect.Method.invoke(Method.java:511)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
02-22 13:17:15.007: E/AndroidRuntime(2520):     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Prototik** [comment]
Duplicate #310 

PS.

> I'm using SherlockFragment
> SherlockDialogFragment

Maybe are you try `org.holoeverywhere.app.Fragment` and `org.holoeverywhere.app.DialogFragment`? :)

**Comment by silversmurf** [comment]
oh - of course!
ok, thanks... :)
