### ISSUE TITLE
Exception in Activity layout inflater with Robolectric + HoloEverywhere

### ISSUE THREAD

**Issue by felipecsl** [Prototik/HoloEverywhere#321]
Using current version of HoloEverywhere and robolectric 1.1

``` java
activity = new LoginActivity();
activity.onCreate();
```

The problem is in `setContentView`.

Tried already `getLayoutInflater().setFactory(this)`. Didn't work

```
java.lang.ClassCastException: com.xtremelabs.robolectric.shadows.ShadowLayoutInflater$LayoutInflaterAppSingletonizer$MyLayoutInflater cannot be cast to org.holoeverywhere.LayoutInflater
    at android.support.v4.app._HoloActivity.getLayoutInflater(_HoloActivity.java)
    at com.weheartit.activities.authentication.WhiLoginActivity.onCreate(WhiLoginActivity.java:46)
    at com.weheartit.activities.WhiLoginActivityTest.setUp(WhiLoginActivityTest.java:32)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    at com.xtremelabs.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:292)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

**Comment by Prototik** [comment]
``` java
@Override
public LayoutInflater getLayoutInflater() {
  return LayoutInflater.from(this);
}
```

Why and how Robolectric to override methods _HoloActivity? Contact the developer of Robolectric.  
Or extend com.xtremelabs.robolectric.shadows.ShadowLayoutInflater$LayoutInflaterAppSingletonizer$MyLayoutInflater from org.holoeverywhere.LayoutInflater.

**Comment by imminent** [comment]
@Prototik I sent this toward Robolectric, but are you saying that those things should be done in our code, or changed in Robolectric? I don't completely follow your sentences.

**Comment by xian** [comment]
I think you want to return an android.view.LayoutInflater instead? Unless you need some methods from your own...

``` java
@Override
public android.view.LayoutInflater getLayoutInflater() {
  return LayoutInflater.from(this);
}
```

-- edit --
sorry, misunderstood the problem. We'll address this in Robolectric.

**Comment by felipecsl** [comment]
I'm still confused whether this should be handled by HoloEverywhere or Robolectric
