### ISSUE TITLE
android.view.InflateException: Binary XML file line #350: Error inflating class <unknown>

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#342]
device : LT15i
os.version : unknown

android.view.InflateException: Binary XML file line #350: Error inflating class <unknown>
at android.view.LayoutInflater.createView(LayoutInflater.java:606)
at org.holoeverywhere.LayoutInflater.tryCreateView(LayoutInflater.java:315)
at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:279)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:653)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:678)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:242)
at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:227)
at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:222)
at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:217)
at com.sunnysoft.app.wordplus.fragments.WordPlayFragment.onCreateView(WordPlayFragment.java:1072)
at android.support.v4.app._HoloFragment.onCreateView(_HoloFragment.java:214)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:461)
at com.sunnysoft.app.wordplus.MainActivity$NavigationItem.onClick(MainActivity.java:178)
at com.sunnysoft.app.wordplus.MainActivity$NavigationAdapter.onItemSelected(MainActivity.java:147)
at com.sunnysoft.app.wordplus.MainActivity$NavigationAdapter.onItemClick(MainActivity.java:134)
at android.widget.AdapterView.performItemClick(AdapterView.java:292)
at android.widget.AbsListView.performItemClick(AbsListView.java:1065)
at org.holoeverywhere.widget.ListView.performItemClick(ListView.java:660)
at com.sunnysoft.app.wordplus.MainActivity.setMenu(MainActivity.java:989)
at com.sunnysoft.app.wordplus.fragments.DashBoardFragment$1.onClick(DashBoardFragment.java:138)
at android.view.View.performClick(View.java:3534)
at android.view.View$PerformClick.run(View.java:14263)
at android.os.Handler.handleCallback(Handler.java:605)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4441)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at android.view.LayoutInflater.createView(LayoutInflater.java:586)
... 40 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/scrubber_progress_horizontal_holo_light.xml from drawable resource ID #0x10804d3
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:138)
at org.holoeverywhere.drawable.DrawableCompat.getDrawable(DrawableCompat.java:113)
at org.holoeverywhere.widget.ProgressBar.<init>(ProgressBar.java:246)
at org.holoeverywhere.widget.ProgressBar.<init>(ProgressBar.java:203)
at org.holoeverywhere.widget.AbsSeekBar.<init>(AbsSeekBar.java:42)
at org.holoeverywhere.widget.SeekBar.<init>(SeekBar.java:30)
at org.holoeverywhere.widget.SeekBar.<init>(SeekBar.java:26)
... 43 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-hdpi/scrubber_track_holo_light.9.png from drawable resource ID #0x10804d6
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:152)
at org.holoeverywhere.drawable.DrawableCompat.getDrawable(DrawableCompat.java:107)
at org.holoeverywhere.drawable.LayerDrawable.inflate(LayerDrawable.java:368)
at org.holoeverywhere.drawable.DrawableCompat.createFromXmlInner(DrawableCompat.java:87)
at org.holoeverywhere.drawable.DrawableCompat.createFromXml(DrawableCompat.java:63)
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:135)
... 49 more
Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
at android.content.res.AssetManager.openNonAssetFdNative(Native Method)
at android.content.res.AssetManager.openNonAssetFd(AssetManager.java:428)
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:147)
... 54 more

**Comment by Prototik** [comment]
> This file can not be opened as a file descriptor; it is probably compressed

Check your build settings.
