### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Could not find class: fragment

### ISSUE THREAD

**Issue by Zeliret** [Prototik/HoloEverywhere#346]
Hi!

I have a ViewPager on Main Activity. There are 3 fragments in it one. Each fragment has one more fragment inside. When I start app 1st time everything is fine, but after some swipes the app crashes. Actually it happens when I swipe from 3rd fragment to 1st and then swipe back. The fragment was destroyed and the fragment manager trying to create a new instance i suppose. In that case I dont understand why the fragment was created in 1st time. 

Here stacktrace: 

``` java
ERROR/AndroidRuntime(12982): FATAL EXCEPTION: main
        android.view.InflateException: Binary XML file line #13: Error inflating class fragment
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:581)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:278)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:263)
        at mega.onicon.fragment.DialogsFragment.onCreateView(DialogsFragment.java:57)
        at android.support.v4.app._HoloFragment.onCreateView(_HoloFragment.java:177)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
        at android.support.v4.app.FragmentManagerImpl.attachFragment(FragmentManager.java:1264)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:672)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
        at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:461)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1011)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:880)
        at android.support.v4.view.ViewPager$3.run(ViewPager.java:238)
        at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1696)
        at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1829)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:848)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:869)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:869)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:869)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:869)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:869)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:869)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:869)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1750)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1135)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2096)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1734)
        at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2216)
        at android.view.ViewRoot.handleMessage(ViewRoot.java:1887)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:3687)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.ClassNotFoundException: Could not find class: fragment
        at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:318)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
        ... 41 more
```

**Comment by Prototik** [comment]
Show activity layout and layout which you inflate in 

> at mega.onicon.fragment.DialogsFragment.onCreateView(DialogsFragment.java:57)

**Comment by Prototik** [comment]
Кстати, megagroup, предлагаю не общаться на ломанном английском и не насиловать мне мозг.

**Comment by Zeliret** [comment]
Активити:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="fill_parent"
             android:layout_height="fill_parent">
    <LinearLayout android:id="@android:id/content"
                  android:orientation="vertical"
                  android:layout_width="fill_parent"
                  android:layout_height="fill_parent">
            <ViewPager android:id="@+id/pager"
                       android:layout_width="fill_parent"
                       android:layout_height="fill_parent">
                <PagerTitleStrip android:id="@+id/pagerTitleStrip"
                                 android:layout_width="fill_parent"
                                 android:layout_height="wrap_content"
                                 android:layout_gravity="top"
                                 android:background="#aaa"
                                 android:textColor="#eee"
                                 android:paddingTop="2dp"
                                 android:paddingBottom="2dp"
                                 android:paddingLeft="5dp"
                                 android:paddingRight="5dp" />
            </ViewPager>
    </LinearLayout>
    <include layout="@layout/offline_panel" />
</FrameLayout>
```

Фрагмент:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:layout_width="fill_parent"
              android:layout_height="fill_parent">
    <ProgressBar android:id="@+id/progress"
                 android:layout_width="70dp"
                 android:layout_height="70dp"
                 android:layout_gravity="center"
                 android:layout_weight="1"
                 style="?android:attr/progressBarStyleLarge"
                 android:indeterminate="true" />
    <fragment android:id="@+id/listFragment"
              android:name="mega.onicon.fragment.DialogsListFragment"
              android:layout_width="match_parent"
              android:layout_height="match_parent" />
</LinearLayout>
```

**Comment by Zeliret** [comment]
С помощью дебага понял вот что: 
когда создается фрагмент (mega.onicon.fragment.DialogsListFragment), сперва вызывается FragmentActivity::onCreateView из суппорт либы. Она создает фрагмент и вью, все ок. 

Когда я листаю пейджер, вьюшка фрагмента убивается. Возвращаясь на него я опять попадаю в  FragmentActivity::onCreateView, а там фрагмент уже существует, и из-за проверки:

``` java
} else if (fragment.mInLayout) {
 // A fragment already exists and it is not one we restored from
            // previous state.
            throw new IllegalArgumentException(attrs.getPositionDescription()
                    + ": Duplicate id 0x" + Integer.toHexString(id)
                    + ", tag " + tag + ", or parent id 0x" + Integer.toHexString(containerId)
                    + " with another fragment for " + fname);
}
```

вьюшка не создается. Потом HoloFactoryMerger запускает фабрику Holo. И там уже вылетает исключение, что не найден класс fragment. Очень странно...

**Comment by Prototik** [comment]
Вот я тоже добился этого эффекта. Кстати, support library какой версии? Nested fragments вроде только с r11.

**Comment by Zeliret** [comment]
12 ревизия. Я тут нашел топик: http://stackoverflow.com/questions/6847460/fragments-within-fragments

Судя по этой доке: http://developer.android.com/about/versions/android-4.2.html#NestedFragments

Есть ограничение: 

> Note: You cannot inflate a layout into a fragment when that layout includes a < fragment >. Nested fragments are only supported when added to a fragment dynamically.

Сделал динамическое создание фрагмента - заработало. Но все равно, это очень странно, т.к. в первый раз фрагмент инфлейтится из xml без проблем.

**Comment by Prototik** [comment]
Я тут это... Похвастаться хочу.

HoloEverywhere - первая, и на данный момент единственная библиотека, которая разрешает вложенные фрагменты в xml любой глубины. Пользуйтесь :)

**Comment by Prototik** [comment]
А, и еще, для этого используется несколько хаков в LayoutInflater. Для того, чтобы все работало, необходимо использовать только тот, что суется аргументом в onCreateView. Т.е. если писать код по гайдлайнам, а там везде контент инфлейтится через `inflater.inflate(R.layout.layout, container, false)`, то все ок.

**Comment by Zeliret** [comment]
Отлично! Большое спасибо :) А то каждый раз программно задавать фрагмент - теряется вся прелесть модульного подхода.
