### ISSUE TITLE
NoSuchMethodError when accessing action bar on Galaxy Note 2.3.6

### ISSUE THREAD

**Issue by MartinRajniak** [Prototik/HoloEverywhere#348]
![NoSuchMethod](https://f.cloud.github.com/assets/1181874/253834/da0ca378-8be2-11e2-953c-29fb95b4e73d.png)

**Comment by mkuprionis** [comment]
Additional log, on Galaxy S2 @ 4.0.3.

Edit: I'm experiencing crash at 4418af25c90a7909d773eb4ed58f39efe766b817 and at 792ed59b0a9a99665cb81f93ef61fb446d05f4bb there's no this problem.

```
java.lang.NoSuchMethodError: android.view.ViewStub.setLayoutInflater
    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:350)
    at org.holoeverywhere.LayoutInflater.tryCreateView(LayoutInflater.java:788)
    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:593)
    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:430)
    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:728)
    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:549)
    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:499)
    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:494)
    at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2871)
    at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2931)
    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:286)
    at org.holoeverywhere.app.Dialog.setContentView(Dialog.java:141)
    at org.holoeverywhere.app.Dialog.setContentView(Dialog.java:135)
    at org.holoeverywhere.app.Dialog.setContentView(Dialog.java:130)
    at org.holoeverywhere.app.AlertDialog.installDecorView(AlertDialog.java:405)
    at org.holoeverywhere.internal.AlertController.installContent(AlertController.java:474)
    at org.holoeverywhere.app.AlertDialog.onCreate(AlertDialog.java:411)
    at org.holoeverywhere.app.ProgressDialog.onCreate(ProgressDialog.java:213)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:353)
    at android.app.Dialog.show(Dialog.java:257)
    at org.holoeverywhere.app.ProgressDialog.show(ProgressDialog.java:51)
    at <...>.DialogHelper.showProgressDialog(DialogHelper.java:122)
    at <...>.FacebookAuthFragment.doLoginFacebook(FacebookAuthFragment.java:70)
    at <...>.FacebookAuthFragment.access$0(FacebookAuthFragment.java:69)
    at <...>.FacebookAuthFragment$1.onClick(FacebookAuthFragment.java:62)
    at android.view.View.performClick(View.java:3591)
    at android.view.View$PerformClick.run(View.java:14263)
    at android.os.Handler.handleCallback(Handler.java:605)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4507)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
    at dalvik.system.NativeStart.main(Native Method)
```
