### ISSUE TITLE
Typeface cannot be made

### ISSUE THREAD

**Issue by mikepenz** [Prototik/HoloEverywhere#35]
With the newest version a user always gets the following error-message:

java.lang.RuntimeException: native typeface cannot be made
    at android.graphics.Typeface.<init>(Typeface.java:147)
    at android.graphics.Typeface.createFromAsset(Typeface.java:121)
    at com.WazaBe.HoloEverywhere.FontLoader.loadFont(FontLoader.java:20)
    at com.WazaBe.HoloEverywhere.HoloAlertDialogBuilder.<init>(HoloAlertDialogBuilder.java:41)
    at com.tundem.zuzzle.GameActivity.doYouReallyWantToExit(GameActivity.java:616)
    at com.tundem.zuzzle.GameActivity.onKeyDown(GameActivity.java:209)
    at android.view.KeyEvent.dispatch(KeyEvent.java:1326)
    at android.app.Activity.dispatchKeyEvent(Activity.java:2078)
    at com.actionbarsherlock.app.SherlockFragmentActivity.dispatchKeyEvent(SherlockFragmentActivity.java:122)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1709)
    at android.view.ViewRoot.deliverKeyEventToViewHierarchy(ViewRoot.java:2566)
    at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2541)
    at android.view.ViewRoot.handleMessage(ViewRoot.java:1873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3835)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
    at dalvik.system.NativeStart.main(Native Method)

Is it my issue or is it caused by the new FontLoader Class?

**Comment by ChristopheVersieux** [comment]
For sure caused by the new font lader.
I woll have a look later this week, I am in business trip and might not be
back before a few weeks.

On Tue, Jul 3, 2012 at 9:40 PM, Mike Penz <
reply@reply.github.com

**Comment by ChristopheVersieux** [comment]
BTWn there are a lot of people having the same issue on stackoverflow and a
lot of differents ways to fix it.

I hope I will be able to reproduce the bug.

**Comment by mikepenz** [comment]
Thanks for the fast answer. 

I did some research and found that it is normally caused by not-found fonts (file not found) or the font's incompatiblity. 

Perhaps the compile-process was faulty and the .apk was not packed correct. I'll repack it and see if it fixes the issue.
I'll also add a try and catch to be save for future issues. 

Have a nice weeks. 
Thanks.

**Comment by fedefernandez** [comment]
Hi @mikepenz 

You need to add "Roboto-Regular.ttf" to your assets folder. Remember that library projects cannot include raw assets (http://developer.android.com/tools/projects/index.html#considerations).

However the try/catch block is a good practice.

Hope this help.

**Comment by mikepenz** [comment]
Thanks. Totally forgot about this, but why was it working on all previous versions? Never added it before?

Oh and if it's important please add it to the "How to install ?"-Section because most will forget it xD. 

Thanks for your help

**Comment by fedefernandez** [comment]
You are welcome

I don't know why was working on all previous versions xD

**Comment by fedefernandez** [comment]
@mikepenz reopen the issue please, it's not solved. I only give you a temporary solution

**Comment by mikepenz** [comment]
Opened it again.
Cheers.
