### ISSUE TITLE
ClassCastException: org.holoeverywhere.preference.Preference cannot be cast to org.holoeverywhere.internal.GenericInflater$Parent

### ISSUE THREAD

**Issue by pavel-shatskikh** [Prototik/HoloEverywhere#355]
Hi! I'm getting the following error:

```
    Caused by: java.lang.ClassCastException: org.holoeverywhere.preference.Preference cannot be cast to org.holoeverywhere.internal.GenericInflater$Parent
    at org.holoeverywhere.internal.GenericInflater.rInflate(GenericInflater.java:264)
    at org.holoeverywhere.internal.GenericInflater.rInflate(GenericInflater.java:265)
    at org.holoeverywhere.internal.GenericInflater.inflate(GenericInflater.java:193)
    at org.holoeverywhere.internal.GenericInflater.inflate(GenericInflater.java:163)
    at org.holoeverywhere.internal.GenericInflater.inflate(GenericInflater.java:157)
    at org.holoeverywhere.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:380)
    at org.holoeverywhere.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:287)
    at my.package.app.SettingsActivity.onCreate(SettingsActivity.java:14)
```

In SettingsActivity:

public class SettingsActivity extends PreferenceActivity {

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    addPreferencesFromResource(R.xml.preferences);
}
```

}

In preferences.xml:

<?xml version="1.0" encoding="utf-8"?>

<PreferenceScreen xmlns:holo="http://schemas.android.com/apk/res-auto">

```
<Preference
        holo:selectable="false"
        holo:title="Settings">

    <SwitchPreference
            holo:id="@+id/message_group_preference"
            holo:summaryOff="@string/switch_off"
            holo:summaryOn="@string/switch_on"
            holo:title="@string/message_group" />

</Preference>
```

</PreferenceScreen>

Holoeverywhere version: 1.5.
Android SDK: 4.2
Tested on: Android 4.1.2 (gt-i9300).

What am I doing wrong?

**Comment by Prototik** [comment]
Root element of preference layout should be PreferenceScreen, not Preference.

**Comment by pavel-shatskikh** [comment]
thanks!
