### ISSUE TITLE
NPE when fragment with child fragments is destroyed 

### ISSUE THREAD

**Issue by croemmich** [Prototik/HoloEverywhere#357]
Application sometime crashes when fragments with child fragments are destroyed. Since: 4b2f98d61ffa4f855598ad6c00fec5544c54519a

I haven't been able to reliably reproduce it, but it happens often in my case.

```
3-21 00:09:12.511: ERROR/ACRA(20849): java.lang.NullPointerException
        at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1175)
        at android.support.v4.app._HoloFragment.onDestroyView(_HoloFragment.java:198)
        at android.support.v4.app.Fragment.performDestroyView(Fragment.java:1665)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:980)
        at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1185)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:639)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:429)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by croemmich** [comment]
Thanks!
