### ISSUE TITLE
setSupportProgressBarIndeterminateVisibility error if using with slider addon

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#371]
I'm trying to add slider to existing applicatin which uses indeterminate progress in the actionbar to indicate loading activity. When application tries to adjust indeterminate progress visibility it crashes. I've added modified DemoActivity.onCreate code to reproduce the issue

``` java
@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
///ADD
        requestWindowFeature(Window.FEATURE_INDETERMINATE_PROGRESS);
///ENDOFADD
        final ActionBar ab = getSupportActionBar();
        ab.setTitle(R.string.library_name);

        setContentView(R.layout.content);

        final AddonSliderA slider = addonSlider();

        if (findViewById(R.id.customMenuFrame) == null) {
            // Phone
            mStaticMenu = false;
            ab.setDisplayHomeAsUpEnabled(true);
            slider.setLeftViewWidth(computeMenuWidth());
            slider.setDragWithActionBar(true);
        } else {
            // Tablet
            mStaticMenu = true;
            slider.setAddonEnabled(false);
        }

        mMenuFragment = (MenuFragment) getSupportFragmentManager().findFragmentById(R.id.leftView);

        getSupportFragmentManager().addOnBackStackChangedListener(this);
///ADD
        Handler handler = new Handler();
        handler.post(new Runnable()
        {

            @Override
            public void run()
            {
                setSupportProgressBarIndeterminateVisibility(false);
            }
        });
///ENDOFADD
    }
```

Exception

```
03-28 15:27:39.769: E/AndroidRuntime(6926): FATAL EXCEPTION: main
03-28 15:27:39.769: E/AndroidRuntime(6926): java.lang.NullPointerException
03-28 15:27:39.769: E/AndroidRuntime(6926):     at com.android.internal.policy.impl.PhoneWindow.updateProgressBars(PhoneWindow.java:1295)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at com.android.internal.policy.impl.PhoneWindow.onIntChanged(PhoneWindow.java:1247)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at com.android.internal.policy.impl.PhoneWindow.updateInt(PhoneWindow.java:2998)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at com.android.internal.policy.impl.PhoneWindow.setFeatureInt(PhoneWindow.java:1192)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at android.app.Activity.setProgressBarIndeterminateVisibility(Activity.java:4077)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at com.actionbarsherlock.internal.ActionBarSherlockNative.setProgressBarIndeterminateVisibility(ActionBarSherlockNative.java:157)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at org.holoeverywhere.addon.AddonSherlock$AddonSherlockA.setProgressBarIndeterminateVisibility(AddonSherlock.java:182)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at org.holoeverywhere.app.Activity.setSupportProgressBarIndeterminateVisibility(Activity.java:599)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at org.holoeverywhere.demo.DemoActivity$1.run(DemoActivity.java:77)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at android.os.Handler.handleCallback(Handler.java:605)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at android.os.Handler.dispatchMessage(Handler.java:92)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at android.os.Looper.loop(Looper.java:137)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at android.app.ActivityThread.main(ActivityThread.java:4424)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at java.lang.reflect.Method.invokeNative(Native Method)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at java.lang.reflect.Method.invoke(Method.java:511)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
03-28 15:27:39.769: E/AndroidRuntime(6926):     at dalvik.system.NativeStart.main(Native Method)

```

**Comment by httpdispatch** [comment]
Hmm, if i use postDelayed to 1000 ms application doesn't crash. But if i use delay 10ms application still crashes. Any suggestions?

**Comment by Prototik** [comment]
Перенесите `setSupportProgressBarIndeterminateVisibility(false);` в onPostCreate(), после вызова super.onPostCreate(). Без хандлера.

**Comment by httpdispatch** [comment]
Спасибо большое, это помогло. Есть какой-нибудь аналог onPostCreate для MenuFragment? Дело в том что у меня MenuFragment вставляет другой фрагмент, который сразу же пытается поменять состояние setSupportProgressBarIndeterminateVisibility. Это все работало на ActionBar табах. 
Я пока нашел временное решение. Вставляю MenuFragment вручную в методе onPostCreate главного активити но не уверен, что это правильно

``` java
mMenuFragment = new MenuFragment();
        getSupportFragmentManager().beginTransaction().add(R.id.leftView, mMenuFragment,
                "MenuFragment").commit();
```

R.id.leftView заменил на RelativeLayout

**Comment by Prototik** [comment]
Можно добавить слушатель состояний в Slider, тот должен вызвать onContentShowed() при своем первом показе.

**Comment by Prototik** [comment]
Или просто вручную создать некий метод во фрагменте и тупо его вызвать в onPostCreate()

**Comment by httpdispatch** [comment]
Спасибо за помощь
