### ISSUE TITLE
ActionBar inflate exception with custom layout

### ISSUE THREAD

**Issue by Leandros** [Prototik/HoloEverywhere#373]
I try to inflate the ActionBar with a custom layout, but I get an exception on Android 2.2 and 2.3, but not on Android 4.2.2 (Nexus 4).

**Exception**

```
03-30 04:01:26.934: ERROR/AndroidRuntime(900): FATAL EXCEPTION: main
        android.view.InflateException: Binary XML file line #2: Error inflating class org.holoeverywhere.widget.LinearLayout
        at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:386)
        at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:599)
        at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:448)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:533)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:492)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:487)
        at de.skilloverflow.moneytracker.fragments.AddAccount.onCreateView(AddAccount.java:78)
        at android.support.v4.app._HoloFragment.onCreateView(_HoloFragment.java:182)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:429)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:4627)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:521)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.reflect.InvocationTargetException
        at org.holoeverywhere.widget.LinearLayout.<init>(LinearLayout.java:32)
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:446)
        at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:362)
        ... 22 more
        Caused by: android.content.res.Resources$NotFoundException: File res/drawable-hdpi/done_new.png from drawable resource ID #0x0
        at android.content.res.Resources.loadDrawable(Resources.java:1714)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
        at org.holoeverywhere.widget.LinearLayout.init(LinearLayout.java:142)
        at org.holoeverywhere.widget.LinearLayout.<init>(LinearLayout.java:37)
        ... 26 more
        Caused by: java.io.FileNotFoundException: res/drawable-hdpi/done_new.png
        at android.content.res.AssetManager.openNonAssetNative(Native Method)
        at android.content.res.AssetManager.openNonAsset(AssetManager.java:405)
        at android.content.res.Resources.loadDrawable(Resources.java:1706)
        ... 29 more
```

This is how I inflate the ActionBar:

``` java
LayoutInflater inflater = (LayoutInflater) mActionBar.getThemedContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
final View customActionBarView = inflater.inflate(R.layout.actionbar_custom_view_done_discard, null);

mActionBar.setDisplayOptions(ActionBar.DISPLAY_SHOW_CUSTOM, ActionBar.DISPLAY_SHOW_CUSTOM | ActionBar.DISPLAY_SHOW_HOME
                | ActionBar.DISPLAY_SHOW_TITLE);
mActionBar.setCustomView(customActionBarView, new ActionBar.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT));
```

`getSupportActionBarContext()` doesn't work either.

The icons are their, they're not missing!

**Comment by Prototik** [comment]
Show layout which you are inflate into de.skilloverflow.moneytracker.fragments.AddAccount

**Comment by Leandros** [comment]
Sure, it's nothing special. Just a Done / Discard layout for the ActionBar:

``` xml
<org.holoeverywhere.widget.LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="horizontal"
    android:divider="?android:attr/dividerVertical"
    android:showDividers="middle"
    android:dividerPadding="12dp">

    <include layout="@layout/actionbar_discard_button" />

    <include layout="@layout/actionbar_done_button" />
</org.holoeverywhere.widget.LinearLayout>
```

The buttons are like this: 

``` xml
<org.holoeverywhere.widget.FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    style="?android:actionButtonStyle"
    android:id="@+id/actionbar_discard"
    android:background="@drawable/selectable_background_holo_green"
    android:layout_width="0dp"
    android:layout_height="match_parent"
    android:layout_weight="1">

    <org.holoeverywhere.widget.TextView
        style="?android:actionBarTabTextStyle"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:paddingRight="20dp"
        android:drawableLeft="@drawable/action_discard"
        android:drawablePadding="8dp"
        android:gravity="center_vertical"
        android:text="@string/discard" />

</org.holoeverywhere.widget.FrameLayout>
```

**Comment by Prototik** [comment]
> ?android:attr/dividerVertical

Replace to `android:divider="?dividerVertical"`

> ?android:actionButtonStyle

`?actionButtonStyle`

> ?android:actionBarTabTextStyle

`?actionBarTabTextStyle`

> android:showDividers="middle"

Should be holo: prefix

Also i don't think that you should use package-prefix. HoloEverywhere's LayoutInflater use HE widgets instead system.

**Comment by Leandros** [comment]
Works thanks a lot.
