### ISSUE TITLE
Opening a menu, by pressing the hardware button crashes on 2.2 - 4.x

### ISSUE THREAD

**Issue by Leandros** [Prototik/HoloEverywhere#375]
I use a normal overflow menu, inflated from an xml file in `onCreateMenu`, but when I press the menu button, the application crash.
On Android 4.x it works find, though the Theme for the menu is broken, because it's black font on black background.

```
03-30 05:12:57.824: ERROR/AndroidRuntime(1217): FATAL EXCEPTION: main
        java.lang.NullPointerException
        at com.android.internal.view.menu.IconMenuView.addItemView(IconMenuView.java:289)
        at com.android.internal.view.menu.IconMenuView.updateChildren(IconMenuView.java:351)
        at com.android.internal.view.menu.IconMenuView.initialize(IconMenuView.java:333)
        at com.android.internal.view.menu.MenuBuilder$MenuType.getMenuView(MenuBuilder.java:199)
        at com.android.internal.view.menu.MenuBuilder.getMenuView(MenuBuilder.java:323)
        at com.android.internal.policy.impl.PhoneWindow.initializePanelContent(PhoneWindow.java:840)
        at com.android.internal.policy.impl.PhoneWindow.openPanel(PhoneWindow.java:417)
        at com.android.internal.policy.impl.PhoneWindow.onKeyUpPanel(PhoneWindow.java:603)
        at com.android.internal.policy.impl.PhoneWindow.onKeyUp(PhoneWindow.java:1319)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1648)
        at android.view.ViewRoot.deliverKeyEventToViewHierarchy(ViewRoot.java:2471)
        at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2441)
        at android.view.ViewRoot.handleMessage(ViewRoot.java:1735)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:4627)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:521)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Prototik** [comment]
Duplicate #358

**Comment by Leandros** [comment]
I am using the latest version of the library. I cloned it yesterday. 

Edit: Nevermind, cherry picked the fix commit.
