### ISSUE TITLE
Menu inflating issue after 1.5.0 update

### ISSUE THREAD

**Issue by r-gurzkowski** [Prototik/HoloEverywhere#392]
Hey, 

I have problem with creating menu on phones with physical menu key, after update from 1.4.x to 1.5.0. On 4.1 device nothing happens, on android 2.3 application hangs with this attached stack trace (no holo classes there). On HTC One X with no physical menu button everything is ok. 

java.lang.NullPointerException
    at com.android.internal.view.menu.IconMenuView.addItemView(IconMenuView.java:289)
    at com.android.internal.view.menu.IconMenuView.updateChildren(IconMenuView.java:351)
    at com.android.internal.view.menu.IconMenuView.initialize(IconMenuView.java:333)
    at com.android.internal.view.menu.MenuBuilder$MenuType.getMenuView(MenuBuilder.java:199)
    at com.android.internal.view.menu.MenuBuilder.getMenuView(MenuBuilder.java:323)
    at com.android.internal.policy.impl.PhoneWindow.initializePanelContent(PhoneWindow.java:868)
    at com.android.internal.policy.impl.PhoneWindow.openPanel(PhoneWindow.java:437)
    at com.android.internal.policy.impl.PhoneWindow.onKeyUpPanel(PhoneWindow.java:631)
    at com.android.internal.policy.impl.PhoneWindow.onKeyUp(PhoneWindow.java:1378)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1727)
    at android.view.ViewRoot.deliverKeyEventToViewHierarchy(ViewRoot.java:2627)
    at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2602)
    at android.view.ViewRoot.handleMessage(ViewRoot.java:1874)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:3687)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by Prototik** [comment]
Duplicate #358
