### ISSUE TITLE
Preference framework not found

### ISSUE THREAD

**Issue by sfkamath** [Prototik/HoloEverywhere#398]
There seems to be an incompatibility with the facebook sdk. Not sure how to work around this. Any help would be appreciated

Look at the cache field in the class here
https://github.com/facebook/facebook-android-sdk/blob/master/facebook/src/com/facebook/SharedPreferencesTokenCachingStrategy.java

Stacktrace below
04-09 22:19:45.230: E/AndroidRuntime(2130): java.lang.UnsatisfiedLinkError: HoloEverywhere: PreferenceFramework not found
04-09 22:19:45.230: E/AndroidRuntime(2130):     at org.holoeverywhere.preference.PreferenceManagerHelper.checkImpl(PreferenceManagerHelper.java:37)
04-09 22:19:45.230: E/AndroidRuntime(2130):     at org.holoeverywhere.preference.PreferenceManagerHelper.wrap(PreferenceManagerHelper.java:58)
04-09 22:19:45.230: E/AndroidRuntime(2130):     at org.holoeverywhere.preference.PreferenceManagerHelper.wrap(PreferenceManagerHelper.java:64)
04-09 22:19:45.230: E/AndroidRuntime(2130):     at org.holoeverywhere.app.Application.getSharedPreferences(Application.java:94)
04-09 22:19:45.230: E/AndroidRuntime(2130):     at org.holoeverywhere.app.Application.getSharedPreferences(Application.java:1)
04-09 22:19:45.230: E/AndroidRuntime(2130):     at com.facebook.SharedPreferencesTokenCachingStrategy.<init>(SharedPreferencesTokenCachingStrategy.java:114)
04-09 22:19:45.230: E/AndroidRuntime(2130):     at com.facebook.SharedPreferencesTokenCachingStrategy.<init>(SharedPreferencesTokenCachingStrategy.java:88)
04-09 22:19:45.230: E/AndroidRuntime(2130):     at com.facebook.Session.<init>(Session.java:229)

**Comment by Prototik** [comment]
Attach preference framework from addons folder.

**Comment by vitriolix** [comment]
I just hit this issue too.  I imported the Prefs library project and added it to my project properites as a library it uses, but still I get this.  What step am I missing?

**Comment by vitriolix** [comment]
strange, this was related to the version of the facebook sdk I had.  a coworker had a different version and it caused this.

**Comment by jeymo** [comment]
Didn't work for me...I use facebook sdk 3.0.1. Which version do you use, Vitriolix?

**Comment by Prototik** [comment]
[Preferences addon](https://github.com/Prototik/HoloEverywhere/tree/master/addons/preferences)
[Facebook sdk for HE](https://github.com/Prototik/HoloEverywhere/tree/addon-facebook)

**Comment by rddimon** [comment]
I have problem with yandex mapview. What can I correct, can help me?
Error message:

07-10 13:01:17.778: ERROR/AndroidRuntime(15741): FATAL EXCEPTION: main
        android.view.InflateException: Binary XML file line #6: Error inflating class ru.yandex.yandexmapkit.MapView
        at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:376)
        at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:584)
        at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:438)
        at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:725)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:532)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:482)
        at com.bizico.app.yandex.YandexMap_.onCreateView(YandexMap_.java from OutputFileObject:43)
        at android.support.v4.app._HoloFragment.onCreateView(_HoloFragment.java:180)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:429)
        at android.os.Handler.handleCallback(Handler.java:605)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4441)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
        at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:352)
        ... 22 more
        Caused by: java.lang.UnsatisfiedLinkError: HoloEverywhere: PreferenceFramework not found
        at org.holoeverywhere.preference.PreferenceManagerHelper.checkImpl(PreferenceManagerHelper.java:37)
        at org.holoeverywhere.preference.PreferenceManagerHelper.wrap(PreferenceManagerHelper.java:58)
        at org.holoeverywhere.preference.PreferenceManagerHelper.wrap(PreferenceManagerHelper.java:64)
        at org.holoeverywhere.app.Application.getSharedPreferences(Application.java:97)
        at org.holoeverywhere.app.Application.getSharedPreferences(Application.java:30)
        at ru.yandex.core.CoreApplication.restoreFsRoot(Unknown Source)
        at ru.yandex.core.CoreApplication.initialize(Unknown Source)
        at ru.yandex.core.CoreApplication.initOnce(Unknown Source)
        at ru.yandex.yandexmapkit.MapStaticView.init(Unknown Source)
        at ru.yandex.yandexmapkit.MapStaticView.<init>(Unknown Source)
        at ru.yandex.yandexmapkit.MapView.<init>(Unknown Source)
        ... 25 more

**Comment by BraisGabin** [comment]
Add the [Preferences Addon Library](https://github.com/Prototik/HoloEverywhere/tree/master/addons/preferences).

**Comment by rddimon** [comment]
works, thanks)

**Comment by carl1990** [comment]
i hava add this lib into project but still cannot work ,what should i do? I was miss what?
