### ISSUE TITLE
Error inflating class ListView

### ISSUE THREAD

**Issue by tslocum** [Prototik/HoloEverywhere#423]
When trying to create an AlertDialog populated with Google account names, I receive an "Error inflating class ListView" error.  I am using org.holoeverywhere.app.AlertDialog

Code:

```
    public AlertDialog showSignInDialog(Activity activity) {
        AccountManager accountManager = AccountManager
                .get(getApplicationContext());
        final Account[] accounts = accountManager
                .getAccountsByType("com.google");

        final int size = accounts.length;

        if (size > 0) {
            String[] names = new String[size];
            for (int i = 0; i < size; i++) {
                names[i] = accounts[i].name;
            }

            AlertDialog accountsAlertDialog = new AlertDialog.Builder(activity)
                    .setTitle("Select account")
                    .setItems(names, new DialogInterface.OnClickListener() {
                        public void onClick(DialogInterface dialog, int which) {
                            // Do something
                        }
                    })
                    .create();
            accountsAlertDialog.show();

            return accountsAlertDialog;
        } else {
            return showOpenIDSignInDialog(activity);
        }
    }
```

Logcat output:

```
04-26 11:22:25.443: E/AndroidRuntime(24134): Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class ListView
04-26 11:22:25.443: E/AndroidRuntime(24134):    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:454)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:533)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:492)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:487)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at org.holoeverywhere.internal.AlertController$AlertParams.createListView(AlertController.java:151)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at org.holoeverywhere.internal.AlertController$AlertParams.apply(AlertController.java:137)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at org.holoeverywhere.app.AlertDialog$Builder.create(AlertDialog.java:59)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at sh.ftp.rocketninelabs.meditationassistant.MeditationAssistant.showSignInDialog(MeditationAssistant.java:747)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at sh.ftp.rocketninelabs.meditationassistant.MediNET$4.run(MediNET.java:110)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at android.app.Activity.runOnUiThread(Activity.java:4644)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at sh.ftp.rocketninelabs.meditationassistant.MediNET.askToSignIn(MediNET.java:101)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at sh.ftp.rocketninelabs.meditationassistant.MainActivity.openMediNET(MainActivity.java:739)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at sh.ftp.rocketninelabs.meditationassistant.MainActivity.clickedStreak(MainActivity.java:280)
04-26 11:22:25.443: E/AndroidRuntime(24134):    ... 14 more
04-26 11:22:25.443: E/AndroidRuntime(24134): Caused by: java.lang.ClassNotFoundException: Could not find class: ListView
04-26 11:22:25.443: E/AndroidRuntime(24134):    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:607)
04-26 11:22:25.443: E/AndroidRuntime(24134):    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:448)
04-26 11:22:25.443: E/AndroidRuntime(24134):    ... 26 more
```

**Comment by Prototik** [comment]
Can't reproduce.
