### ISSUE TITLE
Cast exception @ Preference-SavedState

### ISSUE THREAD

**Issue by TheNephilim88** [Prototik/HoloEverywhere#430]
Hey,

I got those logcats from users of my app. Unfortunately I do not have any information about used phones/android-version, but maybe anyone has an idea why this is happening or maybe can give advice how to reproduce/fix this?

I currently can't reproduce this Exception...

<pre><code>java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mypackage/com.mypackage.preferences.Preference_Activity}: java.lang.ClassCastException: org.holoeverywhere.preference.Preference$BaseSavedState cannot be cast to org.holoeverywhere.preference.PreferenceScreen$SavedState
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2110)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
at android.app.ActivityThread.access$700(ActivityThread.java:140)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4921)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: org.holoeverywhere.preference.Preference$BaseSavedState cannot be cast to org.holoeverywhere.preference.PreferenceScreen$SavedState
at org.holoeverywhere.preference.PreferenceScreen.onRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.Preference.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.Preference.restoreHierarchyState(Unknown Source)
at org.holoeverywhere.preference.PreferenceActivity.onRestoreInstanceState(Unknown Source)
at android.app.Activity.performRestoreInstanceState(Activity.java:944)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1145)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2088)</code></pre>

**Comment by TheNephilim88** [comment]
With this fix I now get this kind of reports:

<pre><code>java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mypackage/com.mypackage.preferences.Preference_Activity}: java.lang.IllegalArgumentException: Wrong state class -- expecting Preference State
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2185)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2210)
at android.app.ActivityThread.access$600(ActivityThread.java:142)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1208)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4931)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: Wrong state class -- expecting Preference State
at org.holoeverywhere.preference.Preference.onRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.PreferenceScreen.onRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.Preference.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.Preference.restoreHierarchyState(Unknown Source)
at org.holoeverywhere.preference.PreferenceActivity.onRestoreInstanceState(Unknown Source)
at android.app.Activity.performRestoreInstanceState(Activity.java:900)
at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1130)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
... 11 more</code></pre>

**Comment by Prototik** [comment]
Show your preference layout.

**Comment by TheNephilim88** [comment]
Found out, that this has nothing to do with MY preference layout (of course, I can post it if really needed, but I dont think so).

This bug occurs when app has been killed in background (like when OS killed it due to low memory conditions). This can be forced and reproduced with the HoloEverywhere Demo as well:
1. Start HE-Demo
2. Go to Settings
3. Do sth. to kill app in background (tried it with going into Systemsettings -> Apps -> Running -> Cached Processes -> Holoeverywhere Demo -> Stop)
4. Go back to HE-Demo

-> Logcat shows same like I posted above

**Comment by httpdispatch** [comment]
+1 for the issue

**Comment by httpdispatch** [comment]
I'm receuved such crash report. Android 2.3.6

```
java.lang.IllegalArgumentException: Wrong state class -- expecting Preference State
    at org.holoeverywhere.preference.Preference.onRestoreInstanceState(Preference.java:576)
    at org.holoeverywhere.preference.PreferenceScreen.onRestoreInstanceState(PreferenceScreen.java:214)
    at org.holoeverywhere.preference.Preference.dispatchRestoreInstanceState(Preference.java:172)
    at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(PreferenceGroup.java:87)
    at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(PreferenceGroup.java:90)
    at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(PreferenceGroup.java:90)
    at org.holoeverywhere.preference.Preference.restoreHierarchyState(Preference.java:820)
    at org.holoeverywhere.preference.PreferenceFragment.onActivityCreated(PreferenceFragment.java:154)
    at com.trovebox.android.app.common.CommonPreferenceFragment.onActivityCreated(CommonPreferenceFragment.java:76)
    at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1468)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:931)
    at android.support.v4.app.FragmentManagerImpl.attachFragment(FragmentManager.java:1264)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:672)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:461)
    at com.trovebox.android.app.ui.adapter.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:157)
    at android.support.v4.view.ViewPager.populate(ViewPager.java:1011)
    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:522)
    at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:494)
    at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:486)
    at com.trovebox.android.app.NavigationHandlerFragment.selectTab(NavigationHandlerFragment.java:178)
    at com.trovebox.android.app.NavigationHandlerFragment$FragmentWrapper.selectFragment(NavigationHandlerFragment.java:117)
    at com.trovebox.android.app.NavigationHandlerFragment$FragmentWrapper.onClick(NavigationHandlerFragment.java:88)
    at android.view.View.performClick(View.java:2537)
    at android.view.View$PerformClick.run(View.java:9157)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3687)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    at dalvik.system.NativeStart.main(Native Method)
```
