### ISSUE TITLE
Android 2.x: Fragment.onPrepareOptionsMenu menu.findItem returns null in some cases

### ISSUE THREAD

**Issue by httpdispatch** [Prototik/HoloEverywhere#440]
I see crashes report from users with android version 2.x. NPE exception occurs when i try to access menu item retrieved via menu.findItem. I can't reproduce exact circumstances but most of all it happens when screen is rotated or something like this.

``` java
MenuItem refreshItem = menu.findItem(R.id.menu_refresh);
refreshItem.setVisible(isRefreshMenuVisible()); //NPE is here
```

I don't have any crashes reports from users with android 4.x. Do you have any ide why it happens?
One thing, menu invalidate is called in the handler.post

Full stack trace

```
java.lang.NullPointerException
    at com.trovebox.android.app.common.CommonRefreshableFragmentWithImageWorker.reinitMenu(CommonRefreshableFragmentWithImageWorker.java:68)
    at com.trovebox.android.app.common.CommonRefreshableFragmentWithImageWorker.onPrepareOptionsMenu(CommonRefreshableFragmentWithImageWorker.java:46)
    at android.support.v4.app._HoloFragment.onPrepareOptionsMenu(_HoloFragment.java:227)
    at android.support.v4.app.Fragment.performPrepareOptionsMenu(Fragment.java:1556)
    at android.support.v4.app.FragmentManagerImpl.dispatchPrepareOptionsMenu(FragmentManager.java:1964)
    at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:470)
    at org.holoeverywhere.app.Activity.access$8(Activity.java:1)
    at org.holoeverywhere.app.Activity$17.post(Activity.java:440)
    at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(IAddonBasicAttacher.java:81)
    at org.holoeverywhere.app.Activity.performAddonAction(Activity.java:528)
    at org.holoeverywhere.app.Activity.onPreparePanel(Activity.java:432)
    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:334)
    at com.android.internal.policy.impl.PhoneWindow.onKeyDownPanel(PhoneWindow.java:577)
    at com.android.internal.policy.impl.PhoneWindow.onKeyDown(PhoneWindow.java:1252)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1710)
    at android.view.ViewRoot.deliverKeyEventToViewHierarchy(ViewRoot.java:2699)
    at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2674)
    at android.view.ViewRoot.handleMessage(ViewRoot.java:1946)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3687)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Prototik** [comment]
How i can reproduce this?

**Comment by httpdispatch** [comment]
Unfortunately i don't know. But it is frequent and it is present only on Android 2.x. All i know is that onPrepareOptionsMenu is called in handler.post (maybe it occurs after activity is destroyed) but menu.findeItem returns null.

**Comment by Prototik** [comment]
Собсна, HoloEverywhere не лезет особо в ABS, и если включен аддон ABS - все on{Prepare,Create}OptionsMenu идут напрямую в ABS, если эти вызовы не перехватит вышестоящий аддон, ессно.
На данный момент вышестоящий аддон есть только один: Slider. Он НЕ перехватывает вызовы.

Не проблема HoloEverywhere.

**Comment by httpdispatch** [comment]
А с Fragment Lifecycle это может быть связано? Ну ситуация когда фрагмент уничтожен или view уничтожено, но он все равно реагирует на событие onPrepareOptionsMenu?
