### ISSUE TITLE
Demo crash

### ISSUE THREAD

**Issue by Gordi90** [Prototik/HoloEverywhere#457]
I've imported the HE to the Android Studio (as in the Wiki for intelliJ), the demo runs fine, until I choose "Settings". 

``` logcat
05-21 17:15:57.065      171-194/?                              E/: Dumpstate > /data/log/dumpstate_app_error
05-21 17:15:57.065  18650-18650/org.holoeverywhere.demo        E/AndroidRuntime: FATAL EXCEPTION: main
        java.lang.IllegalStateException: Dependency "null" not found for preference "null" (title: "null"
        at org.holoeverywhere.preference.Preference.registerDependency(Preference.java:793)
        at org.holoeverywhere.preference.Preference.onAttachedToActivity(Preference.java:484)
        at org.holoeverywhere.preference.PreferenceGroup.onAttachedToActivity(PreferenceGroup.java:176)
        at org.holoeverywhere.preference.PreferenceGroup.onAttachedToActivity(PreferenceGroup.java:176)
        at org.holoeverywhere.preference.PreferenceScreen.bind(PreferenceScreen.java:149)
        at org.holoeverywhere.preference.PreferenceFragment.bindPreferences(PreferenceFragment.java:86)
        at org.holoeverywhere.preference.PreferenceFragment.onActivityCreated(PreferenceFragment.java:145)
        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1468)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:931)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
        at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:461)
        at org.holoeverywhere.demo.fragments.MenuFragment$NavigationClickListener.onClick(MenuFragment.java:43)
        at android.view.View.performClick(View.java:2538)
        at android.view.View$PerformClick.run(View.java:9152)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:3687)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
        at dalvik.system.NativeStart.main(Native Method)
```

I had to check it, because, in my code, there is a PreferenceActivity, which worked before, but now there is a blank activity (without title):

``` xlm
<?xml version="1.0" encoding="utf-8"?>
<PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android"
                  xmlns:holo="http://schemas.android.com/apk/res-auto">

    <PreferenceScreen holo:title="@string/pref_category_title_personal">
        <intent android:action="com.xxxxxx.app.activities.PersonalPreferencesActivity"/>
    </PreferenceScreen>
    <PreferenceScreen holo:title="@string/pref_category_title_billing">
        <intent android:action="com.xxxxxx.app.activities.BillingPreferencesActivity"/>
    </PreferenceScreen>
    <PreferenceScreen holo:title="@string/pref_category_title_xxxxx">
        <intent android:action="com.xxxxxx.app.activities.xxxxxxxPreferencesActivity"/>
    </PreferenceScreen>

</PreferenceScreen>
```

**Comment by Gordi90** [comment]
I tried to revert, but had no idea how much. FIrst try: "Update to ABS 4.3.0" and it works.

**Comment by Prototik** [comment]
For `<intent>` and `<category>` now you should use holo: namespace, like for other nodes in layout.

Demo builded via maven works fine, it's problems in your build environment.
