### ISSUE TITLE
android.content.ActivityNotFoundException: No Activity found to handle Intent {  }

### ISSUE THREAD

**Issue by Zeliret** [Prototik/HoloEverywhere#461]
Обновился до 1.6 версии и обнаружил такую проблему с преференсами.

Так у меня в xml задан экран настроек "О приложении". При клике на aboutChangelog элемент должен произойти запуск активити. 

``` xml
<PreferenceScreen xmlns:holo="http://schemas.android.com/apk/res-auto"
                  xmlns:android="http://schemas.android.com/apk/res/android">
    <Preference holo:title="@string/settingsAppVersionTitle"
                holo:key="aboutAppVersion" />
    <Preference holo:title="@string/settingsAndroidVersionTitle"
                holo:key="aboutAndroidVersion" />
    <Preference holo:title="@string/settingsChangelog"
                holo:key="aboutChangelog">
        <intent android:action="mega.onicon.activity.ChangelogActivity" />
    </Preference>
</PreferenceScreen>
```

Раньше так и работало, а теперь выскакивает исключение.

``` java
ERROR/AndroidRuntime(23998): FATAL EXCEPTION: main
        android.content.ActivityNotFoundException: No Activity found to handle Intent {  }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1409)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1379)
        at android.app.Activity.startActivityForResult(Activity.java:2827)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:817)
        at android.support.v4.app._HoloActivity.superStartActivity(_HoloActivity.java:675)
        at android.support.v4.app._HoloActivity.startActivityForResult(_HoloActivity.java:653)
        at android.support.v4.app._HoloActivity.startActivity(_HoloActivity.java:639)
        at android.support.v4.app._HoloActivity.startActivity(_HoloActivity.java:634)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:258)
        at org.holoeverywhere.preference.Preference.performClick(Preference.java:619)
        at org.holoeverywhere.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:217)
        at android.widget.AdapterView.performItemClick(AdapterView.java:284)
        at android.widget.ListView.performItemClick(ListView.java:3763)
        at org.holoeverywhere.widget.ListView.performItemClick(ListView.java:681)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:1918)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:3687)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Prototik** [comment]
`<intent>` и `<extras>` теперь используют holo: префикс, не android:.

**Comment by Zeliret** [comment]
Спасибо :)) Я так и подумал, даже поменял, но не стал компилировать :)
