### ISSUE TITLE
Intermittant crash when starting app.. Its like the Application Object is null. isDisableContextMenu  isDebugMode

### ISSUE THREAD

**Issue by bob9** [Prototik/HoloEverywhere#467]
I attempted to wrap "org.holoeverywhere.app.Application$Config.isDisableContextMenu" method call in a if null then return false. The result was the same error intermittently from a different method call 
at org.holoeverywhere.app.Application$Config.isDebugMode. I have included the crash stack trace below of the 2 crashes..

If anyone has any idea how to fix this issue, I would be very appreciative.

Thanks
## bob9

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xyz.mrwongs/com.xyz.ui.MainActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
at android.app.ActivityThread.access$600(ActivityThread.java:140)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4898)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.holoeverywhere.app.Application$Config.isDisableContextMenu(Application.java:105)
at com.actionbarsherlock.internal.view.menu.ContextMenuDecorView.prepareDecorView(ContextMenuDecorView.java:72)
at android.support.v4.app._HoloActivity.prepareDecorView(_HoloActivity.java:327)
at org.holoeverywhere.app.Activity.setContentView(Activity.java:260)
at com.slidingmenu.lib.app.SlidingFragmentActivity.setContentView(SlidingFragmentActivity.java:75)
at com.slidingmenu.lib.app.SlidingFragmentActivity.setContentView(SlidingFragmentActivity.java:67)
at com.slidingmenu.lib.app.SlidingFragmentActivity.setContentView(SlidingFragmentActivity.java:59)
at com.xyz.ui.MainActivity.onCreate(MainActivity.java:134)
at android.app.Activity.performCreate(Activity.java:5184)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
```

**Comment by Prototik** [comment]
Update library, Application.Config doesn't exists since 1.4.
