### ISSUE TITLE
ProgessBar SavedState causes crash when unmarshaling.

### ISSUE THREAD

**Issue by kkocel** [Prototik/HoloEverywhere#470]
Hello,
I've got something like this:

```
05-29 09:46:48.886: E/AndroidRuntime(13596): FATAL EXCEPTION: main
05-29 09:46:48.886: E/AndroidRuntime(13596): android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.holoeverywhere.widget.ProgressBar$SavedState
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.os.Parcel.readParcelable(Parcel.java:2077)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.os.Parcel.readValue(Parcel.java:1965)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.os.Parcel.readSparseArrayInternal(Parcel.java:2255)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.os.Parcel.readSparseArray(Parcel.java:1687)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.os.Parcel.readValue(Parcel.java:2022)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.os.Parcel.readMapInternal(Parcel.java:2226)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.os.Bundle.unparcel(Bundle.java:223)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.os.Bundle.getSparseParcelableArray(Bundle.java:1240)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:845)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:807)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.support.v4.app.Fragment.setUserVisibleHint(Fragment.java:801)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.support.v4.app.FragmentStatePagerAdapter.setPrimaryItem(FragmentStatePagerAdapter.java:152)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.support.v4.view.ViewPager.populate(ViewPager.java:1062)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.support.v4.view.ViewPager.populate(ViewPager.java:911)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1432)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.View.measure(View.java:15518)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at org.holoeverywhere.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:601)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at org.holoeverywhere.widget.LinearLayout.measureVertical(LinearLayout.java:920)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at org.holoeverywhere.widget.LinearLayout.onMeasure(LinearLayout.java:1112)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.View.measure(View.java:15518)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1217)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.widget.ScrollView.onMeasure(ScrollView.java:321)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.View.measure(View.java:15518)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:681)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.View.measure(View.java:15518)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.View.measure(View.java:15518)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.View.measure(View.java:15518)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.View.measure(View.java:15518)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at org.holoeverywhere.internal.WindowDecorView.onMeasure(WindowDecorView.java:118)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.View.measure(View.java:15518)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.View.measure(View.java:15518)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at org.holoeverywhere.widget.LinearLayout.measureVertical(LinearLayout.java:1021)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at org.holoeverywhere.widget.LinearLayout.onMeasure(LinearLayout.java:1112)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.View.measure(View.java:15518)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4825)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2176)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.View.measure(View.java:15518)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1874)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1089)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1265)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
05-29 09:46:48.886: E/AndroidRuntime(13596):    at android.view.Choreographer.doFrame(Choreographer.java:532)
```

**Comment by Prototik** [comment]
Android bug.
In FragmentStatePagerAdapter#getItem you can manually load this class:

``` java
Class.forName(ProgressBar.SavedState.class.getName(), true, context.getClassLoader())
```

**Comment by httpdispatch** [comment]
Maybe it happens because of SavedState is protected not public?

**Comment by Prototik** [comment]
Original code of ProgressBar use a package visibility.
One moment.

**Comment by Prototik** [comment]
Fixed :D

No, it's /really/ android bug.
Any application have a two classloaders:
- System classloader. This classloader can load classes only from /system/framework folder. eg `android.*`.
- Application classloader. This can load classes from application apk. Activities, services and all others classes from apk. This classloader extend system classloader, and if use it everywhere - all ok.  
  FragmentManager doesn't set any classloader for savedinstance bundle, thats it's use system classloader, which simply don't know about apk anything.

**Comment by kkocel** [comment]
@Prototik You're right - this is kind of Android problem, still I need to access this class to load it..

**Comment by Prototik** [comment]
But we are use support library - potential, crashes in restore instance state (activity/fragment) /can/ be fixed, but...
Hardly.

**Comment by kkocel** [comment]
Ok, as a workaround i created org.holoeverywhere.widget package, moved my adapter there and loaded class in getItem method.

**Comment by Prototik** [comment]
You can load class by name like this:

``` java
Class.forName("org.holoeverywhere.widget.ProgressBar$SavedState", true, context.getClassLoader())
```

without moving in org.holoeverywhere.widget package.

**Comment by Prototik** [comment]
Fixed in latest commit... Damn...

**Comment by ljarka** [comment]
This fix not resolves issue.

```
    0android.os.BadParcelableException: ClassNotFoundException when unmarshalling:  
org.holoeverywhere.widget.ProgressBar$SavedState 
    1at android.os.Parcel.readParcelable(Parcel.java:1971)
    2at android.os.Parcel.readValue(Parcel.java:1859)
    3at android.os.Parcel.readSparseArrayInternal(Parcel.java:2128)
    4at android.os.Parcel.readSparseArray(Parcel.java:1581)
    5at android.os.Parcel.readValue(Parcel.java:1916)
    6at android.os.Parcel.readMapInternal(Parcel.java:2099)
    7at android.os.Bundle.unparcel(Bundle.java:223)
    8at android.os.Bundle.getSparseParcelableArray(Bundle.java:1225)
    9at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
    10at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(Unknown Source)
    11at android.support.v4.app.Fragment.setUserVisibleHint(Unknown Source)
    12at android.support.v4.app.FragmentStatePagerAdapter.setPrimaryItem(Unknown Source)
```

**Comment by Prototik** [comment]
@LukaszJarka anyway it's android bug. And i cannot fix it /fully/ without patching of support library. I don't want.

Also i see you don't use `org.holoeverywhere.app.Fragment`. Fix placed in it.

**Comment by kkocel** [comment]
Ok, then but which `FragmentManager` we should use to return `org.holoeverywhere.app.Fragment`?

**Comment by Prototik** [comment]
@kkocel mm, sorry? You just should extends fragments from `org.holoeverywhere.app.Fragment` (or `ListFragment`, or something else). FragmentManager always is standard `FragmentManagerImpl`.

**Comment by kkocel** [comment]
Ok, I figured it out. It turned that we extended normal `Fragment`. Anyway большое спасибо!

**Comment by kkocel** [comment]
Unfortunately this bug still occurs.

Now I have situation when I have an `FragmentStatePagerAdapter` with items, then I'm notifying adapter that data has changed. New views contain `ProgressBar` from HE

```
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: org.holoeverywhere.widget.ProgressBar$SavedState
at android.os.Parcel.readParcelable(Parcel.java:1966)
at android.os.Parcel.readValue(Parcel.java:1854)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2123)
at android.os.Parcel.readSparseArray(Parcel.java:1576)
at android.os.Parcel.readValue(Parcel.java:1911)
at android.os.Parcel.readMapInternal(Parcel.java:2094)
at android.os.Bundle.unparcel(Bundle.java:223)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1225)
at android.support.v4.app.FragmentManagerImpl.void moveToState(android.support.v4.app.Fragment,int,int,int,boolean)(Unknown Source)
at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at android.support.v4.app.FragmentManagerImpl.void moveToState(android.support.v4.app.Fragment,int,int,int,boolean)(Unknown Source)
at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at android.support.v4.app.BackStackRecord.void run()(Unknown Source)
at android.support.v4.app.FragmentManagerImpl.boolean execPendingActions()(Unknown Source)
at android.support.v4.app.FragmentManagerImpl.boolean executePendingTransactions()(Unknown Source)
at android.support.v4.app.FragmentStatePagerAdapter.void finishUpdate(android.view.ViewGroup)(Unknown Source)
at android.support.v4.view.ViewPager.void setCurrentItem(int,boolean)(Unknown Source)
at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at android.support.v4.view.ViewPager.void setCurrentItem(int,boolean)(Unknown Source)
at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at android.support.v4.view.ViewPager.void setCurrentItem(int,boolean)(Unknown Source)
at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at dalvik.system.NativeStart.main(Native Method)at android.support.v4.view.ViewPager.void dataSetChanged()(Unknown Source)
at android.support.v4.view.ViewPager$PagerObserver.void onChanged()(Unknown Source)
at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:35)
at android.support.v4.view.PagerAdapter.void notifyDataSetChanged()(Unknown Source)
```

**Comment by Prototik** [comment]
Well, i can /totally/ fix this issue, but anyway it's one bike more in this bike-collection-library :D
One moment.

**Comment by Prototik** [comment]
Damn, i write workaround for this, but i don't want see this terrible code in library. I'll write to android devs mail list and provide patch for support library instead this.

**Comment by Prototik** [comment]
Wow i'm already find a patch by Steve Lhomme, but it's in [review stage](https://android-review.googlesource.com/#/c/40760/) :(
