### ISSUE TITLE
AlertDialog.create() crashes with  "Error inflating class <unknown>"

### ISSUE THREAD

**Issue by judepereira** [Prototik/HoloEverywhere#499]
The moment I create my AlertDialog, the activity force closes with the following error. I've imported all views from org.holoeverywhere. 

```
   android.view.InflateException: Binary XML file line #8: Error inflating class <unknown>
    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:376)
    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:588)
    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:438)
    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:725)
    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:728)
    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:532)
    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:482)
    at org.holoeverywhere.app.Dialog.requestDecorView(Dialog.java:155)
    at org.holoeverywhere.app.Dialog.setContentView(Dialog.java:170)
    at org.holoeverywhere.app.AlertDialog.installDecorView(AlertDialog.java:405)
    at org.holoeverywhere.internal.AlertController.installContent(AlertController.java:474)
    at org.holoeverywhere.app.AlertDialog.onCreate(AlertDialog.java:411)
    at android.app.Dialog.dispatchOnCreate(Dialog.java:307)
    at android.app.Dialog.show(Dialog.java:225)
    at com.judepereira.android.bankatmlocator.ShowNearbyOrSearchResultsActivity$1.onItemClick(ShowNearbyOrSearchResultsActivity.java:74)
    at android.widget.AdapterView.performItemClick(AdapterView.java:284)
    at android.widget.ListView.performItemClick(ListView.java:3513)
    at org.holoeverywhere.widget.ListView.performItemClick(ListView.java:688)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:1812)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:123)
    at android.app.ActivityThread.main(ActivityThread.java:3683)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
    at dalvik.system.NativeStart.main(Native Method)
    Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.constructNative(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:352)
    ... 27 more
    Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010065 a=-1}
    at android.content.res.Resources.loadDrawable(Resources.java:1681)
    at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
    at android.view.View.<init>(View.java:1951)
    at android.view.View.<init>(View.java:1899)
    ... 30 more
```

What's causing this?

**Comment by restorer** [comment]
You also must inherit you application class from holoeverywhere's application and you must use holoeverywhere's theme for activity.

**Comment by judepereira** [comment]
I have done both. All my imports are from holoeverywhere.

## 

Jude Pereira
judepereira@7terminals.com | +91 800 731 7529

**Comment by lukrop** [comment]
I have the same Problem using a `DatePickerDialog` with it's `show()` method. Interesstingly `TimePickerDialog` works with it's `show()` method

``` java
btnFromDate.setOnClickListener(new View.OnClickListener() {
    public void onClick(View v) {
        DatePickerDialog fromDatePicker = new DatePickerDialog(getSupportActivity(),
        R.style.AppTheme, mFromDateSetListener, mFromYear, mFromMonth, mFromDay);
        fromDatePicker.show();
    }
});

btnFromTime.setOnClickListener(new View.OnClickListener() {
    public void onClick(View v) {
        TimePickerDialog fromTimePicker = new TimePickerDialog(getSupportActivity(),
        mFromTimeSetListener, mFromHour, mFromMinute, true);
        fromTimePicker.show();
    }
});
```

The TimePickerDialog works, the DatePickerDialog doesn't.

**Comment by judepereira** [comment]
For me, I changed getApplicationContext() to this, the main activity
itself, and it worked well. Can you try this fix?

## 

Jude Pereira
judepereira@7terminals.com | +91 800 731 7529

**Comment by lukrop** [comment]
I just fixed it by supplying `AlertDialog.THEME_HOLO_LIGHT` instead of `R.style.AppTheme`.

**Comment by Prototik** [comment]
Wow. Two rules:
- DO NOT USE APPLICATION CONTEXT FOR DIALOGS! NEVER!
- AlertDialog doesn't accept activity theme. You should provide something from Holo.Theme.Dialog.Alert[.Light] for it.
