### ISSUE TITLE
Not find roboto_light font

### ISSUE THREAD

**Issue by crossle** [Prototik/HoloEverywhere#500]
```
 29813         AndroidRuntime  E  Caused by: java.lang.IllegalStateException: Could not find font in raw resources: roboto_light
 29813         AndroidRuntime  E    at org.holoeverywhere.FontLoader$RawLazyFont.loadTypeface(FontLoader.java:187)
 29813         AndroidRuntime  E    at org.holoeverywhere.FontLoader$Font.getTypeface(FontLoader.java:52)
 29813         AndroidRuntime  E    at org.holoeverywhere.FontLoader$FontCollector.getTypeface(FontLoader.java:81)
 29813         AndroidRuntime  E    at org.holoeverywhere.FontLoader.applyInternal(FontLoader.java:296)
 29813         AndroidRuntime  E    at org.holoeverywhere.FontLoader.apply(FontLoader.java:273)
 29813         AndroidRuntime  E    at org.holoeverywhere.FontLoader.applyDefaultFont(FontLoader.java:278)
 29813         AndroidRuntime  E    at org.holoeverywhere.widget.TextView.setFontStyle(TextView.java:109)
 29813         AndroidRuntime  E    at org.holoeverywhere.widget.TextView.setFontStyle(TextView.java:182)
 29813         AndroidRuntime  E    at org.holoeverywhere.widget.TextView.setTextAppearance(TextView.java:151)
 29813         AndroidRuntime  E    at org.holoeverywhere.widget.TextView.construct(TextView.java:34)
 29813         AndroidRuntime  E    at org.holoeverywhere.widget.TextView.<init>(TextView.java:166)
 29813         AndroidRuntime  E    at org.holoeverywhere.widget.TextView.<init>(TextView.java:161)

```

**Comment by Prototik** [comment]
You should copy fonts from `demo/res/raw` folder into your project. Article about FontLoader will be after next release iteration.

**Comment by jjalonso** [comment]
Where i can find the doc?

Thanks.

**Comment by Lakedaemon** [comment]
I got that same issue with plugin 2.16 and holoeverywhere snapshot, from a user with a HTC 3D evo, with Android 4.4 (a custom rom ? ) and a IOS7 theme

Is it my fault ? Should i copy  the font ? ...I'll go and look at the doc for FontLoader

Generic Evo 3D CDMA htc_shooter with customTheme    com.ibocharov.themechooser.ios7(iOS7)   

java.lang.RuntimeException
:Unable to create application org.lakedaemon.d.Application
:java.lang.IllegalStateException
:Could not find font in raw resources
:roboto_light
at  android.app.ActivityThread.handleBindApplication (ActivityThread.java : 4409)
at  android.app.ActivityThread.access$1500 (ActivityThread.java : 145)
at  android.app.ActivityThread$H.handleMessage (ActivityThread.java : 1266)
at  android.os.Handler.dispatchMessage (Handler.java : 102)
at  android.os.Looper.loop (Looper.java : 136)
at  android.app.ActivityThread.main (ActivityThread.java : 5078)
at  java.lang.reflect.Method.invokeNativeNative Method
at  java.lang.reflect.Method.invoke (Method.java : 515)
at  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java : 781)
at  com.android.internal.os.ZygoteInit.main (ZygoteInit.java : 597)
at  dalvik.system.NativeStart.mainNative Method
Caused by : java.lang.IllegalStateException: Could not find font in raw resources: roboto_light
at  org.holoeverywhere.FontLoader$RawLazyFont.setRawResourceId (FontLoader.java : 575)
at  org.holoeverywhere.FontLoader$RawLazyFont.loadTypeface (FontLoader.java : 568)
at  org.holoeverywhere.FontLoader$Font.getTypeface (FontLoader.java : 283)
at  org.holoeverywhere.FontLoader$FontCollector.getTypeface (FontLoader.java : 368)
at  org.holoeverywhere.FontLoader$FontCollector.getTypeface (FontLoader.java : 400)
at  org.holoeverywhere.FontLoader.applyInternal (FontLoader.java : 154)
at  org.holoeverywhere.FontLoader.apply (FontLoader.java : 128)
at  org.holoeverywhere.FontLoader.applyDefaultFont (FontLoader.java : 134)
at  org.holoeverywhere.widget.TextView.setFontStyle (TextView.java : 91)
at  org.holoeverywhere.widget.TextView.setFontStyle (TextView.java : 156)
at  org.holoeverywhere.widget.TextView.setTextAppearance (TextView.java : 133)
at  org.holoeverywhere.widget.TextView.setTextAppearance (TextView.java : 101)
at  org.holoeverywhere.widget.TextView.construct (TextView.java : 38)
at  org.holoeverywhere.widget.TextView. (TextView.java : 30)
at  org.holoeverywhere.widget.TextView. (TextView.java : 25)
at  org.holoeverywhere.widget.TextView. (TextView.java : 21)
at  org.holoeverywhere.widget.Toast.makeText (Toast.java : 18)
at  org.holoeverywhere.widget.Toast.makeText (Toast.java : 28)
at  org.lakedaemon.android.App.guardPreferences (App.kt : 62)
at  org.lakedaemon.d.Application.onCreate (D.kt : 93)
at  android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java : 1007)
at  android.app.ActivityThread.handleBindApplication (ActivityThread.java : 4406))
...  10 more
java.lang.IllegalStateException: Could not find font in raw resources: roboto_light
at  org.holoeverywhere.FontLoader$RawLazyFont.setRawResourceId (FontLoader.java : 575)
at  org.holoeverywhere.FontLoader$RawLazyFont.loadTypeface (FontLoader.java : 568)
at  org.holoeverywhere.FontLoader$Font.getTypeface (FontLoader.java : 283)
at  org.holoeverywhere.FontLoader$FontCollector.getTypeface (FontLoader.java : 368)
at  org.holoeverywhere.FontLoader$FontCollector.getTypeface (FontLoader.java : 400)
at  org.holoeverywhere.FontLoader.applyInternal (FontLoader.java : 154)
at  org.holoeverywhere.FontLoader.apply (FontLoader.java : 128)
at  org.holoeverywhere.FontLoader.applyDefaultFont (FontLoader.java : 134)
at  org.holoeverywhere.widget.TextView.setFontStyle (TextView.java : 91)
at  org.holoeverywhere.widget.TextView.setFontStyle (TextView.java : 156)
at  org.holoeverywhere.widget.TextView.setTextAppearance (TextView.java : 133)
at  org.holoeverywhere.widget.TextView.setTextAppearance (TextView.java : 101)
at  org.holoeverywhere.widget.TextView.construct (TextView.java : 38)
at  org.holoeverywhere.widget.TextView. (TextView.java : 30)
at  org.holoeverywhere.widget.TextView. (TextView.java : 25)
at  org.holoeverywhere.widget.TextView. (TextView.java : 21)
at  org.holoeverywhere.widget.Toast.makeText (Toast.java : 18)
at  org.holoeverywhere.widget.Toast.makeText (Toast.java : 28)
at  org.lakedaemon.android.App.guardPreferences (App.kt : 62)
at  org.lakedaemon.d.Application.onCreate (D.kt : 93)
at  android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java : 1007)
at  android.app.ActivityThread.handleBindApplication (ActivityThread.java : 4406)
at  android.app.ActivityThread.access$1500 (ActivityThread.java : 145)
at  android.app.ActivityThread$H.handleMessage (ActivityThread.java : 1266)
at  android.os.Handler.dispatchMessage (Handler.java : 102)
at  android.os.Looper.loop (Looper.java : 136)
at  android.app.ActivityThread.main (ActivityThread.java : 5078)
at  java.lang.reflect.Method.invokeNativeNative Method
at  java.lang.reflect.Method.invoke (Method.java : 515)
at  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java : 781)
at  com.android.internal.os.ZygoteInit.main (ZygoteInit.java : 597)
at  dalvik.system.NativeStart.mainNative Method
