### ISSUE TITLE
Error inflating class org.holoeverywhere.widget.SeekBar

### ISSUE THREAD

**Issue by otro678** [Prototik/HoloEverywhere#524]
There already was issue about this, but it was closed without solution - https://github.com/Prototik/HoloEverywhere/issues/342

I'm not having this issue on Galaxy Nexus, Nexus 7, Nexus 10, HTC Wildfire S and HTC Desire, but I have some crash logs from Galaxy S III, Galaxy Note II and HTC One. I don't think this is something related to build settings, since this is issue that happens only sometimes on particular devices. 
Here is crash log:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sergeyotro.sharpsquare/com.sergeyotro.sharpsquare.ui.DisplayingActivity}: android.view.InflateException: Binary XML file line #109: Error inflating class org.holoeverywhere.widget.SeekBar
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2249)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
at android.app.ActivityThread.access$700(ActivityThread.java:154)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5306)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #109: Error inflating class org.holoeverywhere.widget.SeekBar
at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:376)
at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:588)
at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:438)
at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:725)
at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:728)
at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:532)
at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:482)
at android.support.v4.app._HoloActivity.requestDecorView(_HoloActivity.java:573)
at android.support.v4.app._HoloActivity.setContentView(_HoloActivity.java:597)
at com.sergeyotro.sharpsquare.ui.DisplayingActivity.onCreate(DisplayingActivity.java:95)
at android.app.Activity.performCreate(Activity.java:5255)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2213)
... 11 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:352)
... 23 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/scrubber_progress_horizontal_holo_light.xml from drawable resource ID #0x108068d
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:138)
at org.holoeverywhere.drawable.DrawableCompat.getDrawable(DrawableCompat.java:113)
at org.holoeverywhere.widget.ProgressBar.<init>(ProgressBar.java:246)
at org.holoeverywhere.widget.ProgressBar.<init>(ProgressBar.java:203)
at org.holoeverywhere.widget.AbsSeekBar.<init>(AbsSeekBar.java:42)
at org.holoeverywhere.widget.SeekBar.<init>(SeekBar.java:30)
at org.holoeverywhere.widget.SeekBar.<init>(SeekBar.java:26)
... 26 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi/scrubber_track_holo_light.9.png from drawable resource ID #0x1080690
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:152)
at org.holoeverywhere.drawable.DrawableCompat.getDrawable(DrawableCompat.java:107)
at org.holoeverywhere.drawable.LayerDrawable.inflate(LayerDrawable.java:368)
at org.holoeverywhere.drawable.DrawableCompat.createFromXmlInner(DrawableCompat.java:87)
at org.holoeverywhere.drawable.DrawableCompat.createFromXml(DrawableCompat.java:63)
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:135)
... 32 more
Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
at android.content.res.AssetManager.openNonAssetFdNative(Native Method)
at android.content.res.AssetManager.openNonAssetFd(AssetManager.java:428)
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:147)
... 37 more
```

**Comment by Prototik** [comment]
Not library bug. Definitely. Vendor or your issue. Seriously. And i don't want to find way how to fix this crap.
