### ISSUE TITLE
Null pointer when adding a HeaderView to a ListFragment on 2.3.6

### ISSUE THREAD

**Issue by ChrisDavis8** [Prototik/HoloEverywhere#526]
Null pointer exception on calling ListFragment.getListView().addHeaderView()
It seems to call onPrepareView() twice the second time the view is null.
This is on a CHOICE_MODE_MULTIPLE_MODAL listfragment
The same code runs fine on 4.x

07-01 22:14:20.070: E/AndroidRuntime(1594): FATAL EXCEPTION: main
07-01 22:14:20.070: E/AndroidRuntime(1594): java.lang.NullPointerException
07-01 22:14:20.070: E/AndroidRuntime(1594):     at org.holoeverywhere.widget.ListView.onPrepareView(ListView.java:557)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at org.holoeverywhere.widget.ListView$1.onPrepareView(ListView.java:207)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at org.holoeverywhere.widget.ListAdapterWrapper.onPrepareView(ListAdapterWrapper.java:119)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at org.holoeverywhere.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:136)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.AbsListView.obtainView(AbsListView.java:1409)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.ListView.makeAndAddView(ListView.java:1745)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.ListView.fillDown(ListView.java:670)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.ListView.fillSpecific(ListView.java:1302)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.ListView.layoutChildren(ListView.java:1576)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.AbsListView.onLayout(AbsListView.java:1260)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at org.holoeverywhere.widget.ListView.onLayout(ListView.java:548)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1254)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1130)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.LinearLayout.onLayout(LinearLayout.java:1047)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1254)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1130)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.LinearLayout.onLayout(LinearLayout.java:1047)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.View.layout(View.java:7175)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.ViewRoot.performTraversals(ViewRoot.java:1140)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.os.Handler.dispatchMessage(Handler.java:99)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.os.Looper.loop(Looper.java:130)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at android.app.ActivityThread.main(ActivityThread.java:3683)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at java.lang.reflect.Method.invokeNative(Native Method)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at java.lang.reflect.Method.invoke(Method.java:507)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
07-01 22:14:20.070: E/AndroidRuntime(1594):     at dalvik.system.NativeStart.main(Native Method)

**Comment by ChrisDavis8** [comment]
After some more digging it seems to be calling getView() on my Adapter for position 0 passing in the header view layout as the convertview instead of the first item view

**Comment by ChrisDavis8** [comment]
Damn sorry, it turned out to be my Adapter not returning a view due to not finding the view holder on the convertview
