### ISSUE TITLE
ProgressDialog bug

### ISSUE THREAD

**Issue by agrebnev** [Prototik/HoloEverywhere#533]
07-09 13:39:50.781: E/AndroidRuntime(11795): Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class <unknown>
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:376)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:588)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:438)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:725)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:728)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:532)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:482)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.app.Dialog.requestDecorView(Dialog.java:155)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.app.Dialog.setContentView(Dialog.java:170)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.app.AlertDialog.installDecorView(AlertDialog.java:405)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.internal.AlertController.installContent(AlertController.java:474)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.app.AlertDialog.onCreate(AlertDialog.java:411)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at org.holoeverywhere.app.ProgressDialog.onCreate(ProgressDialog.java:213)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at android.app.Dialog.dispatchOnCreate(Dialog.java:339)
07-09 13:39:50.781: E/AndroidRuntime(11795):    at android.app.Dialog.show(Dialog.java:249)

**Comment by agrebnev** [comment]
It look like i put wrong context in ProcessDialog constructor. I put getSupportApplication instead getSupportActivity. However in any case the error should be more clear.
