### ISSUE TITLE
ListView setSelector(int ResID)

### ISSUE THREAD

**Issue by ghost** [Prototik/HoloEverywhere#534]
When i try to set a selector using the R.drawable.abs__list_selector_holo_light provided by ABS, the app crashes with a ResourceNotFound error.

On removing the setSelector from the ListView widget provided by HoloEverywhere, the app functions correctly.

**Comment by kidinov** [comment]
I see the same trouble. Stack trace: 
E/AndroidRuntime: FATAL EXCEPTION: main
        android.content.res.Resources$NotFoundException: File res/drawable/activated_background.xml from drawable resource ID #0x7f020131
        at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:138)
        at org.holoeverywhere.drawable.DrawableCompat.getDrawable(DrawableCompat.java:107)
        at org.holoeverywhere.widget.ListView.setSelector(ListView.java:954)
        at org.kidinov.unixadmin.FileManagerFragment.init(FileManagerFragment.java:211)
        at org.kidinov.unixadmin.FileManagerFragment.go(FileManagerFragment.java:183)
        at org.kidinov.unixadmin.FileManagerFragment.onResume(FileManagerFragment.java:97)
        at android.support.v4.app.Fragment.performResume(Fragment.java:1503)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:948)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1089)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1445)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:429)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:3683)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1c/d=0x0 a=2 r=0x7f090011}
        at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:128)
        at org.holoeverywhere.drawable.DrawableCompat.getDrawable(DrawableCompat.java:107)
        at org.holoeverywhere.drawable.StateListDrawable.inflate(StateListDrawable.java:194)
        at org.holoeverywhere.drawable.DrawableCompat.createFromXmlInner(DrawableCompat.java:87)
        at org.holoeverywhere.drawable.DrawableCompat.createFromXml(DrawableCompat.java:63)
        at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:135)
But APK contains this file.

**Comment by Prototik** [comment]
In DrawableCompat was added fallback mode, this issue should fixed.
