### ISSUE TITLE
IndexOutOfBoundsException in HeaderViewListAdapter.isEnabled

### ISSUE THREAD

**Issue by kkocel** [Prototik/HoloEverywhere#539]
I've came across such bug. 

``` java
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
at java.util.ArrayList.get(ArrayList.java:304)
at org.holoeverywhere.widget.HeaderViewListAdapter.isEnabled(Unknown Source)
at android.widget.ListView.dispatchDraw(ListView.java:3193)
at android.view.View.draw(View.java:13762)
at android.widget.AbsListView.draw(AbsListView.java:4211)
at org.holoeverywhere.widget.ListView.draw(Unknown Source)
at android.view.View.getDisplayList(View.java:12710)
```

**Comment by Prototik** [comment]
Cannot reproduce. I think you call isEnabled before calling notifyDataSetChanged, but after removing some rows from adapter.
