### ISSUE TITLE
ClassCastException: org.holoeverywhere.preference.Preference$BaseSavedState cannot be cast to org.holoeverywhere.preference.PreferenceScreen$SavedState

### ISSUE THREAD

**Issue by BraisGabin** [Prototik/HoloEverywhere#540]
I received this at my Google Play publisher console:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ragnabase.mvp/com.ragnabase.mvp.SettingsActivity}: java.lang.ClassCastException: org.holoeverywhere.preference.Preference$BaseSavedState cannot be cast to org.holoeverywhere.preference.PreferenceScreen$SavedState
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
at android.app.ActivityThread.access$600(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: org.holoeverywhere.preference.Preference$BaseSavedState cannot be cast to org.holoeverywhere.preference.PreferenceScreen$SavedState
at org.holoeverywhere.preference.PreferenceScreen.onRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.Preference.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(Unknown Source)
at org.holoeverywhere.preference.Preference.restoreHierarchyState(Unknown Source)
at org.holoeverywhere.preference.PreferenceFragment.onActivityCreated(Unknown Source)
at android.support.v4.app.Fragment.performActivityCreated(Unknown Source)
at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
                                              moveToState
                                              moveToState
                                              moveToState
at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
                                              moveToState
                                              moveToState
                                              moveToState
at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
                                              moveToState
                                              moveToState
                                              moveToState
at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(Unknown Source)
at android.support.v4.app.FragmentActivity.onStart(Unknown Source)
at org.holoeverywhere.app.Activity.onStart(Unknown Source)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1164)
at android.app.Activity.performStart(Activity.java:5114)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
... 11 more
```

I used ddaec1186a1a160fa7b6b17cd97178fc610c071b at this app version. I only have one of this and I don't know how to reproduce it. If it helps you to find a bug, great. If not, simply close this issue.

**Comment by Prototik** [comment]
_Very outdated_

I also don't know how i can reproduce it, and i can not find other similar stacktraces, close it.
