### ISSUE TITLE
InflateException for seekbar widget

### ISSUE THREAD

**Issue by ChrisDavis8** [Prototik/HoloEverywhere#545]
Hi I am getting bug reports of the following exception affecting some users, I have checked for the resource and its there and it is fine on my own devices. Any suggestions?

android.view.InflateException: Binary XML file line #131: Error inflating class org.holoeverywhere.widget.SeekBar
at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:382)
at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:594)
at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:444)
at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:731)
at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:538)
at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:488)
at com.hullomail.messaging.android.holo.messagelist.HmMessageDetailFragment.onCreateView(HmMessageDetailFragment.java:161)
at android.support.v4.app._HoloFragment.onCreateView(_HoloFragment.java:173)
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1460)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:429)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4898)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:358)
... 22 more Caused by: android.content.res.Resources$NotFoundException: File res/drawable/scrubber_progress_horizontal_holo_light.xml from drawable resource ID #0x1080653
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:138)
at org.holoeverywhere.drawable.DrawableCompat.getDrawable(DrawableCompat.java:113)
at org.holoeverywhere.widget.ProgressBar.(ProgressBar.java:246)
at org.holoeverywhere.widget.ProgressBar.(ProgressBar.java:203)
at org.holoeverywhere.widget.AbsSeekBar.(AbsSeekBar.java:42)
at org.holoeverywhere.widget.SeekBar.(SeekBar.java:30)
at org.holoeverywhere.widget.SeekBar.(SeekBar.java:26)
... 25 more Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi/scrubber_track_holo_light.9.png from drawable resource ID #0x1080656
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:152)
at org.holoeverywhere.drawable.DrawableCompat.getDrawable(DrawableCompat.java:107)
at org.holoeverywhere.drawable.LayerDrawable.inflate(LayerDrawable.java:368)
at org.holoeverywhere.drawable.DrawableCompat.createFromXmlInner(DrawableCompat.java:87)
at org.holoeverywhere.drawable.DrawableCompat.createFromXml(DrawableCompat.java:63)
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:135)
... 31 more Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
at android.content.res.AssetManager.openNonAssetFdNative(Native Method)
at android.content.res.AssetManager.openNonAssetFd(AssetManager.java:428)
at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:147)
... 36 more

**Comment by ChrisDavis8** [comment]
Some more information:
It is only happening on 4.x devices, mainly samsungs
The users that have the problem get it every time that layout is inflated
They have tried reinstalling the app but the problem still occurs

**Comment by ChrisDavis8** [comment]
So I tried changing the progressDrawable in my layouts XML but it still tries to load the dodgy asset, why would that be? is because its set in the style?

**Comment by ChrisDavis8** [comment]
So tried removing all mention of scrubber_track_holo_light from themes and styles removed the pngs and scrubber_progress_horizontal_holo_light so it would just use the holo dark but I still get the same exception how is that possible??
