### ISSUE TITLE
RoboGuice not working in Android 2.2, 2.3.3

### ISSUE THREAD

**Issue by rakshith** [Prototik/HoloEverywhere#546]
The project running fine in Android 4+, but fails in Android 2.2, 2.3.3

In brief Caused by: java.lang.NoSuchMethodException, at java.lang.Class.getDeclaredMethods(Native Method)

posted below the Starck Trace.

Please help me

07-20 18:00:38.248: E/ResourceType(10605): Style contains key with bad entry: 0x010102f0
07-20 18:00:39.948: E/AndroidRuntime(10605): FATAL EXCEPTION: main
07-20 18:00:39.948: E/AndroidRuntime(10605): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.marvelsoft.sadmin/com.marvelsoft.sadmin.DemoActivity}: java.lang.NoSuchMethodException
07-20 18:00:39.948: E/AndroidRuntime(10605):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2663)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at android.app.ActivityThread.access$2300(ActivityThread.java:125)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at android.os.Handler.dispatchMessage(Handler.java:99)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at android.os.Looper.loop(Looper.java:123)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at android.app.ActivityThread.main(ActivityThread.java:4627)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at java.lang.reflect.Method.invokeNative(Native Method)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at java.lang.reflect.Method.invoke(Method.java:521)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at dalvik.system.NativeStart.main(Native Method)
07-20 18:00:39.948: E/AndroidRuntime(10605): Caused by: java.lang.NoSuchMethodException
07-20 18:00:39.948: E/AndroidRuntime(10605):    at java.lang.Class.getDeclaredMethods(Native Method)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at java.lang.ClassCache.getDeclaredMethods(ClassCache.java:153)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at java.lang.Class.getDeclaredMethods(Class.java:774)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:375)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.internal.BindingBuilder.toInstance(BindingBuilder.java:82)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at org.holoeverywhere.addon.AddonRoboguice$HoloModule.configure(AddonRoboguice.java:216)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.spi.Elements.getElements(Elements.java:101)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.spi.Elements.getElements(Elements.java:92)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.util.Modules$RealOverriddenModuleBuilder$1.configure(Modules.java:172)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.AbstractModule.configure(AbstractModule.java:59)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.spi.Elements.getElements(Elements.java:101)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.Guice.createInjector(Guice.java:95)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.Guice.createInjector(Guice.java:72)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.google.inject.Guice.createInjector(Guice.java:62)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at org.holoeverywhere.addon.AddonRoboguice.createInjector(AddonRoboguice.java:299)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at org.holoeverywhere.addon.AddonRoboguice.access$1(AddonRoboguice.java:281)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at org.holoeverywhere.addon.AddonRoboguice$AddonRoboguiceA.obtainInjector(AddonRoboguice.java:67)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at org.holoeverywhere.addon.AddonRoboguice$AddonRoboguiceA.onPreCreate(AddonRoboguice.java:140)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at org.holoeverywhere.app.Activity$5.justAction(Activity.java:219)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at org.holoeverywhere.app.Activity$5.justAction(Activity.java:1)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at org.holoeverywhere.addon.IAddonAttacher$AddonCallback.action(IAddonAttacher.java:9)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(IAddonBasicAttacher.java:167)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at org.holoeverywhere.app.Activity.performAddonAction(Activity.java:497)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at org.holoeverywhere.app.Activity.onCreate(Activity.java:216)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at com.marvelsoft.sadmin.DemoActivity.onCreate(DemoActivity.java:48)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
07-20 18:00:39.948: E/AndroidRuntime(10605):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
07-20 18:00:39.948: E/AndroidRuntime(10605):    ... 11 more

**Comment by gordonpro** [comment]
Prototik looks like busy.

**Comment by Prototik** [comment]
@gordonpro Yea, you right :D

**Comment by tommyannguyen** [comment]
how to fix it ?
