### ISSUE TITLE
NoSuchMethodError in RotateDrawable

### ISSUE THREAD

**Issue by ChrisDavis8** [Prototik/HoloEverywhere#549]
Crash report on 2.3.4

RotateDrawable.invalidateDrawable() is calling getCallBack() which is only available since API 11

```
java.lang.NoSuchMethodError: org.holoeverywhere.drawable.RotateDrawable.getCallback
at org.holoeverywhere.drawable.RotateDrawable.invalidateDrawable(RotateDrawable.java:225)
at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:300)
at android.graphics.drawable.GradientDrawable.onLevelChange(GradientDrawable.java:468)
at android.graphics.drawable.Drawable.setLevel(Drawable.java:445)
at org.holoeverywhere.drawable.RotateDrawable.onLevelChange(RotateDrawable.java:253)
at android.graphics.drawable.Drawable.setLevel(Drawable.java:445)
at org.holoeverywhere.widget.ProgressBar.onDraw(ProgressBar.java:448)
```

**Comment by 8Duke8** [comment]
I felt into the same problem as well. Do you plan to fix it or is there a work around? Thanks in advance

**Comment by william-ferguson-au** [comment]
Is there an alternate?

**Comment by william-ferguson-au** [comment]
Just uploaded a pull request for this. It will stop the crashes on Gingerbread or earlier devices but not sure that it will behave as intended (without being able to call the non-existent method).
