### ISSUE TITLE
ListView OnItemLongClickListenerWrapper problem

### ISSUE THREAD

**Issue by rddimon** [Prototik/HoloEverywhere#551]
Exception when do long click, simple click worked:
java.lang.NullPointerException
        at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onCreateActionMode(PhoneWindow.java:2484)
        at com.android.internal.app.ActionBarImpl$ActionModeImpl.dispatchOnCreate(ActionBarImpl.java:708)
        at com.android.internal.app.ActionBarImpl.startActionMode(ActionBarImpl.java:392)
        at android.app.Activity.onWindowStartingActionMode(Activity.java:4380)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionMode(PhoneWindow.java:2190)
        at android.app.Activity.startActionMode(Activity.java:4363)
        at com.actionbarsherlock.internal.ActionBarSherlockNative.startActionMode(ActionBarSherlockNative.java:226)
        at org.holoeverywhere.addon.AddonSherlock$AddonSherlockA.startActionMode(AddonSherlock.java:190)
        at org.holoeverywhere.app.Activity.startActionMode(Activity.java:566)
        at org.holoeverywhere.widget.ListView.startActionMode(ListView.java:997)
        at org.holoeverywhere.widget.ListView.performItemLongClick(ListView.java:685)
        at org.holoeverywhere.widget.ListView$OnItemLongClickListenerWrapper.onItemLongClick(ListView.java:106)
        at android.widget.AbsListView.performLongPress(AbsListView.java:2588)
        at android.widget.AbsListView$CheckForLongPress.run(AbsListView.java:2538)
        at android.os.Handler.handleCallback(Handler.java:605)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4441)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)

I'm try to use ListFragment in DialogFragment, parent of dialog  SupportMapFragment, using this  http://stackoverflow.com/questions/13721929/using-actionbarsherlock-with-the-new-supportmapfragment 

Can help me to find way of this?)

**Comment by Prototik** [comment]
After migrating on ABC this bug shouldn't occur again.

**Comment by javamuc** [comment]
Care to elaborate on the issue, as I'm facing the same problem but I don't use holoeverywhere nor abs?
