### ISSUE TITLE
Strange problem during release test with proguard

### ISSUE THREAD

**Issue by andresmafra** [Prototik/HoloEverywhere#571]
Im experiencing the strange problem below while testing the release version of my app. The problem only happens with proguard enabled.

```
08-09 21:44:06.140: E/AndroidRuntime(4465): FATAL EXCEPTION: main
08-09 21:44:06.140: E/AndroidRuntime(4465): java.lang.ExceptionInInitializerError
08-09 21:44:06.140: E/AndroidRuntime(4465):     at java.lang.Class.newInstanceImpl(Native Method)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at java.lang.Class.newInstance(Class.java:1409)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at android.app.Instrumentation.newApplication(Instrumentation.java:957)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at android.app.Instrumentation.newApplication(Instrumentation.java:942)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at android.app.LoadedApk.makeApplication(LoadedApk.java:461)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3264)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at android.app.ActivityThread.access$2200(ActivityThread.java:117)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:973)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at android.os.Handler.dispatchMessage(Handler.java:99)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at android.os.Looper.loop(Looper.java:123)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at android.app.ActivityThread.main(ActivityThread.java:3687)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at java.lang.reflect.Method.invokeNative(Native Method)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at java.lang.reflect.Method.invoke(Method.java:507)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at dalvik.system.NativeStart.main(Native Method)
08-09 21:44:06.140: E/AndroidRuntime(4465): Caused by: java.lang.RuntimeException: SystemServiceCreator must be implement SystemService
08-09 21:44:06.140: E/AndroidRuntime(4465):     at org.holoeverywhere.SystemServiceManager.register(Unknown Source)
08-09 21:44:06.140: E/AndroidRuntime(4465):     at org.holoeverywhere.app.Application.<clinit>(Unknown Source)
08-09 21:44:06.140: E/AndroidRuntime(4465):     ... 16 more
```

My Proguard.txt

....

-keep class org.springframework.*\* { _; }
-keep class org.codehaus.jackson._\* { _; }
-keep class org.holoeverywhere._\* { _; }
-keep class com.actionbarsherlock._\* { _; }
-keep class com.facebook._\* { *; }

-dontwarn org.springframework.**
-dontwarn org.apache.**

-libraryjars libs/commons-collections-3.2.1.jar
-libraryjars libs/gson-2.2.3.jar
-libraryjars libs/spring-android-auth-1.0.1.RELEASE.jar
-libraryjars libs/spring-android-core-1.0.1.RELEASE.jar
-libraryjars libs/spring-android-rest-template-1.0.1.RELEASE.jar

HoloEveryWhere version is 1.5.1.

**Comment by Prototik** [comment]
ProGuard remove all runtime annotations from classes. Ask PG don't do it :)
