### ISSUE TITLE
Error while save preferences data

### ISSUE THREAD

**Issue by Huyzy** [Prototik/HoloEverywhere#586]
I am using Facebook SDK 3.5.0 with holoeverywhere and I get this error:

```
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020): Error while save preferences data
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020): java.util.ConcurrentModificationException
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at java.util.HashMap$KeyIterator.next(HashMap.java:833)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at org.holoeverywhere.preference._SharedPreferencesImpl_JSON$ClearJSONManipulate.onJSONManipulate(_SharedPreferencesImpl_JSON.java:40)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at org.holoeverywhere.preference._SharedPreferencesImpl_JSON$EditorImpl.apply(_SharedPreferencesImpl_JSON.java:70)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at org.holoeverywhere.preference._SharedPreferencesImpl_JSON$EditorImpl.commit(_SharedPreferencesImpl_JSON.java:92)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.SharedPreferencesTokenCachingStrategy.clear(SharedPreferencesTokenCachingStrategy.java:177)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Session.closeAndClearTokenInformation(Session.java:612)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Response.createResponseFromObject(Response.java:418)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Response.createResponsesFromObject(Response.java:396)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Response.createResponsesFromString(Response.java:347)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Response.createResponsesFromStream(Response.java:339)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Response.fromHttpConnection(Response.java:313)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Request.executeConnectionAndWait(Request.java:1529)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Request.executeBatchAndWait(Request.java:1428)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.RequestBatch.executeAndWaitImpl(RequestBatch.java:221)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.RequestBatch.executeAndWait(RequestBatch.java:187)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.RequestAsyncTask.doInBackground(RequestAsyncTask.java:164)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.RequestAsyncTask.doInBackground(RequestAsyncTask.java:1)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
08-23 23:30:54.577: E/_SharedPreferencesImpl_JSON(15020):   at java.lang.Thread.run(Thread.java:841)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020): Error while save preferences data
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020): java.util.ConcurrentModificationException
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at java.util.HashMap$KeyIterator.next(HashMap.java:833)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at org.holoeverywhere.preference._SharedPreferencesImpl_JSON$ClearJSONManipulate.onJSONManipulate(_SharedPreferencesImpl_JSON.java:40)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at org.holoeverywhere.preference._SharedPreferencesImpl_JSON$EditorImpl.apply(_SharedPreferencesImpl_JSON.java:70)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at org.holoeverywhere.preference._SharedPreferencesImpl_JSON$EditorImpl.commit(_SharedPreferencesImpl_JSON.java:92)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.SharedPreferencesTokenCachingStrategy.clear(SharedPreferencesTokenCachingStrategy.java:177)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Session.closeAndClearTokenInformation(Session.java:612)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Response.createResponseFromObject(Response.java:418)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Response.createResponsesFromObject(Response.java:396)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Response.createResponsesFromString(Response.java:347)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Response.createResponsesFromStream(Response.java:339)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Response.fromHttpConnection(Response.java:313)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Request.executeConnectionAndWait(Request.java:1529)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.Request.executeBatchAndWait(Request.java:1428)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.RequestBatch.executeAndWaitImpl(RequestBatch.java:221)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.RequestBatch.executeAndWait(RequestBatch.java:187)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.RequestAsyncTask.doInBackground(RequestAsyncTask.java:164)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at com.facebook.RequestAsyncTask.doInBackground(RequestAsyncTask.java:1)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
08-23 23:30:54.607: E/_SharedPreferencesImpl_JSON(15020):   at java.lang.Thread.run(Thread.java:841)
```

**Comment by Prototik** [comment]
Fixed.
