### ISSUE TITLE
Fast Scroll Crash on API 8

### ISSUE THREAD

**Issue by Vorror** [Prototik/HoloEverywhere#593]
I'm using org.holoeverywhere.app.ListFragment and my application seems to crash on API 8 when I use setFastScrollEnabled()

```
08-25 10:03:33.892: E/AndroidRuntime(1756): java.lang.NoSuchMethodError: android.widget.AbsListView.getVerticalScrollbarPosition
08-25 10:03:33.892: E/AndroidRuntime(1756):     at org.holoeverywhere.widget.FastScroller.init(FastScroller.java:385)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at org.holoeverywhere.widget.FastScroller.<init>(FastScroller.java:146)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at org.holoeverywhere.widget.ListView.setFastScrollEnabled(ListView.java:860)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at com.dgtlrepublic.skyjournal.MainListFragment.onActivityCreated(MainListFragment.java:40)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1468)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.support.v4.app._HoloFragment.performActivityCreated(_HoloFragment.java:251)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:931)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:461)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.support.v4.view.ViewPager.populate(ViewPager.java:1064)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.support.v4.view.ViewPager.populate(ViewPager.java:911)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1432)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.View.measure(View.java:8171)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at org.holoeverywhere.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:594)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at org.holoeverywhere.widget.LinearLayout.measureVertical(LinearLayout.java:913)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at org.holoeverywhere.widget.LinearLayout.onMeasure(LinearLayout.java:1105)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.View.measure(View.java:8171)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at org.holoeverywhere.internal.WindowDecorView.onMeasure(WindowDecorView.java:114)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.View.measure(View.java:8171)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at com.jeremyfeinstein.slidingmenu.lib.CustomViewAbove.onMeasure(CustomViewAbove.java:480)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.View.measure(View.java:8171)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:578)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:362)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.View.measure(View.java:8171)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.View.measure(View.java:8171)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at org.holoeverywhere.widget.LinearLayout.measureVertical(LinearLayout.java:1014)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at org.holoeverywhere.widget.LinearLayout.onMeasure(LinearLayout.java:1105)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.View.measure(View.java:8171)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.View.measure(View.java:8171)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3132)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.View.measure(View.java:8171)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.ViewRoot.performTraversals(ViewRoot.java:801)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.view.ViewRoot.handleMessage(ViewRoot.java:1727)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.os.Handler.dispatchMessage(Handler.java:99)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.os.Looper.loop(Looper.java:123)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at android.app.ActivityThread.main(ActivityThread.java:4627)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at java.lang.reflect.Method.invokeNative(Native Method)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at java.lang.reflect.Method.invoke(Method.java:521)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
08-25 10:03:33.892: E/AndroidRuntime(1756):     at dalvik.system.NativeStart.main(Native Method)
```

Fast Scrolling works fine on higher API levels

**Comment by Vorror** [comment]
Issue was fixed in 518. You can close this issue.
