### ISSUE TITLE
ClassNotFoundException: android.view.accessibility.AccessibilityNodeInfo

### ISSUE THREAD

**Issue by william-ferguson-au** [Prototik/HoloEverywhere#596]
android.view.accessibility.AccessibilityNodeInfo was only introduced in API 14

java.lang.NoClassDefFoundError: android.view.accessibility.AccessibilityNodeInfo
at java.lang.Class.getDeclaredMethods(Native Method)
at java.lang.ClassCache.getDeclaredMethods(ClassCache.java:140)
at java.lang.Class.getDeclaredMethod(Class.java:725)
at org.holoeverywhere.LayoutInflater.rInflate(SourceFile:744)
at org.holoeverywhere.LayoutInflater.inflate(SourceFile:538)
at org.holoeverywhere.LayoutInflater.inflate(SourceFile:488)
at org.holoeverywhere.LayoutInflater.inflate(SourceFile:483)
at android.widget.Toast.makeText(Toast.java:230)
at android.widget.Toast.makeText(Toast.java:253)
at org.acra.util.ToastSender.sendToast(SourceFile:26)
at org.acra.ErrorReporter$2.run(SourceFile:624) Caused by: java.lang.ClassNotFoundException: android.view.accessibility.AccessibilityNodeInfo in loader dalvik.system.PathClassLoader[/data/app/au.com.xandar.jumblee-1.apk]
at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:251)
at java.lang.ClassLoader.loadClass(ClassLoader.java:548)
at java.lang.ClassLoader.loadClass(ClassLoader.java:508)
... 11 more java.lang.ClassNotFoundException: android.view.accessibility.AccessibilityNodeInfo in loader dalvik.system.PathClassLoader[/data/app/au.com.xandar.jumblee-1.apk]
at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:251)
at java.lang.ClassLoader.loadClass(ClassLoader.java:548)
at java.lang.ClassLoader.loadClass(ClassLoader.java:508)
at java.lang.Class.getDeclaredMethods(Native Method)
at java.lang.ClassCache.getDeclaredMethods(ClassCache.java:140)
at java.lang.Class.getDeclaredMethod(Class.java:725)
at org.holoeverywhere.LayoutInflater.rInflate(SourceFile:744)
at org.holoeverywhere.LayoutInflater.inflate(SourceFile:538)
at org.holoeverywhere.LayoutInflater.inflate(SourceFile:488)
at org.holoeverywhere.LayoutInflater.inflate(SourceFile:483)
at android.widget.Toast.makeText(Toast.java:230)
at android.widget.Toast.makeText(Toast.java:253)
at org.acra.util.ToastSender.sendToast(SourceFile:26)
at org.acra.ErrorReporter$2.run(SourceFile:624)

**Comment by Prototik** [comment]
Fixed.
