### ISSUE TITLE
HE-1.6.8 NoSuchMethodError: android.view.View.combineMeasuredStates

### ISSUE THREAD

**Issue by william-ferguson-au** [Prototik/HoloEverywhere#600]
View.combineMeasuredStates was introduced in API#11.
This error occurs in some Gingerbread devices.

java.lang.NoSuchMethodError: android.view.View.combineMeasuredStates
at org.holoeverywhere.preference.FragmentBreadCrumbs.onMeasure(SourceFile:160)
at android.view.View.measure(View.java:8314)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
at org.holoeverywhere.widget.LinearLayout.measureChildBeforeLayout(SourceFile:594)
at org.holoeverywhere.widget.LinearLayout.measureVertical(SourceFile:913)
at org.holoeverywhere.widget.LinearLayout.onMeasure(SourceFile:1105)
at android.view.View.measure(View.java:8314)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
at org.holoeverywhere.widget.LinearLayout.measureChildBeforeLayout(SourceFile:594)
at org.holoeverywhere.widget.LinearLayout.measureVertical(SourceFile:913)
at org.holoeverywhere.widget.LinearLayout.onMeasure(SourceFile:1105)
at android.view.View.measure(View.java:8314)
at org.holoeverywhere.widget.LinearLayout.measureHorizontal(SourceFile:648)
at org.holoeverywhere.widget.LinearLayout.onMeasure(SourceFile:1107)
at android.view.View.measure(View.java:8314)
at org.holoeverywhere.widget.LinearLayout.measureVertical(SourceFile:1014)
at org.holoeverywhere.widget.LinearLayout.onMeasure(SourceFile:1105)
at android.view.View.measure(View.java:8314)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
at org.holoeverywhere.internal.WindowDecorView.onMeasure(SourceFile:114)
at android.view.View.measure(View.java:8314)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
at android.view.View.measure(View.java:8314)
at org.holoeverywhere.widget.LinearLayout.measureVertical(SourceFile:1014)
at org.holoeverywhere.widget.LinearLayout.onMeasure(SourceFile:1105)
at android.view.View.measure(View.java:8314)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
at android.view.View.measure(View.java:8314)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3138)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:250)
at android.view.View.measure(View.java:8314)
at android.view.ViewRoot.performTraversals(ViewRoot.java:839)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1860)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:3647)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)

**Comment by william-ferguson-au** [comment]
Thanks. I was just about to have a crack at this. 
But I suspect it would have taken me a lot lot longer to have resolved it.
