### ISSUE TITLE
Could not find font in raw resources: roboto_condensed

### ISSUE THREAD

**Issue by HenriqueRocha** [Prototik/HoloEverywhere#617]
Hi,

I'm not using Roboto Condensed anywhere but I got this bug report today in the Developer Console of my app.

Any ideas about what might be the problem?

Thanks very much in advance.

java.lang.IllegalStateException: Could not find font in raw resources: roboto_condensed
at org.holoeverywhere.FontLoader$RawLazyFont.loadTypeface(FontLoader.java:309)
at org.holoeverywhere.FontLoader$Font.getTypeface(FontLoader.java:72)
at org.holoeverywhere.FontLoader$FontCollector.getTypeface(FontLoader.java:149)
at org.holoeverywhere.FontLoader$FontCollector.getTypeface(FontLoader.java:161)
at org.holoeverywhere.FontLoader.applyInternal(FontLoader.java:455)
at org.holoeverywhere.FontLoader.apply(FontLoader.java:430)
at org.holoeverywhere.FontLoader.applyDefaultFont(FontLoader.java:435)
at org.holoeverywhere.widget.TextView.setFontStyle(TextView.java:74)
at org.holoeverywhere.widget.TextView.setFontStyle(TextView.java:156)
at org.holoeverywhere.widget.TextView.setTextAppearance(TextView.java:116)
at org.holoeverywhere.widget.TextView.setTextAppearance(TextView.java:84)
at org.holoeverywhere.widget.TextView.setTextAppearance(TextView.java:161)
at android.widget.Editor$SuggestionsPopupWindow$SuggestionAdapter.getView(Editor.java:3576)
at android.widget.Editor$SuggestionsPopupWindow.measureContent(Editor.java:3648)
at android.widget.Editor$PinnedPopupWindow.computeLocalPosition(Editor.java:3395)
at android.widget.Editor$PinnedPopupWindow.show(Editor.java:3375)
at android.widget.Editor$SuggestionsPopupWindow.show(Editor.java:3633)
at android.widget.Editor.showSuggestions(Editor.java:2892)
at android.widget.Editor$1.run(Editor.java:2729)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:5777)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
at dalvik.system.NativeStart.main(Native Method)

**Comment by Prototik** [comment]
This font is using a Editor in suggestion popup window. Just copy `demo/res/raw/roboto_condensed.ttf` in your project and rebuild it.

**Comment by AntonKosov** [comment]
In the demo project a few fonts.
What other fonts you need to take?
