### ISSUE TITLE
Could not find font in raw resources: roboto_light

### ISSUE THREAD

**Issue by maiys** [Prototik/HoloEverywhere#626]
Please help, some phone throw this exception, but others work fine, why?

Caused by: java.lang.IllegalStateException: Could not find font in raw resources: roboto_light
at org.holoeverywhere.FontLoader$RawLazyFont.loadTypeface(FontLoader.java:309)
at org.holoeverywhere.FontLoader$Font.getTypeface(FontLoader.java:72)
at org.holoeverywhere.FontLoader$FontCollector.getTypeface(FontLoader.java:149)
at org.holoeverywhere.FontLoader$FontCollector.getTypeface(FontLoader.java:161)
at org.holoeverywhere.FontLoader.applyInternal(FontLoader.java:455)
at org.holoeverywhere.FontLoader.apply(FontLoader.java:430)
at org.holoeverywhere.FontLoader.applyDefaultFont(FontLoader.java:435)
at org.holoeverywhere.widget.TextView.setFontStyle(TextView.java:74)
at org.holoeverywhere.widget.TextView.setFontStyle(TextView.java:156)
at org.holoeverywhere.widget.TextView.setTextAppearance(TextView.java:116)
at org.holoeverywhere.widget.TextView.setTextAppearance(TextView.java:84)
at org.holoeverywhere.widget.TextView.setTextAppearance(TextView.java:161)
at com.android.internal.widget.ActionBarView.initTitle(ActionBarView.java:857)
at com.android.internal.widget.ActionBarView.setDisplayOptions(ActionBarView.java:668)
at com.android.internal.widget.ActionBarView.<init>(ActionBarView.java:254)
... 37 more
android.view.InflateException: Binary XML file line #39: Error inflating class com.android.internal.widget.ActionBarView
at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:382)
at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:590)
at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:444)
at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:731)
at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:734)
at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:734)
at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:538)
at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:488)
at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:483)
at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3094)
at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3157)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:335)
at com.actionbarsherlock.internal.ActionBarSherlockNative.setContentView(ActionBarSherlockNative.java:141)
at org.holoeverywhere.addon.AddonSherlock$AddonSherlockA.installDecorView(AddonSherlock.java:60)
at android.support.v4.app.bq.a(_HoloActivity.java:587)
at android.support.v4.app.bq.action(_HoloActivity.java:1)
at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(IAddonBasicAttacher.java:167)
at org.holoeverywhere.app.Activity.performAddonAction(Activity.java:497)
at android.support.v4.app._HoloActivity.requestDecorView(_HoloActivity.java:584)
at android.support.v4.app._HoloActivity.setContentView(_HoloActivity.java:604)
at com.mofancier.easebackup.MainActivity.onCreate(MainActivity.java:104)
at android.app.Activity.performCreate(Activity.java:5271)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2304)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2400)
at android.app.ActivityThread.access$600(ActivityThread.java:153)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1269)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5295)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:358)

**Comment by Prototik** [comment]
Some textviews in standard android framework use this font. I haven't way (or have, but too hard) for using a existing fonts from framework. Maybe later. Just copy `demo/res/raw/roboto_light.ttf` to your project.
