### ISSUE TITLE
ImageButton crash on inflating

### ISSUE THREAD

**Issue by almozavr** [Prototik/HoloEverywhere#642]
The HEAD is `4555871bb3314d31c5068a361e8f88f3e2b227cb`

```
Caused by: android.view.InflateException: Error inflating class org.holoeverywhere.widget.ImageButton
        at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:296)
        at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:520)
        at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:358)
        at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:657)
        at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:660)
        at org.holoeverywhere.LayoutInflater.parseInclude(LayoutInflater.java:573)
        at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:647)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:464)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.support.v4.app._HoloActivity.requestDecorView(_HoloActivity.java:385)
        at android.support.v4.app._HoloActivity.setContentView(_HoloActivity.java:409)
        at com.threewaytalk.android.ui.activity.ForeignCallChooserActivity.onCreate(ForeignCallChooserActivity.java:59)
        at android.app.Activity.performCreate(Activity.java:5104)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
        ... 11 more
        Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
        at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:272)
        ... 25 more
        Caused by: java.lang.NullPointerException
        at org.holoeverywhere.widget.ImageButton.onCreateDrawableState(ImageButton.java:37)
        at android.view.View.getDrawableState(View.java:14322)
        at android.view.View.setBackgroundDrawable(View.java:14547)
        at android.view.View.setBackground(View.java:14487)
        at android.view.View.<init>(View.java:3647)
        at android.widget.ImageView.<init>(ImageView.java:114)
        at android.widget.ImageButton.<init>(ImageButton.java:87)
        at org.holoeverywhere.widget.ImageButton.<init>(ImageButton.java:21)
        at org.holoeverywhere.widget.ImageButton.<init>(ImageButton.java:17)
        ... 28 more
```

**Comment by waninkoko** [comment]
This is caused when the ImageButton has a background drawable. The bug was introduced by this commit: 73f98facb0355d54862e38a60ecf9874a50d11aa

A temporary workaround is to revert that commit or check if mStateOverlay exists in onCreateDrawableState.
