### ISSUE TITLE
Error inflating class org.holoeverywhere.widget.SeekBar

### ISSUE THREAD

**Issue by Densely** [Prototik/HoloEverywhere#644]
I have some crash logs from HTC ONE XL

09-26 12:20:28.071  10805-10805/com.amem E/AndroidRuntime﹕ FATAL EXCEPTION: main
        android.view.InflateException: Binary XML file line #41: Error inflating class org.holoeverywhere.widget.SeekBar
        at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:382)
        at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:590)
        at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:444)
        at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:731)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:538)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:488)
        at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:483)
        at com.amem.FileManager.AudioItemAdapter.getView(AudioItemAdapter.java:68)
        at org.holoeverywhere.widget.ListAdapterWrapper.getView(ListAdapterWrapper.java:83)
        at android.widget.AbsListView.obtainView(AbsListView.java:2090)
        at android.widget.ListView.makeAndAddView(ListView.java:2004)
        at android.widget.ListView.fillDown(ListView.java:856)
        at android.widget.ListView.fillFromTop(ListView.java:916)
        at android.widget.ListView.layoutChildren(ListView.java:1843)
        at android.widget.AbsListView.onLayout(AbsListView.java:1914)
        at org.holoeverywhere.widget.ListView.onLayout(ListView.java:552)
        at android.view.View.layout(View.java:11359)
        at android.view.ViewGroup.layout(ViewGroup.java:4571)
        at org.holoeverywhere.widget.LinearLayout.setChildFrame(LinearLayout.java:1126)
        at org.holoeverywhere.widget.LinearLayout.layoutVertical(LinearLayout.java:583)
        at org.holoeverywhere.widget.LinearLayout.onLayout(LinearLayout.java:1096)
        at android.view.View.layout(View.java:11359)
        at android.view.ViewGroup.layout(ViewGroup.java:4571)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
        at android.view.View.layout(View.java:11359)
        at android.view.ViewGroup.layout(ViewGroup.java:4571)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
        at android.view.View.layout(View.java:11359)
        at android.view.ViewGroup.layout(ViewGroup.java:4571)
        at org.holoeverywhere.widget.LinearLayout.setChildFrame(LinearLayout.java:1126)
        at org.holoeverywhere.widget.LinearLayout.layoutVertical(LinearLayout.java:583)
        at org.holoeverywhere.widget.LinearLayout.onLayout(LinearLayout.java:1096)
        at android.view.View.layout(View.java:11359)
        at android.view.ViewGroup.layout(ViewGroup.java:4571)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
        at android.view.View.layout(View.java:11359)
        at android.view.ViewGroup.layout(ViewGroup.java:4571)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1665)
        at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2700)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:5045)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
        at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:358)
        ... 46 more
        Caused by: android.content.res.Resources$NotFoundException: File res/drawable/scrubber_progress_horizontal_holo_light.xml from drawable resource ID #0x10804b2
        at org.holoeverywhere.drawable.DrawableCompat.loadDrawable(DrawableCompat.java:138)
        at org.holoeverywhere.drawable.DrawableCompat.getDrawable(DrawableCompat.java:113)
        at org.holoeverywhere.widget.ProgressBar.<init>(ProgressBar.java:246)
        at org.holoeverywhere.widget.ProgressBar.<init>(ProgressBar.java:203)
        at org.holoeverywhere.widget.AbsSeekBar.<init>(AbsSeekBar.java:42)
        at org.holoeverywhere.widget.SeekBar.<init>(SeekBar.java:30)
        at org.holoeverywhere.widget.SeekBar.<init>(SeekBar.ja
09-26 12:20:28.081  10763-10860/com.amem:exceptionReporter I/AMEM﹕ Got request to report error: Intent { act=com.amem.Exception.actionSendReport dat=custom://42905445 cmp=com.amem/.Exception.ExceptionReportService (has extras) }

**Comment by namnx** [comment]
I also have this issue. I found an issue report here https://github.com/Prototik/HoloEverywhere/issues/524 and no fix until now :(

**Comment by Prototik** [comment]
Dupe #545
