### ISSUE TITLE
Using SearchView in ActionBar crashes

### ISSUE THREAD

**Issue by skyflyer** [Prototik/HoloEverywhere#653]
I'm trying to use SearchView inside ActionBar with HoloEverywhere v1.6.8. There are two problems when using theme Holo.Theme.Light.DarkActionBar (it works for Holo.Theme.Light):
1. Testing on API level 10 (emulator), the text inside the search view is black, which makes it unreadable 
2. Testing on API level 17 (Nexus 7), the app crashes with exception (stacktrace below): `Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x7f01001f a=-1}`

0x7f01001f is textColorPrimary, which I see is defined, so it is puzzling why it fails. 

Let me know if you need reproduction of this error.

Stacktrace:

```
E/AndroidRuntime( 5773): android.view.InflateException: Binary XML file line #29: Error inflating class <unknown>
E/AndroidRuntime( 5773):    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:382)
E/AndroidRuntime( 5773):    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:594)
E/AndroidRuntime( 5773):    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:444)
E/AndroidRuntime( 5773):    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:731)
E/AndroidRuntime( 5773):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:538)
E/AndroidRuntime( 5773):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:488)
E/AndroidRuntime( 5773):    at com.actionbarsherlock.widget.SearchView.<init>(SearchView.java:264)
E/AndroidRuntime( 5773):    at com.actionbarsherlock.widget.SearchView.<init>(SearchView.java:252)
E/AndroidRuntime( 5773):    at com.example.holobar.MainActivity.onPrepareOptionsMenu(MainActivity.java:49)
E/AndroidRuntime( 5773):    at android.support.v4.app.Watson.onPreparePanel(Watson.java:89)
E/AndroidRuntime( 5773):    at com.actionbarsherlock.ActionBarSherlock.callbackPrepareOptionsMenu(ActionBarSherlock.java:581)
E/AndroidRuntime( 5773):    at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchPrepareOptionsMenu(ActionBarSherlockNative.java:73)
E/AndroidRuntime( 5773):    at org.holoeverywhere.addon.AddonSherlock$AddonSherlockA.onPreparePanel(AddonSherlock.java:134)
E/AndroidRuntime( 5773):    at org.holoeverywhere.app.Activity$17.action(Activity.java:404)
E/AndroidRuntime( 5773):    at org.holoeverywhere.app.Activity$17.action(Activity.java:1)
E/AndroidRuntime( 5773):    at org.holoeverywhere.addon.IAddonBasicAttacher.performAddonAction(IAddonBasicAttacher.java:167)
E/AndroidRuntime( 5773):    at org.holoeverywhere.app.Activity.performAddonAction(Activity.java:497)
E/AndroidRuntime( 5773):    at org.holoeverywhere.app.Activity.onPreparePanel(Activity.java:401)
E/AndroidRuntime( 5773):    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:441)
E/AndroidRuntime( 5773):    at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:775)
E/AndroidRuntime( 5773):    at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:198)
E/AndroidRuntime( 5773):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
E/AndroidRuntime( 5773):    at android.view.Choreographer.doCallbacks(Choreographer.java:562)
E/AndroidRuntime( 5773):    at android.view.Choreographer.doFrame(Choreographer.java:531)
E/AndroidRuntime( 5773):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
E/AndroidRuntime( 5773):    at android.os.Handler.handleCallback(Handler.java:730)
E/AndroidRuntime( 5773):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 5773):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 5773):    at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime( 5773):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5773):    at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 5773):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime( 5773):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 5773):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 5773): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 5773):    at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 5773):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
E/AndroidRuntime( 5773):    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:358)
E/AndroidRuntime( 5773):    ... 33 more
E/AndroidRuntime( 5773): Caused by: android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x7f01001f a=-1}
E/AndroidRuntime( 5773):    at android.content.res.Resources.loadColorStateList(Resources.java:2232)
E/AndroidRuntime( 5773):    at android.content.res.TypedArray.getColorStateList(TypedArray.java:342)
E/AndroidRuntime( 5773):    at android.widget.TextView.<init>(TextView.java:949)
E/AndroidRuntime( 5773):    at org.holoeverywhere.widget.TextView.<init>(TextView.java:133)
E/AndroidRuntime( 5773):    at org.holoeverywhere.widget.TextView.<init>(TextView.java:129)
E/AndroidRuntime( 5773):    ... 36 more
```

**Comment by Prototik** [comment]
![device-2013-11-02-112017](https://f.cloud.github.com/assets/1416030/1458426/2527752a-436e-11e3-80ef-c71883b76dcf.png)
1.6.8 sucks.
