### ISSUE TITLE
conflict Holoeverywhere with PullTorefresh listview

### ISSUE THREAD

**Issue by amaydiam** [Prototik/HoloEverywhere#710]
I learning holoeverywhere library on my app, but i get issue when combine with PullToRefresh Library (https://github.com/johannilsson/android-pulltorefresh), how to fix it ?

**issue Unable to start activity ComponentInfo{com.droidersuin.project/com.droidersuin.project.app.ContentActivity}: java.lang.ClassCastException: com.markupartist.android.widget.PullToRefreshListView cannot be cast to org.holoeverywhere.widget.ListView**

this logcat

```
12-04 06:01:14.141: E/AndroidRuntime(5073): FATAL EXCEPTION: main
12-04 06:01:14.141: E/AndroidRuntime(5073): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.droidersuin.project/com.droidersuin.project.app.Tab_Android}: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.droidersuin.project/com.droidersuin.project.app.ContentActivity}: java.lang.ClassCastException: com.markupartist.android.widget.PullToRefreshListView cannot be cast to org.holoeverywhere.widget.ListView
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2067)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2092)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.ActivityThread.access$600(ActivityThread.java:133)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.os.Handler.dispatchMessage(Handler.java:99)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.os.Looper.loop(Looper.java:137)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.ActivityThread.main(ActivityThread.java:4794)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at java.lang.reflect.Method.invokeNative(Native Method)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at java.lang.reflect.Method.invoke(Method.java:511)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at dalvik.system.NativeStart.main(Native Method)
12-04 06:01:14.141: E/AndroidRuntime(5073): Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.droidersuin.project/com.droidersuin.project.app.ContentActivity}: java.lang.ClassCastException: com.markupartist.android.widget.PullToRefreshListView cannot be cast to org.holoeverywhere.widget.ListView
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2067)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.ActivityThread.startActivityNow(ActivityThread.java:1908)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.LocalActivityManager.moveToState(LocalActivityManager.java:135)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.LocalActivityManager.startActivity(LocalActivityManager.java:347)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.widget.TabHost$IntentContentStrategy.getContentView(TabHost.java:694)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.widget.TabHost.setCurrentTab(TabHost.java:358)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.widget.TabHost.addTab(TabHost.java:236)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at com.droidersuin.project.app.Tab_Android.onCreate(Tab_Android.java:173)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.Activity.performCreate(Activity.java:5008)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2031)
12-04 06:01:14.141: E/AndroidRuntime(5073):     ... 11 more
12-04 06:01:14.141: E/AndroidRuntime(5073): Caused by: java.lang.ClassCastException: com.markupartist.android.widget.PullToRefreshListView cannot be cast to org.holoeverywhere.widget.ListView
12-04 06:01:14.141: E/AndroidRuntime(5073):     at org.holoeverywhere.app.ListActivity.onSupportContentChanged(ListActivity.java:68)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.support.v4.app._HoloActivity.setContentView(_HoloActivity.java:405)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at com.droidersuin.project.app.ContentActivity.onCreate(ContentActivity.java:170)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.Activity.performCreate(Activity.java:5008)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
12-04 06:01:14.141: E/AndroidRuntime(5073):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2031)
12-04 06:01:14.141: E/AndroidRuntime(5073):     ... 21 more
```

**Comment by BraisGabin** [comment]
Two workarounds:
1. Don't use ListActivity. Use Activity, or 
2. Make PullToResfreshListView extends HoloEverywhere.ListView.
