### ISSUE TITLE
Resources$NotFoundException: String resource ID #0xffffffff

### ISSUE THREAD

**Issue by AntonKosov** [Prototik/HoloEverywhere#715]
Device: Nexus 4
Android version: 4.4
HoloEverywhere version: 2.1.0

Reproducibility 100%
1. Run my application.
2. Press Home button.
3. Run any other application.
4. Rotate phone on 90 degrees (to landscape).
5. Message box is displayed that in my application error.

Log:

```
android.content.res.Resources$NotFoundException: String resource ID #0xffffffff
        at android.content.res.Resources.getText(Resources.java:244)
        at com.android.internal.widget.ActionBarView.setHomeActionContentDescription(ActionBarView.java:1347)
        at com.android.internal.widget.ActionBarView.onConfigurationChanged(ActionBarView.java:263)
        at android.view.View.dispatchConfigurationChanged(View.java:8066)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1086)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1090)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1090)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1090)
        at android.view.ViewRootImpl.updateConfiguration(ViewRootImpl.java:2910)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3058)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4998)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by AntonKosov** [comment]
It seems my fault.

**Comment by premnirmal** [comment]
What was the solution @AntonKosov? I am having the same error

**Comment by Prototik** [comment]
0xffffffff = -1. Make sure that you have valid references in style/code.

**Comment by premnirmal** [comment]
Thank you

**Comment by AntonKosov** [comment]
Prototik is absolutely right.

**Comment by ASemeniuk** [comment]
I had exactly the same problem recently (with exactly the same message). It occurrs only on Android 4.4 devices so it is hard to track down.
After lots of researching I found the reason for this. I was using sliding navigation drawer and the problem was in the following code:

``` java
new ActionBarDrawerToggle(this, mDrawerLayout, a2.getResourceId(0, -1), -1, -1)  {...}
```

The last two parameters stand for content description resources of opened and closed drawer images (accessibility-related stuff). I mistakenly put **-1** there (in order to use default `resID`) but the correct value should be **0** instead.

Hope this helps.

**Comment by farhadNascenia** [comment]
THanks ASemeniuk.

**Comment by Rendellhb** [comment]
ASemeniuk Thank´s man.
this was really helpfull.
