### ISSUE TITLE
How to theme a Spinner

### ISSUE THREAD

**Issue by 4nd3250n** [Prototik/HoloEverywhere#723]
The goal is to customize Spinner, font size in particular, without adding any new widgets to spinner.
In the HoloEverywehere res folder there are two xml files:
    simple_spinner_dropdown_item.xml and
    simple_spinner_item.xml.

One uses atribute reference ?spinnerDropDownStyle and the other ?spinnerItemStyle.
I assume those two atributes reference the styles.

Both of these atributes are set in themes:

``` xml
<style name="Holo.Theme" parent="Holo.Base.Theme">
        ...
    <item name="android:spinnerItemStyle">@style/Holo.TextView.SpinnerItem</item>
        ...
</style>

<style name="Holo.Theme.Light" parent="Holo.Base.Theme.Light">
        ...
    <item name="android:spinnerItemStyle">@style/Holo.TextView.SpinnerItem</item>
        ...
</style>
```

What I find puzzling is that in both themes the spinnerItemStyle is set to the same style. How come that spinner has a different look in different themes?     

Style Holo.TextView.SpinnerItem is further defined in styles.xml:

``` xml
<style name="Holo.TextView.SpinnerItem">
        ...    
    <item name="android:textAppearance">@style/Holo.TextAppearance.TextView.SpinnerItem</item>
        ...
</style>
```

And Holo.TextAppearance.TextView.SpinnerItem is defined:

``` xml
<style name="Holo.TextAppearance.TextView.SpinnerItem">
    <!--Include block: ColorsDark-->
    <item name="android:textColor">@color/primary_text_holo_dark</item>
    <item name="android:textColorHighlight">@color/highlighted_text_holo_dark</item>
    <item name="android:textColorHint">@color/hint_foreground_holo_dark</item>
    <!--End of block ColorsDark-->
</style>

<style name="Holo.TextAppearance.TextView.SpinnerItem.Light">
    <!--Include block: ColorsLight-->
    <item name="android:textColor">@color/primary_text_holo_light</item>
    <item name="android:textColorHighlight">@color/highlighted_text_holo_light</item>
    <item name="android:textColorHint">@color/hint_foreground_holo_light</item>
    <!--End of block ColorsLight-->
</style>
```

Size is inherited from style Holo.TextAppearance.TextView. So my train of thought was:
if I inherit from Holo.TextAppearance.TextView.SpinnerItem and override text size I would change the font size used in spinner. Wrong.

What i did was to add the following stuff to my theme and styles

``` xml
<style name="ThemeHoloDarkCustom" parent="@style/Holo.Theme.Fullscreen">
        ...
    <item name="spinnerItemStyle">@style/Holo.TextView.SpinnerItem.Custom</item>
    <item name="spinnerDropDownItemStyle">@style/Holo.TextView.SpinnerItem.DropDown.Custom</item>
        ... 
</style>

<style name="Holo.TextView.SpinnerItem.Custom" parent="@style/Holo.TextView.SpinnerItem">
    <item name="android:textAppearance">@style/Holo.TextAppearance.TextView.SpinnerItem.Custom</item>
</style>

<style name="Holo.TextView.SpinnerItem.DropDown.Custom" parent="@style/Holo.TextView.SpinnerItem">
    <item name="android:textAppearance">@style/Holo.TextAppearance.TextView.SpinnerItem.Custom</item>
</style>

<style name="Holo.TextAppearance.TextView.SpinnerItem.Custom" arent="@style/Holo.TextAppearance.TextView.SpinnerItem" >
    <item name="android:textSize">50dp</item>
</style>
```

This should set the spinner text size to 50dp. Yet it does not. I have tried many many variations around the same idea. No effect what so ever.
How does one theme a spinner?
I have seen posts on the internet that propose implementin completely new layout for spinner items and implementing array adapter. But this approach seems so wrong.

**Comment by Prototik** [comment]
Works nicely:
![device-2013-12-14-122809](https://f.cloud.github.com/assets/1416030/1747803/5b847fd4-6478-11e3-8f2c-a60ff99907ec.png)![device-2013-12-14-122815](https://f.cloud.github.com/assets/1416030/1747806/5c163366-6478-11e3-8fcc-a398843d2503.png)

**Comment by 4nd3250n** [comment]
I have installed release for fix 723. After this there is an error unrelated to spinner. I think it has to do somethibg with support library used.

```
112-15 10:16:47.382: E/AndroidRuntime(1603): FATAL EXCEPTION: main
12-15 10:16:47.382: E/AndroidRuntime(1603): java.lang.NoClassDefFoundError: android.support.v4.view.ViewCompatGingerbread
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.support.v4.view.ViewCompat$GBViewCompatImpl.getOverScrollMode(ViewCompat.java:406)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.support.v4.view.ViewCompat.getOverScrollMode(ViewCompat.java:628)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.support.v4.view.ViewPager.draw(ViewPager.java:2174)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.View.draw(View.java:6936)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.View.draw(View.java:6936)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.View.draw(View.java:6936)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.widget.FrameLayout.draw(FrameLayout.java:357)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1917)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewRoot.draw(ViewRoot.java:1530)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewRoot.performTraversals(ViewRoot.java:1266)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.view.ViewRoot.handleMessage(ViewRoot.java:1868)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.os.Handler.dispatchMessage(Handler.java:99)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.os.Looper.loop(Looper.java:130)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at android.app.ActivityThread.main(ActivityThread.java:3691)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at java.lang.reflect.Method.invokeNative(Native Method)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at java.lang.reflect.Method.invoke(Method.java:507)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
12-15 10:16:47.382: E/AndroidRuntime(1603):     at dalvik.system.NativeStart.main(Native Method)
12-15 10:16:56.006: I/Process(1603): Sending signal. PID: 1603 SIG: 9
```

**Comment by Prototik** [comment]
Check your build environment. In latest support-v4 19.0.1 (and in all 18.0.*) this class exists and works as expected.

**Comment by 4nd3250n** [comment]
Yes. it does exist in support library, yet somehow it produces this error. I am a bit lost here. Could you give some pointers what should I check?
EDIT: Perhaps I should add that I am running it on 2.3.5 device.

**Comment by 4nd3250n** [comment]
Is there a trick to compiling this?
I have tried every possible permutation in Properties -> java Build Path. No result.
