### ISSUE TITLE
IllegalStateException: Circular dependencies cannot exist in AnimatorSet

### ISSUE THREAD

**Issue by AntonKosov** [Prototik/HoloEverywhere#725]
Some of our users an error occurs

HoloEverywhere version: 2.1.0
Android version / Device:
3.2 / samsung samsung GT-P6800
3.2 / samsung samsung GT-P6200
3.2 / samsung samsung GT-P7300
3.2.1 / Acer acer A501

Stack trace:
java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet
at com.a.a.c.i(SourceFile:818)
at com.a.a.c.a(SourceFile:456)
at org.holoeverywhere.widget.datetimepicker.time.RadialPickerLayout.setCurrentItemShowing(SourceFile:543)
at org.holoeverywhere.widget.datetimepicker.time.TimePickerDialog.setCurrentItemShowing(SourceFile:354)
at org.holoeverywhere.widget.datetimepicker.time.TimePickerDialog.onValueSelected(SourceFile:305)
at org.holoeverywhere.widget.datetimepicker.time.RadialPickerLayout.onTouch(SourceFile:708)
at android.view.View.dispatchTouchEvent(View.java:4636)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1554)
...

com.a.a.c = com.nineoldandroids.animation.AnimatorSet

**Comment by zxy198717** [comment]
The same issue at HTC P510e. so what's the bug status?

**Comment by AntonKosov** [comment]
I tried adding to proguard options

-keep class com.nineoldandroids.*\* { *; }

But it did no help me.

**Comment by zxy198717** [comment]
I don't know the root cause, and just add "try catch", but i think it isn't a goog way. 

try {
                if (mTransition != null && mTransition.isRunning()) {
                    mTransition.end();
                }
                mTransition = new AnimatorSet();
                mTransition.playTogether(anims);
                mTransition.start();
            } catch (Exception e) {
                int hourAlpha = (index == HOUR_INDEX) ? 255 : 0;
                int minuteAlpha = (index == MINUTE_INDEX) ? 255 : 0;
                mHourRadialTextsView.setAlpha(hourAlpha);
                mHourRadialSelectorView.setAlpha(hourAlpha);
                mMinuteRadialTextsView.setAlpha(minuteAlpha);
                mMinuteRadialSelectorView.setAlpha(minuteAlpha);
            }
