### ISSUE TITLE
java.lang.NoClassDefFoundError: android.support.v4.app._HoloFragmentInflater$1

### ISSUE THREAD

**Issue by Joosun** [Prototik/HoloEverywhere#726]
```
java.lang.NoClassDefFoundError: android.support.v4.app._HoloFragmentInflater$1
        at android.support.v4.app._HoloFragmentInflater.<clinit>(_HoloFragmentInflater.java:18)
        at org.holoeverywhere.app.Application.<clinit>(Application.java:34)
        at java.lang.Class.newInstanceImpl(Native Method)
        at java.lang.Class.newInstance(Class.java:1130)
        at android.app.Instrumentation.newApplication(Instrumentation.java:990)
        at android.app.Instrumentation.newApplication(Instrumentation.java:975)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4417)
        at android.app.ActivityThread.access$1300(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Prototik** [comment]
Make sure that you use a support-v4 19.0.1. If you use gradle - please switch to HoloEverywhere Plugin instead of  raw handling. If maven - add holo repository to your pom.

**Comment by Joosun** [comment]
How to do it. I use the gradle.

Thanks.

**Comment by Prototik** [comment]
[Wiki](https://github.com/Prototik/HoloEverywhere/wiki/Gradle)

**Comment by Joosun** [comment]
Has error when build.

```
Could not find method preferences() for arguments [] on Addon container.
```

**Comment by Prototik** [comment]
Oops, addons feature seems to broken...

**Comment by Joosun** [comment]
That I was the how to do it?

**Comment by Prototik** [comment]
You can use this syntax for workaround:

```
holoeverywhere {
  addons {
    'preferences'
  }
}
```

**Comment by Joosun** [comment]
use

```
apply plugin: 'holoeverywhere'
```

many resources not found

```
Error retrieving parent for item: No resource found that matches the given name 'Holo.Button.Borderless.Light'.
Error retrieving parent for item: No resource found that matches the given name 'Holo.Preference'.
No resource found that matches the given name: attr 'layout'.
Error retrieving parent for item: No resource found that matches the given name 'Holo.PreferenceCheckBox'.
No resource found that matches the given name: attr 'layout'.
Error retrieving parent for item: No resource found that matches the given name 'Holo.TextView.ListSeparator.Light'.
......
```

**Comment by Prototik** [comment]
Show you `build.gradle`

**Comment by Joosun** [comment]
```
buildscript {
    repositories {
        mavenCentral()

        maven { url 'http://download.crashlytics.com/maven' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:0.6.+'

        classpath 'com.crashlytics.tools.gradle:crashlytics-gradle:1.+'

        classpath 'org.holoeverywhere:plugin:0.2.+'
    }
}

apply plugin: 'android'

apply plugin: 'crashlytics'

apply plugin: 'holoeverywhere'

repositories {
    maven { url 'http://download.crashlytics.com/maven' }

    mavenCentral()
}

holoeverywhere {
    addons {
        'preferences'
    }

    library {
        version '2.1.0'
    }
}

android {
    compileSdkVersion 19
    buildToolsVersion '19.0.0'

    defaultConfig {
        minSdkVersion 8
        targetSdkVersion 19
    }
}

dependencies {
    compile 'com.android.support:support-v4:19.0.1+'

    compile 'com.github.castorflex.smoothprogressbar:library:0.2.0@aar'
    compile 'com.github.chrisbanes.actionbarpulltorefresh:library:0.9.3@aar'
    compile 'com.github.chrisbanes.actionbarpulltorefresh:extra-abc:0.9.3@aar'
    compile 'com.github.chrisbanes.photoview:library:1.2.2'

    compile 'com.crashlytics.android:crashlytics:1.+'

    compile files('../libraries/libGoogleAnalyticsV2.jar')
    compile files('../libraries/Parse-1.3.7.jar')
}
```
