### ISSUE TITLE
Current Demo: Unmarshalling unknown type code 1279544898 at offset 364

### ISSUE THREAD

**Issue by stleusc** [Prototik/HoloEverywhere#760]
Running the current demo (and my own app show the same behaviour) I get this error.
Open Demo App, Switch to Settings, Select Base EditText, Type something and hit HOME
Wait, wait, wait until system kill activity.
Use TaskSwitcher and switch back to App.
CRASH! Expected: Activity resumes...

If you don't want to wait forever, got to phones Developer Settings and select 'Don't keep Activities'

01-18 22:39:02.890: E/AndroidRuntime(701): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.holoeverywhere.demo/org.holoeverywhere.demo.DemoActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@42c15628: Unmarshalling unknown type code 1279544898 at offset 364
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2110)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.app.ActivityThread.access$700(ActivityThread.java:143)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.os.Handler.dispatchMessage(Handler.java:99)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.os.Looper.loop(Looper.java:137)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.app.ActivityThread.main(ActivityThread.java:4950)
01-18 22:39:02.890: E/AndroidRuntime(701):  at java.lang.reflect.Method.invokeNative(Native Method)
01-18 22:39:02.890: E/AndroidRuntime(701):  at java.lang.reflect.Method.invoke(Method.java:511)
01-18 22:39:02.890: E/AndroidRuntime(701):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
01-18 22:39:02.890: E/AndroidRuntime(701):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
01-18 22:39:02.890: E/AndroidRuntime(701):  at dalvik.system.NativeStart.main(Native Method)
01-18 22:39:02.890: E/AndroidRuntime(701): Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@42c15628: Unmarshalling unknown type code 1279544898 at offset 364
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.os.Parcel.readValue(Parcel.java:2032)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.os.Parcel.readMapInternal(Parcel.java:2226)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.os.Bundle.unparcel(Bundle.java:223)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.os.Bundle.getParcelable(Bundle.java:1165)
01-18 22:39:02.890: E/AndroidRuntime(701):  at org.holoeverywhere.preference.Preference.dispatchRestoreInstanceState(Preference.java:145)
01-18 22:39:02.890: E/AndroidRuntime(701):  at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(PreferenceGroup.java:90)
01-18 22:39:02.890: E/AndroidRuntime(701):  at org.holoeverywhere.preference.PreferenceGroup.dispatchRestoreInstanceState(PreferenceGroup.java:90)
01-18 22:39:02.890: E/AndroidRuntime(701):  at org.holoeverywhere.preference.Preference.restoreHierarchyState(Preference.java:935)
01-18 22:39:02.890: E/AndroidRuntime(701):  at org.holoeverywhere.preference.PreferenceFragment.onActivityCreated(PreferenceFragment.java:156)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1508)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:948)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1105)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1087)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1885)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:566)
01-18 22:39:02.890: E/AndroidRuntime(701):  at org.holoeverywhere.app.Activity.onStart(Activity.java:301)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1178)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.app.Activity.performStart(Activity.java:5189)
01-18 22:39:02.890: E/AndroidRuntime(701):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2083)
01-18 22:39:02.890: E/AndroidRuntime(701):  ... 11 more

**Comment by stleusc** [comment]
Wow.... so many comments?

**Comment by BraisGabin** [comment]
Wow, it's a bug. What comment do you want? You are right, you described the bug perfectly and more information isn't necessary. But no one fixed it yet. There was no point to comment here.
