### ISSUE TITLE
AlertDialog setItems

### ISSUE THREAD

**Issue by xavifc** [Prototik/HoloEverywhere#78]
I'm using an AlertDialog with this code:

``` java
AlertDialog.Builder builder = new AlertDialog.Builder(this);
        CharSequence[] items = {"1", "2"};
        builder.setTitle("Title").setItems(items, null);
        builder.show();
```

within an Activity extending from SActivity, and it gives me the following error:

``` java
09-14 08:44:10.123: E/AndroidRuntime(460): Uncaught handler: thread main exiting due to uncaught exception
09-14 08:44:10.163: E/AndroidRuntime(460): android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.LayoutInflater.createView(LayoutInflater.java:513)
09-14 08:44:10.163: E/AndroidRuntime(460):  at com.WazaBe.HoloEverywhere.LayoutInflater.onCreateView(LayoutInflater.java:135)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:563)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.LayoutInflater.inflate(LayoutInflater.java:385)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:332)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.ArrayAdapter.getView(ArrayAdapter.java:323)
09-14 08:44:10.163: E/AndroidRuntime(460):  at com.WazaBe.HoloEverywhere.ArrayAdapter.getView(ArrayAdapter.java:51)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.AbsListView.obtainView(AbsListView.java:1274)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.ListView.measureHeightOfChildren(ListView.java:1147)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.ListView.onMeasure(ListView.java:1060)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.View.measure(View.java:7964)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3023)
09-14 08:44:10.163: E/AndroidRuntime(460):  at com.WazaBe.HoloEverywhere.LinearLayout.measureChildWithMargins(LinearLayout.java:161)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:888)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.LinearLayout.measureVertical(LinearLayout.java:350)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.LinearLayout.onMeasure(LinearLayout.java:278)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.View.measure(View.java:7964)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3023)
09-14 08:44:10.163: E/AndroidRuntime(460):  at com.WazaBe.HoloEverywhere.LinearLayout.measureChildWithMargins(LinearLayout.java:161)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:888)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.LinearLayout.measureVertical(LinearLayout.java:350)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.LinearLayout.onMeasure(LinearLayout.java:278)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.View.measure(View.java:7964)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3023)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.View.measure(View.java:7964)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:3023)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.FrameLayout.onMeasure(FrameLayout.java:245)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.View.measure(View.java:7964)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.ViewRoot.performTraversals(ViewRoot.java:763)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.ViewRoot.handleMessage(ViewRoot.java:1633)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.os.Handler.dispatchMessage(Handler.java:99)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.os.Looper.loop(Looper.java:123)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.app.ActivityThread.main(ActivityThread.java:4363)
09-14 08:44:10.163: E/AndroidRuntime(460):  at java.lang.reflect.Method.invokeNative(Native Method)
09-14 08:44:10.163: E/AndroidRuntime(460):  at java.lang.reflect.Method.invoke(Method.java:521)
09-14 08:44:10.163: E/AndroidRuntime(460):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
09-14 08:44:10.163: E/AndroidRuntime(460):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
09-14 08:44:10.163: E/AndroidRuntime(460):  at dalvik.system.NativeStart.main(Native Method)
09-14 08:44:10.163: E/AndroidRuntime(460): Caused by: java.lang.reflect.InvocationTargetException
09-14 08:44:10.163: E/AndroidRuntime(460):  at com.WazaBe.HoloEverywhere.TextView.<init>(TextView.java:15)
09-14 08:44:10.163: E/AndroidRuntime(460):  at java.lang.reflect.Constructor.constructNative(Native Method)
09-14 08:44:10.163: E/AndroidRuntime(460):  at java.lang.reflect.Constructor.newInstance(Constructor.java:446)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.view.LayoutInflater.createView(LayoutInflater.java:500)
09-14 08:44:10.163: E/AndroidRuntime(460):  ... 39 more
09-14 08:44:10.163: E/AndroidRuntime(460): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/item_background_holo_dark.xml from color state list resource ID #0x0
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.content.res.Resources.loadColorStateList(Resources.java:1813)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.content.res.TypedArray.getColorStateList(TypedArray.java:289)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.TextView.<init>(TextView.java:627)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.widget.TextView.<init>(TextView.java:320)
09-14 08:44:10.163: E/AndroidRuntime(460):  ... 43 more
09-14 08:44:10.163: E/AndroidRuntime(460): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/item_background_holo_dark.xml from xml type colorstatelist resource ID #0x0
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.content.res.Resources.loadXmlResourceParser(Resources.java:1920)
09-14 08:44:10.163: E/AndroidRuntime(460):  at android.content.res.Resources.loadColorStateList(Resources.java:1808)
09-14 08:44:10.163: E/AndroidRuntime(460):  ... 46 more
```

but only when using setItems. I've tested in 2.1, 2.3 and 4.0, and in 4.0 doesn't crash

**Comment by Prototik** [comment]
Try to update: just now released 1.2.2

**Comment by xavifc** [comment]
Wow, had to do a lot of changes! :)

Sorry but it still doesn't work, and now not even on 4.0

(BTW thanks for your work!)

**Comment by Prototik** [comment]
Oh, yes, in select_dialog_item_holo using attribute textColorAlertDialogListItem for text color, but it is available from 11 api. You may change text color in sources, or wait a 1.2.3 :)

Fixed in dev version

**Comment by xavifc** [comment]
Ok, thank you!
