### ISSUE TITLE
setTitle AlertDialog crashes 

### ISSUE THREAD

**Issue by amaydiam** [Prototik/HoloEverywhere#795]
hello i have get error when i setTitle AlertDialog with Holoeverywhere ...

```
java.lang.ClassCastException: org.holoeverywhere.app.Dialog$DialogTitle cannot be cast to org.holoeverywhere.widget.TextView
at org.holoeverywhere.widget.AlertController.setupTitle(AlertController.java:719)
at org.holoeverywhere.widget.AlertController.setupView(AlertController.java:750)
at org.holoeverywhere.widget.AlertController.installContent(AlertController.java:469)
at org.holoeverywhere.app.AlertDialog.onCreate(AlertDialog.java:411)
at android.app.Dialog.dispatchOnCreate(Dialog.java:351)
at android.app.Dialog.show(Dialog.java:256)
at com.droidersuin.project.setting.ProfileActivity$8.onClick(ProfileActivity.java:432)
at android.view.View.performClick(View.java:4232)
at android.view.View$PerformClick.run(View.java:17298)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4921)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
at dalvik.system.NativeStart.main(Native Method)
```

this is my code 

```
AlertDialog.Builder builder = new AlertDialog.Builder(this);
                    builder.setTitle("Choose Crop App");
                    builder.setAdapter( adapter, new DialogInterface.OnClickListener() {
                        public void onClick( DialogInterface dialog, int item ) {
                            startActivityForResult( cropOptions.get(item).appIntent, CROP_FROM_CAMERA);
                        }
                    });

                    builder.setOnCancelListener( new DialogInterface.OnCancelListener() {
                        @Override
                        public void onCancel( DialogInterface dialog ) {

                            if (mImageCaptureUri != null ) {
                                getContentResolver().delete(mImageCaptureUri, null, null );
                                mImageCaptureUri = null;
                            }
                        }
                    } );
```

error at **builder.setTitle("Choose Crop App");**

how to fix it? sory for my english

**Comment by Prototik** [comment]
O_o.
DialogTitle extends org.holoeverywhere.widget.TextView exactly.
Which version of library you are using?

**Comment by Prototik** [comment]
Yep, many thanks for additional info.
