### ISSUE TITLE
holoeverywhere toast.maketext error 

### ISSUE THREAD

**Issue by amaydiam** [Prototik/HoloEverywhere#798]
i'm get issue with last library holoeverywhere ... this

```
03-02 07:59:29.852: E/AndroidRuntime(10814): FATAL EXCEPTION: main
03-02 07:59:29.852: E/AndroidRuntime(10814): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.droidersuin.project/com.droidersuin.project.posting.PostingActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2067)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2092)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.app.ActivityThread.access$600(ActivityThread.java:133)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.os.Handler.dispatchMessage(Handler.java:99)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.os.Looper.loop(Looper.java:137)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.app.ActivityThread.main(ActivityThread.java:4794)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at java.lang.reflect.Method.invokeNative(Native Method)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at java.lang.reflect.Method.invoke(Method.java:511)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at dalvik.system.NativeStart.main(Native Method)
03-02 07:59:29.852: E/AndroidRuntime(10814): Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
03-02 07:59:29.852: E/AndroidRuntime(10814):    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:305)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:513)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:359)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:456)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:415)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:410)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:139)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at org.holoeverywhere.widget.Toast.makeText(Toast.java:19)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at com.droidersuin.project.posting.PostingActivity.onCreate(PostingActivity.java:318)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.app.Activity.performCreate(Activity.java:5008)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2031)
03-02 07:59:29.852: E/AndroidRuntime(10814):    ... 11 more
03-02 07:59:29.852: E/AndroidRuntime(10814): Caused by: java.lang.reflect.InvocationTargetException
03-02 07:59:29.852: E/AndroidRuntime(10814):    at java.lang.reflect.Constructor.constructNative(Native Method)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:281)
03-02 07:59:29.852: E/AndroidRuntime(10814):    ... 22 more
03-02 07:59:29.852: E/AndroidRuntime(10814): Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f0100ab a=-1}
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.content.res.Resources.loadDrawable(Resources.java:1968)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.view.View.<init>(View.java:3336)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.view.ViewGroup.<init>(ViewGroup.java:427)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.widget.LinearLayout.<init>(LinearLayout.java:176)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at android.widget.LinearLayout.<init>(LinearLayout.java:172)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at org.holoeverywhere.widget.LinearLayout.<init>(LinearLayout.java:54)
03-02 07:59:29.852: E/AndroidRuntime(10814):    at org.holoeverywhere.widget.LinearLayout.<init>(LinearLayout.java:50)
03-02 07:59:29.852: E/AndroidRuntime(10814):    ... 
```

error at:
`Toast.makeText(getApplicationContext(), ""+height_keterangan, Toast.LENGTH_SHORT).show();`
how fix it ? thanks

**Comment by Prototik** [comment]
> getApplicationContext()

Use activity's context instead.
