### ISSUE TITLE
DatePickerDialog issue NoClassDefFoundError

### ISSUE THREAD

**Issue by hungnguyen-vn** [Prototik/HoloEverywhere#799]
I encounter this issue when try to using DatePickerDialog:

```
java.lang.NoClassDefFoundError: org.holoeverywhere.widget.datetimepicker.DateTimePickerUtils$1
            at org.holoeverywhere.widget.datetimepicker.DateTimePickerUtils.<clinit>(DateTimePickerUtils.java:39)
            at org.holoeverywhere.widget.datetimepicker.date.DatePickerDialog.setCurrentView(DatePickerDialog.java:249)
            at org.holoeverywhere.widget.datetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:232)
```

This is my **PickersDatePickerFragment.java**

``` java
package com.dmm.clgt.fragments;

import android.os.Bundle;

import org.holoeverywhere.widget.Toast;
import org.holoeverywhere.widget.datetimepicker.date.DatePickerDialog;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

public class PickersDatePickerFragment extends DatePickerDialog implements DatePickerDialog.OnDateSetListener {
    private static final DateFormat DATE_FORMAT = new SimpleDateFormat("d/M/y");

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        initialize(this, 1996, Calendar.APRIL, 14);
    }

    @Override
    public void onDateSet(DatePickerDialog dialog, int year, int monthOfYear, int dayOfMonth) {
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.MONTH, monthOfYear);
        calendar.set(Calendar.DAY_OF_MONTH, dayOfMonth);
        Toast.makeText(getSupportActivity(), "Set date: " + DATE_FORMAT.format(calendar.getTime()), Toast.LENGTH_SHORT).show();

    }
}
```

And here is how I use it in my Activity

``` java
     btDisplay.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                PickersDatePickerFragment dialogFragment = new PickersDatePickerFragment();
                dialogFragment.show(getSupportFragmentManager());
            }
        });
```

@Prototik Could you support me dealing with this issue?

**Comment by Prototik** [comment]
You forgot to include `nineoldandroids` library to your final apk file.

**Comment by hungnguyen-vn** [comment]
Ok, thanks a lot
