### ISSUE TITLE
ProgressDialog caused Exception in Fragment

### ISSUE THREAD

**Issue by RobGThai** [Prototik/HoloEverywhere#80]
I put this code in Fragment.

``` java
        ProgressDialog dialog = new ProgressDialog(getActivity());
        dialog.setMessage("Accept?");
        dialog.setCancelable(true);
        dialog.setIndeterminate(true);
        dialog.setMessage("Just accept it.");
        dialog.setInverseBackgroundForced(true);
        dialog.show();
```

The Logcat output:

``` java
java.lang.ClassCastException: com.WazaBe.HoloEverywhere.widget.ProgressBar
at android.app.ProgressDialog.onCreate(ProgressDialog.java:155)
at android.app.Dialog.dispatchOnCreate(Dialog.java:307)
at android.app.Dialog.show(Dialog.java:225)
[next line is dialog.show()]
```

The Fragment is inside SActivity.

I tried to put this dialog in SherlockMapActivity but the dialog appear as non-Holo even though the theme is set as **android:theme="@style/Holo.Theme.Sherlock.Light"**. however, AlertDialog works just fine.

**Comment by Prototik** [comment]
Use dev version. Fragments began supported only in the dev version of just a couple of hours ago.

**Comment by RobGThai** [comment]
Oh thanks.
