### ISSUE TITLE
Class cast exception when using date picker

### ISSUE THREAD

**Issue by crocsoftware** [Prototik/HoloEverywhere#800]
Hello - I am getting this 
E/AndroidRuntime(13765): Caused by: java.lang.ClassCastException: org.holoeverywhere.widget.NumberPicker cannot be cast to android.widget.NumberPicker 

Using holo 2.1 & android 4.3.

The xml defining the layout is using android "DatePicker"  - no funny stuff here.

```
<LinearLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:id="@+id/delete_diary_layout"
  android:layout_height="fill_parent" 
  android:minWidth="200dp"
  android:layout_width="fill_parent" android:orientation="vertical">
    <DatePicker
        android:id="@+id/date_picker"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
       />

</LinearLayout>
```

I even tried to bypass by using DatePickerDialog - the problem is that when i am using "settitle" to datepickerdialog - nothing shows on screen.
Is there a way to bypass this problem?

Full trace:

```
03-04 23:16:49.036: E/AndroidRuntime(13765): FATAL EXCEPTION: main
03-04 23:16:49.036: E/AndroidRuntime(13765): android.view.InflateException: Binary XML file line #9: Error inflating class android.widget.DatePicker
03-04 23:16:49.036: E/AndroidRuntime(13765):    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:305)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at org.holoeverywhere.LayoutInflater.onCreateView(LayoutInflater.java:513)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at org.holoeverywhere.LayoutInflater.createViewFromTag(LayoutInflater.java:359)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at org.holoeverywhere.LayoutInflater.rInflate(LayoutInflater.java:647)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:465)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:415)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at org.holoeverywhere.LayoutInflater.inflate(LayoutInflater.java:410)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at com.crocodil.software.dwd.History.launchDeleteDiaryDialog(History.java:546)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at com.crocodil.software.dwd.History.onOptionsItemSelected(History.java:538)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.app.Activity.onMenuItemSelected(Activity.java:2566)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:383)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.support.v7.app.ActionBarActivity.superOnMenuItemSelected(ActionBarActivity.java:219)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.support.v7.app.ActionBarActivityDelegateICS.onMenuItemSelected(ActionBarActivityDelegateICS.java:159)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:117)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.onMenuItemSelected(ActionBarActivityDelegateICS.java:295)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:986)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at com.android.internal.view.menu.ListMenuPresenter.onItemClick(ListMenuPresenter.java:166)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.widget.AdapterView.performItemClick(AdapterView.java:298)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:2788)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.widget.AbsListView$1.run(AbsListView.java:3463)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.os.Handler.handleCallback(Handler.java:730)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.os.Handler.dispatchMessage(Handler.java:92)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.os.Looper.loop(Looper.java:137)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.app.ActivityThread.main(ActivityThread.java:5103)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at java.lang.reflect.Method.invokeNative(Native Method)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at java.lang.reflect.Method.invoke(Method.java:525)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at dalvik.system.NativeStart.main(Native Method)
03-04 23:16:49.036: E/AndroidRuntime(13765): Caused by: java.lang.reflect.InvocationTargetException
03-04 23:16:49.036: E/AndroidRuntime(13765):    at java.lang.reflect.Constructor.constructNative(Native Method)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at org.holoeverywhere.LayoutInflater._createView(LayoutInflater.java:281)
03-04 23:16:49.036: E/AndroidRuntime(13765):    ... 32 more
03-04 23:16:49.036: E/AndroidRuntime(13765): Caused by: java.lang.ClassCastException: org.holoeverywhere.widget.NumberPicker cannot be cast to android.widget.NumberPicker
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.widget.DatePicker.<init>(DatePicker.java:222)
03-04 23:16:49.036: E/AndroidRuntime(13765):    at android.widget.DatePicker.<init>(DatePicker.java:145)
03-04 23:16:49.036: E/AndroidRuntime(13765):    ... 35 more
```

**Comment by kkocel** [comment]
Are You using inflater from `Holo`

**Comment by yairohayon** [comment]
Thank you for your reply.
Yes , i am using the Holo inflater - you can see in the stack trace i attached.

**Comment by Prototik** [comment]
HoloEverywhere doesn't provide a DatePicker anymore. But this means that native version of this widget will be using. But native DatePicker using a NumberPicker, which is still provided by library. Dilemma.

So you should use a native layout inflater (which will not override a widgets) for inflating a datepicker. Something like this:
main.xml:

``` xml
<LinearLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:id="@+id/delete_diary_layout"
  android:layout_height="fill_parent" 
  android:minWidth="200dp"
  android:layout_width="fill_parent" android:orientation="vertical">
    <FrameLayout
        android:id="@+id/date_picker_panel"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />
</LinearLayout>
```

main_datepicker.xml:

``` xml
<DatePicker
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/date_picker"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content" />
```

In your activity:

``` java
@Override
public void onCreate(Bundle savedState) {
  super.onCreate(savedState);
  setContentView(R.layout.main);
  android.view.LayoutInfalter nativeInflater = (android.view.LayoutInfalter) superGetSystemService(Context.LAYOUT_INFLATER_SERVICE);
  nativeInflater.inflate(R.layout.main_datepicker, (FrameLayout) findViewById(date_picker_panel), true);
}
```
