### ISSUE TITLE
DemoApplication - Could not start application

### ISSUE THREAD

**Issue by oneassasin** [Prototik/HoloEverywhere#809]
```
03-19 13:55:56.941    6993-6993/org.holoeverywhere.demo E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.holoeverywhere.demo/org.holoeverywhere.demo.DemoActivity}: java.lang.RuntimeException: Couldn't bind menu on view
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2077)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2104)
            at android.app.ActivityThread.access$600(ActivityThread.java:134)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:4624)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Couldn't bind menu on view
            at org.holoeverywhere.slider.SliderMenu.bind(SliderMenu.java:272)
            at org.holoeverywhere.slider.SliderMenu.bind(SliderMenu.java:250)
            at org.holoeverywhere.slider.SliderMenu.makeDefaultMenu(SliderMenu.java:483)
            at org.holoeverywhere.addon.AddonSlider$AddonSliderA.obtainDefaultSliderMenu(AddonSlider.java:205)
            at org.holoeverywhere.demo.DemoActivity.onCreate(DemoActivity.java:27)
            at android.app.Activity.performCreate(Activity.java:4479)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1050)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2041)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2104)
            at android.app.ActivityThread.access$600(ActivityThread.java:134)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1247)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:4624)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by oneassasin** [comment]
Ssory, I forgot to write about the telephone. Android 4.0.3, ThL W3
Two weeks ago, everything was fine. I compiling demo app and succesfuly launched

**Comment by danbrough** [comment]
This error is back.
To fix: change the list id from "@android:id/list" to "@+id/slider_menu" in demo/res/layout-land/menu.xml
