### ISSUE TITLE
ListAdapterWrapper crashes on getlistAdapter

### ISSUE THREAD

**Issue by RichardLindhout** [Prototik/HoloEverywhere#820]
I use the Android Bootstrapp application with HoloEverywhere but I've spend alot of my time fixing this bug it happens when I scroll in my custom fragment pager but only if i view a page for the second time..

```
04-04 22:31:07.529    9335-9335/nl.webridge.whtsnxt.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ClassCastException: org.holoeverywhere.widget.ListAdapterWrapper
            at nl.webridge.whtsnxt.ui.ItemListFragment.getListAdapter(ItemListFragment.java:357)
            at nl.webridge.whtsnxt.ui.ItemListFragment.onLoadFinished(ItemListFragment.java:253)
            at nl.webridge.whtsnxt.ui.ItemListFragment.onLoadFinished(ItemListFragment.java:43)
            at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:427)
            at android.support.v4.app.LoaderManagerImpl$LoaderInfo.reportStart(LoaderManager.java:307)
            at android.support.v4.app.LoaderManagerImpl.doReportStart(LoaderManager.java:768)
            at android.support.v4.app.Fragment.performStart(Fragment.java:1533)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:958)
            at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:823)
            at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1129)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1485)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:472)
            at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1068)
            at android.support.v4.view.ViewPager.populate(ViewPager.java:914)
            at android.support.v4.view.ViewPager$3.run(ViewPager.java:244)
            at android.os.Handler.handleCallback(Handler.java:587)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3687)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Prototik** [comment]
You tried to cast ListAdapterWrapper to your own adapter impl.
Cause is ListView an automatically wrap any adapter to ListAdapterWrapper passed to.
So you can use `ListView.getAdapterSource()` instead of `getAdapter()`

**Comment by RichardLindhout** [comment]
Thanks that worked like a sharm!!
