### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by boonkerz** [Prototik/HoloEverywhere#848]
Download http://jcenter.bintray.com/nekohtml/nekohtml/1.9.6.2/nekohtml-1.9.6.2.jar
[Fatal Error] :6:3: Elementtyp "hr" muss mit dem entsprechenden Endtag "</hr>" beendet werden.

Its German but anyone knows why this error happends?

It means: Element "hr" must end with an "</hr>" tag

**Comment by Prototik** [comment]
And... Why this in HoloEverywhere's tracker?

**Comment by boonkerz** [comment]
i think it comes from holo.

gradlew clean with holo ends up in an error.
when i remove the holo dependencies it shows no error.

**Comment by boonkerz** [comment]
Current Debug on ./gradlew clean

```
21:29:53.963 [ERROR] [org.gradle.BuildExceptionReporter] 
21:29:53.964 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
21:29:53.965 [ERROR] [org.gradle.BuildExceptionReporter] 
21:29:53.965 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
21:29:53.965 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring project ':mec'.
21:29:53.965 [ERROR] [org.gradle.BuildExceptionReporter] > Couldn't determine a final version
21:29:53.966 [ERROR] [org.gradle.BuildExceptionReporter] 
21:29:53.966 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
21:29:53.968 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':mec'.
21:29:53.968 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:79)
21:29:53.968 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:74)
21:29:53.968 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
21:29:53.968 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:493)
21:29:53.969 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:80)
21:29:53.969 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:31)
21:29:53.969 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
21:29:53.969 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
21:29:53.969 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
21:29:53.970 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:64)
21:29:53.970 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
21:29:53.970 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
21:29:53.970 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:35)
21:29:53.970 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
21:29:53.970 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
21:29:53.971 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
21:29:53.971 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:201)
21:29:53.971 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
21:29:53.971 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
21:29:53.971 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
21:29:53.971 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
21:29:53.972 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
21:29:53.972 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.Main.doAction(Main.java:46)
21:29:53.972 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
21:29:53.972 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.Main.main(Main.java:37)
21:29:53.972 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
21:29:53.973 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
21:29:53.973 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
21:29:53.973 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
21:29:53.973 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
21:29:53.973 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
21:29:53.973 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.RuntimeException: Couldn't determine a final version
21:29:53.974 [ERROR] [org.gradle.BuildExceptionReporter]    at org.holoeverywhere.plugin.util.VersionHelper.resolveVersion(VersionHelper.groovy:36)
21:29:53.974 [ERROR] [org.gradle.BuildExceptionReporter]    at org.holoeverywhere.plugin.util.VersionHelper$resolveVersion.call(Unknown Source)
21:29:53.974 [ERROR] [org.gradle.BuildExceptionReporter]    at org.holoeverywhere.plugin.extension.LibraryContainer.resolveVersion(LibraryContainer.groovy:30)
21:29:53.974 [ERROR] [org.gradle.BuildExceptionReporter]    at org.holoeverywhere.plugin.extension.LibraryContainer$resolveVersion.call(Unknown Source)
21:29:53.974 [ERROR] [org.gradle.BuildExceptionReporter]    at org.holoeverywhere.plugin.HoloEverywhereCorePlugin.afterEvaluate(HoloEverywhereCorePlugin.groovy:49)
21:29:53.974 [ERROR] [org.gradle.BuildExceptionReporter]    at org.holoeverywhere.plugin.HoloEverywhereCorePlugin$_apply_closure1.doCall(HoloEverywhereCorePlugin.groovy:35)
21:29:53.975 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
21:29:53.975 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
21:29:53.975 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
21:29:53.975 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
21:29:53.975 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
21:29:53.976 [ERROR] [org.gradle.BuildExceptionReporter]    at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
21:29:53.976 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
21:29:53.976 [ERROR] [org.gradle.BuildExceptionReporter]    ... 29 more
21:29:53.976 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; Elementtyp "hr" muss mit dem entsprechenden Endtag "</hr>" beendet werden.
21:29:53.976 [ERROR] [org.gradle.BuildExceptionReporter]    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
21:29:53.976 [ERROR] [org.gradle.BuildExceptionReporter]    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
21:29:53.977 [ERROR] [org.gradle.BuildExceptionReporter]    at org.holoeverywhere.plugin.util.VersionHelper.resolveVersion(VersionHelper.groovy:18)
21:29:53.977 [ERROR] [org.gradle.BuildExceptionReporter]    ... 41 more
21:29:53.977 [ERROR] [org.gradle.BuildExceptionReporter] 
21:29:53.977 [LIFECYCLE] [org.gradle.BuildResultLogger] 
21:29:53.977 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
21:29:53.978 [LIFECYCLE] [org.gradle.BuildResultLogger] 
21:29:53.978 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 9.064 secs
```

**Comment by Prototik** [comment]
Sorry, indeed HoloEverywhere's issue, will fix in couple hours.

**Comment by Prototik** [comment]
Fixed.
