### ISSUE TITLE
Crash Preferences List

### ISSUE THREAD

**Issue by blackcarth** [Prototik/HoloEverywhere#89]
With Xperia S ( 2.3.7 - build 6.0.A.3.62), the demo crash when click on "List" in the "Preferences".

Works fine on Desire (2.3.5) & SIII (4.0.x).

``` java
E/AndroidRuntime( 5262): FATAL EXCEPTION: main
E/AndroidRuntime( 5262): android.view.InflateException: Binary XML file line #2: Error inflating class com.WazaBe.HoloEverywhere.internal.AlertController$RecycleListView
E/AndroidRuntime( 5262):    at android.view.LayoutInflater.createView(LayoutInflater.java:518)
E/AndroidRuntime( 5262):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
E/AndroidRuntime( 5262):    at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
E/AndroidRuntime( 5262):    at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
E/AndroidRuntime( 5262):    at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
E/AndroidRuntime( 5262):    at com.WazaBe.HoloEverywhere.internal.AlertController$AlertParams.createListView(AlertController.java:141)
E/AndroidRuntime( 5262):    at com.WazaBe.HoloEverywhere.internal.AlertController$AlertParams.apply(AlertController.java:127)
E/AndroidRuntime( 5262):    at com.WazaBe.HoloEverywhere.app.AlertDialog$Builder.create(AlertDialog.java:37)
E/AndroidRuntime( 5262):    at com.WazaBe.HoloEverywhere.preference.DialogPreference.showDialog(DialogPreference.java:267)
E/AndroidRuntime( 5262):    at com.WazaBe.HoloEverywhere.preference.DialogPreference.onClick(DialogPreference.java:147)
E/AndroidRuntime( 5262):    at com.WazaBe.HoloEverywhere.preference.Preference.performClick(Preference.java:535)
E/AndroidRuntime( 5262):    at com.WazaBe.HoloEverywhere.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:105)
E/AndroidRuntime( 5262):    at android.widget.AdapterView.performItemClick(AdapterView.java:288)
E/AndroidRuntime( 5262):    at android.widget.ListView.performItemClick(ListView.java:3514)
E/AndroidRuntime( 5262):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:1908)
E/AndroidRuntime( 5262):    at android.os.Handler.handleCallback(Handler.java:587)
E/AndroidRuntime( 5262):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 5262):    at android.os.Looper.loop(Looper.java:138)
E/AndroidRuntime( 5262):    at android.app.ActivityThread.main(ActivityThread.java:3701)
E/AndroidRuntime( 5262):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5262):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 5262):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:878)
E/AndroidRuntime( 5262):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
E/AndroidRuntime( 5262):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 5262): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 5262):    at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime( 5262):    at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
E/AndroidRuntime( 5262):    at android.view.LayoutInflater.createView(LayoutInflater.java:505)
E/AndroidRuntime( 5262):    ... 23 more
E/AndroidRuntime( 5262): Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
E/AndroidRuntime( 5262):    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
E/AndroidRuntime( 5262):    at android.widget.AbsListView.<init>(AbsListView.java:661)
E/AndroidRuntime( 5262):    at android.widget.ListView.<init>(ListView.java:167)
E/AndroidRuntime( 5262):    at android.widget.ListView.<init>(ListView.java:163)
E/AndroidRuntime( 5262):    at com.WazaBe.HoloEverywhere.internal.AlertController$RecycleListView.<init>(AlertController.java:288)
E/AndroidRuntime( 5262):    ... 26 more
W/ActivityManager(  278):   Force finishing activity com.WazaBe.HoloDemo/.HoloPreferenceActivity
```

**Comment by Prototik** [comment]
0x12 - boolean type. AlertController$RecycleListView override only one method, don't modify styles. You may send framework-res.apk from device?

In AOSP AbsListView.java doesn't occur at the call getDimensionPixelSize

**Comment by blackcarth** [comment]
The installed build of the Xperia was very "old" so I updated to the last one (6.1.A.2.45) and the the problem has disappeared.
Sorry to annoyed you with a <beep> configuration problem...
