### ISSUE TITLE
Crash on creating alert with multiple selection list on Sony experia play 2.3.4

### ISSUE THREAD

**Issue by ChrisDavis8** [Prototik/HoloEverywhere#98]
Again only happening on the experia play, other devices are fine

android.view.InflateException: Binary XML file line #2: Error inflating class com.WazaBe.HoloEverywhere.internal.AlertController$RecycleListView
        at android.view.LayoutInflater.createView(LayoutInflater.java:518)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.WazaBe.HoloEverywhere.internal.AlertController$AlertParams.createListView(AlertController.java:141)
        at com.WazaBe.HoloEverywhere.internal.AlertController$AlertParams.apply(AlertController.java:127)
        at com.WazaBe.HoloEverywhere.app.AlertDialog$Builder.create(AlertDialog.java:37)
        at com.WazaBe.HoloEverywhere.app.AlertDialog$Builder.show(AlertDialog.java:281)
        at com.WazaBe.HoloEverywhere.widget.Spinner$DialogPopup.show(Spinner.java:103)
        at com.WazaBe.HoloEverywhere.widget.Spinner.performClick(Spinner.java:539)
        at android.view.View$PerformClick.run(View.java:9229)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3701)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
        at android.view.LayoutInflater.createView(LayoutInflater.java:505)
        ... 20 more
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
        at android.widget.AbsListView.<init>(AbsListView.java:661)
        at android.widget.ListView.<init>(ListView.java:167)
        at android.widget.ListView.<init>(ListView.java:163)
        at com.WazaBe.HoloEverywhere.internal.AlertController$RecycleListView.<init>(AlertController.java:288)
        ... 23 more
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
        at android.view.LayoutInflater.createView(LayoutInflater.java:505)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.WazaBe.HoloEverywhere.internal.AlertController$AlertParams.createListView(AlertController.java:141)
        at com.WazaBe.HoloEverywhere.internal.AlertController$AlertParams.apply(AlertController.java:127)
        at com.WazaBe.HoloEverywhere.app.AlertDialog$Builder.create(AlertDialog.java:37)
        at com.WazaBe.HoloEverywhere.app.AlertDialog$Builder.show(AlertDialog.java:281)
        at com.WazaBe.HoloEverywhere.widget.Spinner$DialogPopup.show(Spinner.java:103)
        at com.WazaBe.HoloEverywhere.widget.Spinner.performClick(Spinner.java:539)
        at android.view.View$PerformClick.run(View.java:9229)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3701)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
        at android.widget.AbsListView.<init>(AbsListView.java:661)
        at android.widget.ListView.<init>(ListView.java:167)
        at android.widget.ListView.<init>(ListView.java:163)
        at com.WazaBe.HoloEverywhere.internal.AlertController$RecycleListView.<init>(AlertController.java:288)
        ... 23 more
java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
        at android.widget.AbsListView.<init>(AbsListView.java:661)
        at android.widget.ListView.<init>(ListView.java:167)
        at android.widget.ListView.<init>(ListView.java:163)
        at com.WazaBe.HoloEverywhere.internal.AlertController$RecycleListView.<init>(AlertController.java:288)
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
        at android.view.LayoutInflater.createView(LayoutInflater.java:505)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:570)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
        at com.WazaBe.HoloEverywhere.internal.AlertController$AlertParams.createListView(AlertController.java:141)
        at com.WazaBe.HoloEverywhere.internal.AlertController$AlertParams.apply(AlertController.java:127)
        at com.WazaBe.HoloEverywhere.app.AlertDialog$Builder.create(AlertDialog.java:37)
        at com.WazaBe.HoloEverywhere.app.AlertDialog$Builder.show(AlertDialog.java:281)
        at com.WazaBe.HoloEverywhere.widget.Spinner$DialogPopup.show(Spinner.java:103)
        at com.WazaBe.HoloEverywhere.widget.Spinner.performClick(Spinner.java:539)
        at android.view.View$PerformClick.run(View.java:9229)
        at android.os.Handler.handleCallback(Handler.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:130)
        at android.app.ActivityThread.main(ActivityThread.java:3701)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:507)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by Prototik** [comment]
Duplicate #89
You may upload framework-res.apk from device?

**Comment by ChrisDavis8** [comment]
Got it https://dl.dropbox.com/u/3215940/framework-res.rar

**Comment by Prototik** [comment]
Also framework.jar, please :)

**Comment by ChrisDavis8** [comment]
sure no problem
https://dl.dropbox.com/u/3215940/framework.jar

**Comment by Prototik** [comment]
Try this build: http://ubuntuone.com/5V92aLdQkHyS40ndhwiMFo

**Comment by ChrisDavis8** [comment]
Single selection alert list dialog and progress dialog work ok. Nice one :)
